### ISSUE TITLE
VS2015无法运行

### ISSUE THREAD

**Issue by DyncEric** [netease-im/NIM_Duilib_Framework#1]
## 重现步骤

1.
2.

**Comment by cqu227hk** [comment]
编译报错的信息方便贴一下吗？

**Comment by nmgwddj** [comment]
我们在使用 VS 高版本 IDE 打开项目后，将所有项目的工具集修改为 VS2015，编译会产生一些警告，由于警告级别设置为 4，所以将警告视为错误。最终 base 项目没有成功编译通过。该问题已经修复并提交上去，请见 https://github.com/netease-im/NIM_Duilib_Framework/commit/3b2ffb2debffc462cdc2e0fee0e368ace89f7e29

如果你的问题与我们描述的不一样，请根据 issue 模板将问题现象和重现步骤描述清楚，方便我们能快速重现并帮助你解决问题。

**Comment by DyncEric** [comment]
OK，已经修复了。谢谢
