### ISSUE TITLE
render.exe被360删掉

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#10]
## 问题现象
开着360
运行程序时， CEF render.exe进程会被360报毒杀掉

## 重现步骤

1. 开着360
2. 运行程序

可能和我用的版本有关，移植的之前PCDEMO 中的

**Comment by nmgwddj** [comment]
render.exe 进程源码十分简单，可以适当做一些精简看看具体哪块业务会导致误报。如果发布商业产品，可以打上数字签名，如果依然被某些杀软误报，可以提交程序资料申请添白。
