### ISSUE TITLE
如何交换两个控件呢，两控件直接父亲不相同

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#101]
![image](https://user-images.githubusercontent.com/16250519/62365265-3e62fb80-b556-11e9-8aa6-e35eeec51a46.png)

试过 pHorPane->SwapChild(pPPTCef, pIntWindow);     不行，必须同父亲才行
试过 
					pHorPane->AddAt(pPPTCef,0);
					pRightBox->AddAt(pIntWindow,0);
					pHorPane->Remove(pIntWindow);
					pRightBox->Remove(pPPTCef);      也不成功，

不知道 有没有什么方法，可以实现想交换位置时，就可以交换位置

**Comment by lovesnow** [comment]
使用Remove 就删除并释放了 
需要自己写个交换的方法

**Comment by shuilan0066** [comment]
成功了 ，Remove之前暂时先关闭SetAutoDestory，最后又开启了SetAutoDestory

					//切换成大屏
					pHorPane->AddAt(pIntWindow, 0);
					pRightBox->AddAt(pPPTCef, 0);

					pHorPane->SetAutoDestroy(false);
					pRightBox->SetAutoDestroy(false);

					pHorPane->Remove(pPPTCef);
					pRightBox->Remove(pIntWindow);

					pIntWindow->SetAttribute(L"width", L"stretch");
					pIntWindow->SetAttribute(L"height", L"stretch");

					pPPTCef->SetAttribute(L"width", L"400");
					pPPTCef->SetAttribute(L"height", L"300");

					pHorPane->SetAutoDestroy(TRUE);
					pRightBox->SetAutoDestroy(TRUE);
