### ISSUE TITLE
请问下ThreadManger当中的NonNestableTask和Task的区别是什么

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#106]
如题

**Comment by nmgwddj** [comment]
PostNonNestableTask 是发布一个不可在嵌套 MessageLoop 执行的任务，关于嵌套可参见这里：https://segmentfault.com/a/1190000016710643。

这个功能几乎在现有 UI 逻辑下不太可能会用到，我也是回头翻看了一下 base 的实现是对不可嵌套任务做了缓存，在空闲状态下去执行这些不可嵌套的任务内容，前提是说曾经出现过嵌套情况有过非嵌套任务的缓存。

**Comment by lovesnow** [comment]
3Q
