### ISSUE TITLE
cef 控件目前不支持录像吗

### ISSUE THREAD

**Issue by xuhuajie-NetEase** [netease-im/NIM_Duilib_Framework#107]
## 问题现象
用户反馈嵌入的页面的录像无法播放
## 重现步骤
![image](https://user-images.githubusercontent.com/53515032/63142821-fba52700-c01d-11e9-8334-28f027cb36a4.png)

1.
2.

**Comment by nmgwddj** [comment]
#6

**Comment by xuhuajie-NetEase** [comment]
thank you for replying
