### ISSUE TITLE
HBox 添加buttondown 事件 不起作用

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#11]
<HBox name="stdHBox" hotcolor="bk_menuitem_hovered" height="auto" padding="10,10,60,10" borderround="5,5" bordersize="1" bordercolor="lightcolor4" mouse="true">
	              		      		   
	              <Option class="circle_option_yellow" text="标准连麦" name="standard_option" group="layout" valign="center" margin="20,0,0,0" name="std_layout"/>
	              <Control />
	              <Button name="standard_option" bkimage="standard_int.png"  width="auto" height="auto"/>
                <Event type="buttondown" receiver=".\std_layout" applyattribute="selected=&quot;true&quot;" />
                                 
	          </HBox>

EVENT事件不起作用  ，调试发现，刚开始时XML加载了该事件，但handlemessage时，事件又没有了，不知道怎么回事

**Comment by nmgwddj** [comment]
@shuilan0066 你应该把 HBox 更换为 ButtonBox。

**Comment by nmgwddj** [comment]
或者你可以把 Control 的 mouse 属性设置为 false，因为你点击界面中间的时候，Control 控件拦截了鼠标点击消息。
如果你希望点击 HBox 任何一个位置都响应你写的 Event，应该把 Option、Control 的 mouse 属性都设置为 false，让他们不要抢占点击事件。

上面说的 ButtonBox 的做法是自由布局属性的，所以可能跟你的场景不太符合。

**Comment by nmgwddj** [comment]
或者你可以把 Control 的 mouse 属性设置为 false，因为你点击界面中间的时候，Control 控件拦截了鼠标点击消息。
如果你希望点击 HBox 任何一个位置都响应你写的 Event，应该把 Option、Control 的 mouse 属性都设置为 false，让他们不要抢占点击事件。

上面说的 ButtonBox 的做法是自由布局属性的，所以可能跟你的场景不太符合。

**Comment by shuilan0066** [comment]
@nmgwddj   嗯  可行  将子控件 mouse都设置为false后， 实现了这种效果  响应了点击事件
