### ISSUE TITLE
符合模式下出现IsKeyboardEnabled 未声明

### ISSUE THREAD

**Issue by tongso** [netease-im/NIM_Duilib_Framework#110]
项目符合模式引用编译时报如下错误:
严重性	代码	说明	项目	文件	行	禁止显示状态

错误	C2065	“IsKeyboardEnabled”: 未声明的标识符	\nim_duilib_framework development\tool_kits\duilib\control\button.h	30	

错误	C3861	“IsKeyboardEnabled”: 找不到标识符 \nim_duilib_framework-development\tool_kits\duilib\control\button.h	30	

错误	C2065	“IsEnabled”: 未声明的标识符	\nim_duilib_framework-development\tool_kits\duilib\control\button.h	30	

错误	C3861	“IsEnabled”: 找不到标识符 \nim_duilib_framework-development\tool_kits\duilib\control\button.h	30

**Comment by nmgwddj** [comment]
@tongso 已经处理这个问题，https://github.com/netease-im/NIM_Duilib_Framework/commit/45c5104ce0589ca378770e1095442e45a2fa9cc3。
