### ISSUE TITLE
最新的属性列表在哪里呢  在另一项目中 有属性列表但是07年的，最新的有么

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#112]
最新的属性列表在哪里呢  在另一项目中 有属性列表但是07年的，最新的有么

**Comment by nmgwddj** [comment]
控件或布局文档中有描述

![2019-08-30_14-03-05](https://user-images.githubusercontent.com/13995319/64000438-54091800-cb38-11e9-9654-abd8f8a89fda.png)
