### ISSUE TITLE
MsgBox的bug

### ISSUE THREAD

**Issue by kira-96** [netease-im/NIM_Duilib_Framework#113]
## 问题现象
1. ESC键按下无效
2. 激活窗口后再按下Enter键无效

## 重现步骤
第一个问题还可以解决  
``` cpp
LRESULT MsgBox::OnKeyDown(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	if (wParam == VK_ESCAPE)
	{
		OnEsc(bHandled);
	}
	return __super::OnKeyDown(uMsg, wParam, lParam, bHandled);
}
```

第二个问题  
1. 弹出`MsgBox`后，点击MsgBox（非按钮区域）
2. 按下`Enter`键，MsgBox不会消失（弹出后直接按`Enter`会消失）

**Comment by nmgwddj** [comment]
的确代码中虽然后针对按下 ESC 键的方法，但是并没有响应相应的事件，用您的做法完全是可行的。与 ESC 一样，界面中按下回车键实际都要看交互的细节，可能有些交互场景就是需要点击界面某处默认按钮失去焦点从而失效。如果你希望按下回车无条件执行默认处理流程，一样可以像处理 ESC 键一样处理 VK_RETURN。

Msgbox 为一个示例的组件，您可以自由拓展，也欢迎你将完善的代码以 PR 的方式提交至 development 分支，帮助我们完善这方面的功能。

**Comment by kira-96** [comment]
好的，已经解决了，谢谢。
刚刚接触这个，感觉非常不错，希望越来越好！
