### ISSUE TITLE
ToWeakCallback 是否真的安全了？

### ISSUE THREAD

**Issue by xuhuajie-NetEase** [netease-im/NIM_Duilib_Framework#115]
## 问题现象
	// Using ToWeakCallback to protect closure when if [ControlForm] was destoryed 	 
        nbase::ThreadManager::PostTask(kThreadGlobalMisc, ToWeakCallback(closure));

        我仔细研究代码发现，ToWeakCallback的原理是采用weak_ptr去观察supportweakcallback。
       然后重载() 中判断weak_ptr的有效性，如果有效，则执行函数。
        
![IMG20190912102338](https://user-images.githubusercontent.com/53515032/64749231-68411200-d547-11e9-83a1-df14d30af64f.png)

## 重现步骤

1.
2.

**Comment by xuhuajie-NetEase** [comment]
![image](https://user-images.githubusercontent.com/53515032/64750425-7a24b400-d54b-11e9-87de-c865fcfdd40f.png)
//Using ToWeakCallback to protect closure when if [ControlForm] was destoryed
保护不住 :)

**Comment by xuhuajie-NetEase** [comment]
例子用的samples里面的controls

**Comment by nmgwddj** [comment]
ToWeakCallback 能保证的是在任务队列拿到任务时，该任务是有效的。你这种场景应该使用 PostDelayedTask，尽量不要使用 Sleep。

**Comment by xuhuajie-NetEase** [comment]
我用的Sleep是为了强行触发我描述的
![image](https://user-images.githubusercontent.com/53515032/64753105-8feaa700-d554-11e9-8bab-8ff1c7e49dc1.png)
判断时有效，运行时失效

**Comment by xuhuajie-NetEase** [comment]
我的本意是 ，ToWeakCallback不是绝对的安全
当task的任务比较复杂且繁重，耗时过多时，比如耗时的循环运算（这里简单的用sleep模拟而已）。还是有崩溃的可能性

**Comment by nmgwddj** [comment]
任务投递到指定的线程中是线性执行的，耗时的任务会阻塞当前线程，其他任务在队列中是排队等待执行状态的。

确保任务投递是正确的线程，比如你对 UI 的操作 SetRoundCorner 应该单独投递到 UI 线程中，而不是在杂事线程执行，这样就会出现 UI 被关闭，而其他线程还在操作 UI 导致崩溃的情况。

**Comment by xuhuajie-NetEase** [comment]
唔，您还是太纠结我给的例子了。（我赞同您的关于界面元素放UI线程的操作的原则，也是我实际上编码给自己的原则，因为Duilib元素多线程不安全。）
我之前在思考野指针的防范问题。
![image](https://user-images.githubusercontent.com/53515032/64931853-bfa7f080-d86d-11e9-8737-0e3168c1f571.png)
看到了云信给了一种通过弱引用观察目标对象的方法（目前的weakcallback这一套）而喜出望外。
当我打算在博客详细剖析这一套原理时，发现了一个缺点。
即WeakCallback并非绝对的安全，原因在于WeakCallback在执行绑定的函数前，判断了下weak_ptr的有效性，然后执行绑定函数。我反思了下，如果在执行函数过程中weak_ptr无效了呢。尽管，WeakCallback只写了一行执行的代码，但这个函数可以很复杂，
如：   dosomethingwithSupportWeakCallBackentity();
          httpwork();  //it takes time
          dosomethingwithSupportWeakCallBackentity();  //it maybe not safe and crash if 
                                                                                       //SupportWeakCallBackentity destroyed
。
于是我才简单的写了一个例子验证了下。
![image](https://user-images.githubusercontent.com/53515032/64932136-95efc900-d86f-11e9-9a76-6d805fdb3d45.png)
Using ToWeakCallback to protect closure when if [ControlForm] was destoryed
如果你使用了ControlForm ，那么实际上并不能protect。
如果你没有使用（demo确实没有使用到），那么无所谓protect。

额。说了这么多，我的意思是WeakCallback 仍然不是野指针的完美解决方案。多线程的语义下，仍然有崩溃的风险。只要SupportWeakCallBack实体（设计的初衷这个类不一定是界面元素吧）突然在其他线程上被释放。

**Comment by xuhuajie-NetEase** [comment]
可能是我误解了设计者的意思。
如果界面元素继承了SupportWeakCallBack，而且都放UI线程判断的话，确实是安全的。
即任意继承了SupportWeakCallBack的对象，都放到同一个线程中进行判断的话，都是安全的。
我们客户端大部分用到的都是UI元素以及基于UI元素的业务。
这个weakcallback设计还是挺好的。

嗯嗯，看来彻底解决野指针确实比较困难。

这个深入去了解还是有一定意义的，希望这个issue也能给其他人带来帮助

**Comment by caop3ng** [comment]
感觉不是野指针的问题，好像 SupportWeakCallBack 不是线程安全的。

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 你说的很有道理，这个讨论很有意义，能让大家了解一下目前现有的这个线程模型的大致工作原理。像你说的一样，这个并不是绝对安全的，需要使用者通过规则来做一些人为限定减少这种错误。也可以在指定线程函数中增加一些校验（类似于 Chromium base 中的当前线程检查）

ToWeakCallback 的目的是确保在任务从任务列表取出时是有效的，他并不能保证任务执行过程中任务包中所需的资源是有效的。

C++ 11 中增加了一些智能指针对象，为了让开发者尽量减少内存泄露，但依然可能会因为使用问题导致一些陷阱出现。所以我觉得在了解了 ToWeakCallback 的目的后做一些人为限制是有必要的。

**Comment by smallevilbeast** [comment]
我今天也遇到了， 打开窗口， 网络下载回调， 然后关闭窗口， 下载完成后在PostUi在主线程执行的 nbase:Bind的回调    程序直接挂了 @xuhuajie-NetEase  @nmgwddj  - -

**Comment by smallevilbeast** [comment]
如果判断nbase:Bind的回调 已经失效

**Comment by nmgwddj** [comment]
@smallevilbeast 网络下载的回调中如果操作 UI 窗口，请单独投递任务到 UI 线程中，不要在网络下载回调中直接操作 UI。参考示例：https://github.com/netease-im/NIM_PC_Demo/blob/81fecb3edb941008390adc81eb1e2e109dad90ef/chatroom/gui/chatroom_form_msg.cpp#L128

**Comment by xuhuajie-NetEase** [comment]
@smallevilbeast  ![image](https://user-images.githubusercontent.com/53515032/65293778-fd1ebd80-db8e-11e9-94a1-ead4e787ca26.png)

**Comment by tick90011** [comment]
写这块代码的时候也有疑惑 ,想着也不是绝对安全的.  自己写了段代码验证, 果然如此, 网上一搜,发现同道中人啊.  O(∩_∩)O哈哈~
