### ISSUE TITLE
NIM DUILIB 能像原DUILIB那样嵌入到MFC中使用吗？

### ISSUE THREAD

**Issue by yangguang0756** [netease-im/NIM_Duilib_Framework#116]
如果可以，能否提供一个简单的集成思路呢

**Comment by nmgwddj** [comment]
我们没有尝试过，从个人角度而言，不推荐这样混合使用。所以很想了解一下为什么要与 MFC 混合使用？

**Comment by yangguang0756** [comment]
目前有这么一个需求，独立主程序已经用NIM-DUILIB开发，但是软件有一部分是OFFICE插件，也想用NIM-DUILIB绘制插件内部的界面，因为NIM-DUILIB有自己的线程机制，目前不知道怎么类似原版DUILIB那样的方式集成？

**Comment by nmgwddj** [comment]
可以参考 CefNativeControl（真窗口模式）将 MFC 的窗口嵌入到 Duilib 绘制的界面中。Duilib 主窗口和自定义控件都是有独立的窗口句柄的。

**Comment by yangguang0756** [comment]
上述需求可能没描述清楚，比如拟开发一个EXCEL插件，已获取到EXCEL的主窗体HWND，现需要绘制NIM-DUILIB的界面到主GUI线程，并附加到主窗体HWND。因为目前实例都是独立NIM-DUILIB主线程运行的，不清楚NIM-DUILIB的界面如何嵌入到其他第三方主线程？

P.S. 对于NIM-DUILIB，MFC窗口嵌入是没问题的。

**Comment by nmgwddj** [comment]
@yangguang0756 不知道消息过滤器是不是你想要的，你可以实现一个简单的消息过滤器，将过滤器添加到过滤器列表，来处理你关心的内容：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Controls/Window.md#AddPreMessageFilter

**Comment by yangguang0756** [comment]
好的，我参考一下。我确认一下：NIM-DUILIB是不是可以不用NIM自己的线程机制，可以通过简单的消息过滤器直接嵌入到第三方主线程？

**Comment by nmgwddj** [comment]
暂时关闭这个 Issue，如果您有其他问题，可以重新打开这个 Issue.
