### ISSUE TITLE
AnimationPlayer能否设置参数实现类似购物车抛物线的效果

### ISSUE THREAD

**Issue by smallevilbeast** [netease-im/NIM_Duilib_Framework#118]
建一个窗口，移动窗口的坐标

类似下图的效果
![20160919155449773](https://user-images.githubusercontent.com/1271747/65152093-df9c0780-da59-11e9-9c76-ec9fff3086c8.gif)

**Comment by nmgwddj** [comment]
移动是没有问题的，主要是移动的路径可能要自己算一下，移动动画可以参考窗口淡入淡出的实现，将淡入淡出修改为移动坐标。

**Comment by smallevilbeast** [comment]
好 我看下
