### ISSUE TITLE
debug环境下，有时候 窗口显示不出，比如右键菜单，设置等窗口

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#12]
## 问题现象
debug环境下，不稳定，诸如 菜单、设置等窗口 偶现 出现不了情况，但工具栏上有他们的窗口，就是不能显示出来
## 重现步骤

1.debug环境
2.诸如右键菜单、 设置页面等

release环境下，还没出现过

**Comment by nmgwddj** [comment]
@shuilan0066 请问怎么能重现您描述的问题，能否提供一个示例程序或者动态图片？您在重现步骤中仅仅是重复的描述了一下问题现象，我们没办法单独通过这个现象重现这个问题。

**Comment by nmgwddj** [comment]
@shuilan0066 由于没能收到您的及时反馈，该问题将关闭，如果您有进一步重现该问题的方法，请重新打开这个 issue。

**Comment by shuilan0066** [comment]
复现了
使用网易纯直播demo 

https://yx-web-nosdn.netease.im/package/LiveStreaming_Windows_Demo_v2.7.0.zip?download=LiveStreaming_Windows_Demo_v2.7.0.zip


添加进采集系统声音后， 点击关于， 这个弹窗就会出现黑色、或不出现等问题

debug下，频繁出现   release下 大部分机子正常 ，但有些机子也会出现弹窗窗口 不能显示等问题

**Comment by shuilan0066** [comment]
@nmgwddj

**Comment by shuilan0066** [comment]
![2](https://user-images.githubusercontent.com/16250519/59147932-64778e00-8a34-11e9-8c7e-1aa991f6131d.gif)
