### ISSUE TITLE
事件注册没有去重逻辑

### ISSUE THREAD

**Issue by xuhuajie-NetEase** [netease-im/NIM_Duilib_Framework#122]
调用多次AttachButtonUp 会导致注册重复的事件

	void AttachButtonUp(const EventCallback& callback)
	{
		OnEvent[kEventMouseButtonUp] += callback;
	}
![image](https://user-images.githubusercontent.com/53515032/65582721-829bd680-dfb0-11e9-939e-d6b287fd8862.png)

而原版Duilib是去重的。
![image](https://user-images.githubusercontent.com/53515032/65582767-98a99700-dfb0-11e9-9bae-939200f6629f.png)

希望加上。

之前为了防止重复注册，都是在DoInit去注册事件。
但我手头上遇到了一个问题，希望调用InitSomeThing的时候注册。而这个函数有可能多次调用。

**Comment by xuhuajie-NetEase** [comment]
![image](https://user-images.githubusercontent.com/53515032/65583050-1f5e7400-dfb1-11e9-9825-9e3686306261.png)
这个是控制多行显示与折叠的方法，我希望在里面实现事件的响应，但目前来看，会导致重复注册事件

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 允许注册多个回调的口子在某些场景下可能真的会用到，有些牵强的例子是一个控件的变化希望通知多个类来处理产生的变化。如果这个口子关掉的话，类似需求可能实现起来会稍有麻烦。
所以可能更倾向于在接口中传参决定是否允许重复注册，或者从调用方做避免重复处理，比如 std::call_once、临时成员变量都可以应付这种情况。

**Comment by xuhuajie-NetEase** [comment]
嗯嗯，支持可以注册多个事件，但对于重复的注册事件希望能自动去重。
如  clickfun()  clickfun2 （）
AttachButtonUp(  clickfun )
AttachButtonUp(  clickfun2 )
AttachButtonUp(  clickfun )

经过这三步之后
原版的Duilib对clickfun去重，仍然只有两个回调   clickfun()  clickfun2（）
我们的Duilib则有三个回调  clickfun()  clickfun2（）clickfun（）
其中 clickfun重复注册了，导致会执行两遍（这肯定是无用且浪费的）。

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 这个问题当做缺陷来处理，细心的发现。

**Comment by xuhuajie-NetEase** [comment]
这个问题看来没有简单的解决办法。
std::function不支持==，拿到原来函数地址也很困难。
std::function可以保留1）普通的函数指针 2）lambda 3）仿函数对象 4）类静态成员函数 5）类普通成员函数（通过bind）。
经测试，只有1）和 4） 可以通过target拿到裸指针，其他返回nullptr
参考https://stackoverflow.com/questions/18039723/c-trying-to-get-function-address-from-a-stdfunction
https://stackoverflow.com/questions/10938774/get-function-pointer-from-stdfunction-when-using-stdbind

**Comment by nmgwddj** [comment]
您提出这个问题后我们讨论了一下，的确如您所说用的最多的成员函数和lambda是无法拿到地址的，这个问题相对麻烦一些，由于影响不是很大且有其他避免方案，所以这个问题可能会被搁置处理。

**Comment by znone** [comment]
std::function会复制传入的函数，如果传入函数对象，target()应该是得到这个被复制后的对象的地址，需要该函数对象能比较。通常函数对象都不能比较,，且std::function并不知道传入的函数对象类型，这才是无法实现该需求的真正原因。

**Comment by nmgwddj** [comment]
由于没有更合理的处理方案，该问题暂时关闭，建议使用者在注册时做重复检测。

**Comment by chaome** [comment]
不能在框架层去重，所有代码执行必须达到结果。不允许因为之前调用过，本次调用就无效。
包括因为各种原因引起的意外调用。

可以参考C#事件 +=，反复+=会多次注册的。
