### ISSUE TITLE
Combo 选项文字渲染问题

### ISSUE THREAD

**Issue by tornodo** [netease-im/NIM_Duilib_Framework#123]
![微信截图_20190929120110](https://user-images.githubusercontent.com/4067864/65826034-e116cc80-e2b0-11e9-9e88-b2583279c680.png)
如图所示，背景是半透明色，文字像是添加了阴影效果一样。
文档查询不好用，最终都得查到Control上😅。有些控件如VList，HList都没有写出来，不查issue都不知道有这控件。

**Comment by nmgwddj** [comment]
@tornodo https://github.com/netease-im/NIM_Duilib_Framework/commit/040440c497cfac162aa3b21b7ca7f40ae96ca9ef 在绘制文字时使用了抗锯齿效果来避免这个问题，请尝试拉取 development 最新的提交来修补这个问题。

**Comment by tornodo** [comment]
这样字体变模糊了，不知道windows下渲染字体还有什么好方法不？为什么默认方式只有在combo上背景半透明时会出现这问题，而label控件放透明背景上都没有问题？ 
@nmgwddj

**Comment by tornodo** [comment]
@nmgwddj 
我测试的时候使用这个设置感觉解决了。
graphics.SetTextRenderingHint(Gdiplus::TextRenderingHintAntiAliasGridFit);
