### ISSUE TITLE
Visual Studio 2019 (v142) 编译 ui_components 失败

### ISSUE THREAD

**Issue by 01haike** [netease-im/NIM_Duilib_Framework#124]

**Comment by caop3ng** [comment]
@nmgwddj 有计划解决这个吗 hah

**Comment by EssenRoc** [comment]
+1

**Comment by nmgwddj** [comment]
@01haike @caop3ng @EssenRoc 已经在 development 分支中提交了修复，但这样做不是很得体，不过可以临时解决编译不通过的问题。

如果为了兼容不同版本编译器可能未来增加的友元类越来越多，甚至还要加上一些宏判断，所以不是很理想，我们会再讨论更合适的方法。
