### ISSUE TITLE
OpenResZip 如果zip文件加密码就会失败

### ISSUE THREAD

**Issue by u0yiji1** [netease-im/NIM_Duilib_Framework#125]
## 问题现象

ui::GlobalManager::OpenResZip(MAKEINTRESOURCE(IDR_THEME), L"THEME", "password");
给resources.zip加上密码之后 就打不开程序了 提示找不到资源了

这个密码是需要什么格式的?
我用7zip winrar 给文件加密 
加密算法 不管是选aes-256或者ZipCrypto 都不行

## 重现步骤

给resources.zip加上密码之后 就打不开程序了

**Comment by nmgwddj** [comment]
@u0yiji1 

1. 压缩时注意是否将资源的目录层级，压缩包打开第一级目录应该是 resources 文件夹：
![image](https://user-images.githubusercontent.com/13995319/66361849-fd9ebd00-e9b2-11e9-85a2-2255f6048487.png)
2. 修改了压缩密码后要重新编译程序让其把新的压缩包资源嵌入到程序中，同时注意 OpenResZip 方法中要传入密码：
```
ui::GlobalManager::OpenResZip(MAKEINTRESOURCE(IDR_THEME), L"THEME", "your password");
```
3. 使用通用的 zip 压缩工具都可以识别，我试过好压、7zip（默认zip压缩配置）都可以正常使用。

**Comment by u0yiji1** [comment]
@nmgwddj  感谢你的回答 但是我按照你说的方式做了 依然是不行的 不知道为什么 
解压密码是pass
![image](https://user-images.githubusercontent.com/39235248/66579511-85e9b180-ebaf-11e9-9924-9c481c7a6125.png)
![image](https://user-images.githubusercontent.com/39235248/66579573-99951800-ebaf-11e9-9cc1-25ea74bc372b.png)

ui::GlobalManager::OpenResZip(MAKEINTRESOURCE(IDR_THEME), L"THEME", "pass");
然后重新编译 
运行后出现以下错误
![image](https://user-images.githubusercontent.com/39235248/66579803-f8f32800-ebaf-11e9-88e9-fa7ff9489ee8.png)

**Comment by nmgwddj** [comment]
加密算法由 AES-256 修改为 ZipCrypto 试一试，如果依然不行，源代码都是开放的，可以按步调试代码找到打开失败原因。

![image](https://user-images.githubusercontent.com/13995319/66617707-ce818900-ec08-11e9-9d64-7f64cb8d2eb6.png)

**Comment by smallevilbeast** [comment]
@nmgwddj 我今天试了下 加密是有问题， 加密后  有些图片显示不出来  暂不知道原因

**Comment by smallevilbeast** [comment]
@nmgwddj 已提交PR #143 @u0yiji1  可以再测试下

**Comment by u0yiji1** [comment]
@smallevilbeast  经测试 已修复此问题 多谢
