### ISSUE TITLE
当窗口最大化时被拖动，最大化按钮未恢复

### ISSUE THREAD

**Issue by EssenRoc** [netease-im/NIM_Duilib_Framework#126]
## 问题现象

当窗口最大化时被拖动，最大化按钮未恢复

另外当按钮被按下并且处于未放开状态时，移动鼠标经过其他按钮或控件时不应该触发点燃其他组件状态(或者说此时不应该使其他控件处于高亮状态)

## 预期结果

最大化按钮应当恢复状态

正常状态：
![image](https://user-images.githubusercontent.com/12685126/66392664-1d5dd180-ea03-11e9-956f-e9ae591f28f3.png)

目前状态：

![image](https://user-images.githubusercontent.com/12685126/66392684-2c448400-ea03-11e9-97aa-baf807f3f8b0.png)

## 重现步骤

1.运行 basic_d.exe
2.最大化窗口
3.鼠标移动至标题栏，按下左键并拖动窗口，此时窗口已经恢复，但是最大化按钮未恢复。

**Comment by nmgwddj** [comment]
最大化按钮问题请参考：https://github.com/netease-im/NIM_Duilib_Framework/issues/4
鼠标按下状态不切换焦点到其他控件我尝试做了一个改动，请参考此次提交：https://github.com/netease-im/NIM_Duilib_Framework/commit/79980b5a11ecb8cf46d1a1a8116d6d954a5ee92c

**Comment by EssenRoc** [comment]
感谢
