### ISSUE TITLE
Label想办法自动地控制tooltip的显示与否

### ISSUE THREAD

**Issue by xuhuajie-NetEase** [netease-im/NIM_Duilib_Framework#129]
大多数场景下，产品经理希望有字体显示不全的时候用省略号。
     而有省略号的时候希望有tooltip已完整显示原先的内容。
     没有省略号的时候则不太希望有tooltip。

     我的想法是，增加一个属性，如autotooltip="true"。来达到上面的功能。
     内部实现通过在PaintText时，判断下字体需要的区域大小与控件的区域大小（paint时，区域比较正确了），如果字体需要的区域大，则控制tooltip显示，否则tooltip不显示。

**Comment by xuhuajie-NetEase** [comment]
另外，我发现多行tooltip会有明显的闪动现象
复现办法，basic.xml中tooltiptext设置足够大
tooltiptext="一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮一个简单窗口，带有标题栏和常规按钮"
![tooltip](https://user-images.githubusercontent.com/53515032/66557732-f16a5980-eb84-11e9-9195-243c31c1ad1e.gif)

**Comment by xuhuajie-NetEase** [comment]
good，已经不闪烁了！
![image](https://user-images.githubusercontent.com/53515032/66619892-1e644e00-ec11-11e9-892a-72e899ebdbb4.png)
这个为啥注释掉不理解。

**Comment by xuhuajie-NetEase** [comment]
【增加tooltip的省略号下自动显示控制】 #153
如果ok的话，可以关闭该issue

**Comment by nmgwddj** [comment]
Finished by PR #153, doc: 16a8bf41edba113fb05438c0029b2a54c997e532
