### ISSUE TITLE
能不能封装个 视频播发器控件 比如 VLC

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#132]
能不能封装个 视频播发器控件 比如 VLC

如题，如果有视频播发器控件， 播放视频什么的 就方便多了

**Comment by nmgwddj** [comment]
@shuilan0066 可以参考 nim_demo 的示例：https://github.com/netease-im/NIM_PC_Demo/blob/a0292a35e4c74bf18e514e61fea07c862aecf1a7/tool_kits/ui_component/ui_kit/gui/session/dragdrop/bitmap_control.cpp，CBitmapControl 提供了基础的 RGB 数据绘制功能，Demo 代码中也包含了丰富的 YUV 转 RGB 的示例，您可以在这个基础上稍加拓展就可以实现一个简单的视频播放器。
