### ISSUE TITLE
cef控件 不支持flash播放，请支持

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#138]

**Comment by nmgwddj** [comment]
将指定版本的 PPAPI 插件放到代码指定的目录下即可，PPAPI 插件更新频繁，所以项目中没有携带附件。
https://github.com/netease-im/NIM_Duilib_Framework/blob/ad9a6b3edc0c330ff0a7c195ae1dbdf066f5c8ba/ui_components/cef_control/app/client_app.cpp#L28

**Comment by swiftlc** [comment]
代码有没有放在其他仓呢，我github上拉太慢了


| |
swiftlc
|
|
swiftlc@163.com
|
签名由网易邮箱大师定制
在2019年11月11日 10:22，Dylan<notifications@github.com> 写道：

将指定版本的 PPAPI 插件放到代码指定的目录下即可，PPAPI 插件更新频繁，所以项目中没有携带附件。
https://github.com/netease-im/NIM_Duilib_Framework/blob/ad9a6b3edc0c330ff0a7c195ae1dbdf066f5c8ba/ui_components/cef_control/app/client_app.cpp#L28

**Comment by nmgwddj** [comment]
@swiftlc 暂时还没有其他仓库的地址，我们正在考虑是否提供其他镜像地址。您可以使用 github 桌面客户端来尝试下载代码。
