### ISSUE TITLE
按照邮件提示增加了pepflashplayer.dll 依旧加载不出flash内容

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#139]
Command:
--type=ppapi --channel="49664.1.2013368148\456450498" --no-sandbox --ppapi-flash-args --lang=en-US --device-scale-factor=1 --lang=en-US --log-file="C:\open_source\NIM_Duilib_Framework\examples\multi_browser\..\..\bin\cef_temp\cef.log" /prefetch:3

[1111/140046:ERROR:ppapi_thread.cc(331)] Failed to load Pepper module from PepperFlash\pepflashplayer.dll (error: 193)

**Comment by nmgwddj** [comment]
第一，请确认你使用的 PPAPI 插件是 32 位版本，如果你系统已经安装，可以到 C:\Windows\SysWOW64\Macromed\Flash 目录下去复制对应的 PPAPI 插件文件：
![2019-11-11_14-05-14](https://user-images.githubusercontent.com/13995319/68565177-a8f8d100-048d-11ea-8c31-dc13cf8e1f37.png)
第二，你要确保复制到的文件路径和代码中标记的文件路径是一致的：
![image](https://user-images.githubusercontent.com/13995319/68565224-ccbc1700-048d-11ea-8447-308a5379f829.png)
![image](https://user-images.githubusercontent.com/13995319/68565236-d776ac00-048d-11ea-8741-0d5132f8eb28.png)
最后验证可以打开一些带有 Flash 功能的网站或者其他页面来进行测试
![2019-11-11_14-14-00](https://user-images.githubusercontent.com/13995319/68565295-0856e100-048e-11ea-8a01-911968320cd0.png)
