### ISSUE TITLE
目前使用的是本地资源图片，能不能扩展成网络资源

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#14]
当前资源都是本地的
能不能扩展成 可以使用 网络地址，提供网络下载资源方法呢

**Comment by nmgwddj** [comment]
@shuilan0066 即使是网络图片方案也是缓存到本地来使用，这是上层应用可控行为可以自己来实现的。
另外你可以使用 CEF 控件纯前端方式实现界面，Native 程序只是一个壳儿，这样把图片下载缓存等工作交给 CEF 来帮你处理就很省心了。
