### ISSUE TITLE
这里注释有一处错误

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#140]
NIM_Duilib_Framework\base\callback.h

line 111  [多个不带cancel]->[多个带cancel]
-------------------------------------

ahahah

**Comment by nmgwddj** [comment]
细心的观察。

**Comment by nmgwddj** [comment]
Fixed by commit: https://github.com/netease-im/NIM_Duilib_Framework/commit/256432c80ca65accbdc395b9dcdae7c8f94743e1
