### ISSUE TITLE
发现一个RichEdit的bug

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#141]
![1](https://user-images.githubusercontent.com/27080019/68592148-56d7a000-04cd-11ea-8201-1cac96141655.PNG)

richedit内容透视

**Comment by smallevilbeast** [comment]
可以使用SetAlphaFixCorner，  修复这个问题

**Comment by smallevilbeast** [comment]
#87  之前也遇到到，使用window的SetAlphaFixCorner 可以修复

**Comment by swiftlc** [comment]
Ok




2019-11-13
----------------
成都奇鲁科技有限公司(鲁大师)
姓名：刘成
手机：19982746042
邮件：swiftlc@163.com
在2019年11月13日 21:41，evilbeast 写道：

#87 之前也遇到到，使用window的SetAlphaFixCorner 可以修复

**Comment by swiftlc** [comment]
请问window调用这个方法设置有效的时机是什么，我在InitWindow方法中调用最终无效果

**Comment by IULOVE** [comment]
> 可以使用SetAlphaFixCorner， 修复这个问题

SetAlphaFixCorner 这个是啥怎么用呢，百度没搜到啊

**Comment by swiftlc** [comment]
大概意思会在一个layered窗口下面贴一个黑窗，黑窗相比layered窗口内缩大小就是 设置参数




2019-11-29
----------------
成都奇鲁科技有限公司(鲁大师)
姓名：刘成
手机：19982746042
邮件：swiftlc@163.com
在2019年11月29日 16:50，xiaoniu 写道：

可以使用SetAlphaFixCorner， 修复这个问题

SetAlphaFixCorner 这个是啥怎么用呢，百度没搜到啊

**Comment by IULOVE** [comment]
> 大概意思会在一个layered窗口下面贴一个黑窗，黑窗相比layered窗口内缩大小就是 设置参数 2019-11-29 ---------------- 成都奇鲁科技有限公司(鲁大师) 姓名：刘成 手机：19982746042 邮件：swiftlc@163.com 在2019年11月29日 16:50，xiaoniu 写道： 可以使用SetAlphaFixCorner， 修复这个问题 SetAlphaFixCorner 这个是啥怎么用呢，百度没搜到啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哦···能给个设置方法吗，我用的suoi也是会有这个问题，不开分层窗口就不会

**Comment by nmgwddj** [comment]
@swiftlc 请查看此处对 alpha 通道的修补措施 https://github.com/netease-im/NIM_Duilib_Framework/blob/4933d1f2bc402119e26fa0d49f6edb27ad72471f/duilib/Core/Window.cpp#L1829，由于 GDI 绘制过程中会造成 alpha 为 0 的问题，导致会出现穿透的情况，所以参考这里代码你可以做两种修复措施。
 - 将窗口 shadowattached 属性设置为 true，这样会修补整个区域让鼠标不会出现穿透情况。
 - 手动设置窗口的 alphafixcorner 属性，让窗口在绘制过程中修复 RichEdit 所在的区域。
