### ISSUE TITLE
examples basic项目release版本窗口添加OnKeyDown结果有误

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#142]
![{IL96V%V26ABU7D85JLPB2I](https://user-images.githubusercontent.com/27080019/68652157-d3b55900-0563-11ea-870a-8c48144b19e0.png)

**Comment by nmgwddj** [comment]
反馈缺陷时，希望您能通过 issue 提供的模板尽量将问题的现象和预期填写清楚，以及如何能快速重现这个问题。
![image](https://user-images.githubusercontent.com/13995319/68818854-57388c80-06c1-11ea-976a-d784a8d2caff.png)
有些问题可能您所在的领域很容易就能看出，但是并不能让所有看到这个 issue 的人都能理解或清楚问题的现象和预期的结果是怎样的。
