### ISSUE TITLE
cef控件加载页面背景透明效果求支持

### ISSUE THREAD

**Issue by swiftlc** [netease-im/NIM_Duilib_Framework#144]
这里有个cef透明或者异形的资料:
https://sq.163yun.com/blog/article/214097332706783232

**Comment by nmgwddj** [comment]
1、设置窗口 attachedshadow 为 false（因为阴影图片中间区域是黑色的，确保阴影不会影响透明效果）
2、使用离屏渲染模式 https://github.com/netease-im/NIM_Duilib_Framework/blob/master/examples/cef/cef_form.h#L5 修改为 true
3、设置窗口最外层 Box 为一个透明度较高的颜色，如 `#10000000`
4、设置窗口透明度 `<CefControl name="cef_control" alpha="50"/>`

最终效果：

![2019-11-19_09-33-08](https://user-images.githubusercontent.com/13995319/69108567-03a6b400-0ab0-11ea-8d29-ad71f02a4341.png)

**Comment by swiftlc** [comment]
你好 这样做可以实现网页的整体透明，不过如何做到只针对网页背景做alpha完全透明呢

**Comment by nmgwddj** [comment]
@swiftlc 我们没有过这方面实战，不过可以给您提供一些思路。
 - CefSettings 中设置下背景为透明色 `CefColorSetARGB`
 - 窗口背景设置为透明
 - 网页 body 设置为透明，而元素保持原样
一些参考资料：https://magpcss.org/ceforum/viewtopic.php?f=6&t=10504
