### ISSUE TITLE
老Demo项目，怎么升级duilib库

### ISSUE THREAD

**Issue by zywj** [netease-im/NIM_Duilib_Framework#149]
```
NetEase IM Demo 
NetEase Education Demo
```

这几个项目，好像还在用比较老的duilib版本。
想知道如何能升级到最新的duilib。
我自己把duilib目录和duilib_d.lib拷到相应的目录，编译是报错的。
感觉这个升级不太好升，因为样式xml中属性，跟最新的duilib格式也不太一样了

**Comment by nmgwddj** [comment]
升级中改动较大的就是字体相关的属性，需要在 XML 中批量替换已经写好的字体标签、个别 UI 组件中修改设置字体的代码。
如果你着急使用，请先尝试自己替换编译逐步解决错误，无法自己解决的错误可以提供详细的错误内容一起来排查。
如果你不是很着急升级 Duilib，还请耐心等待我们后续的 Demo 更新，我们会逐步替换到 Demo 中的 Duilib 库。

**Comment by zywj** [comment]
感谢！
