### ISSUE TITLE
发现一个扩展屏大BUG

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#15]
## 问题现象
窗口在扩展屏中，点击放大，再点击最小化，再点击还原，发现窗口位置不对，窗口大小超出了屏幕范围
可以用demo中的，CEF、控件例子 做测试
## 重现步骤

1.把窗口放在第二屏中， 点击放大 再点击最小化
2.点击还原，就会出现这个问题

**Comment by shuilan0066** [comment]
测试发现：

当窗口是子进程时， 隐藏，再显示时，容易出现 有些按钮不显示现象
鼠标经过后，才显示出按钮，但这些按钮是有背景的，并不是起初的透明背景了

**Comment by nmgwddj** [comment]
@shuilan0066 根据您描述的复现步骤，没有能成功的复现这个问题。能否提供更详细的环境信息？或者您可以在有问题的场景中跟踪一下代码并修复这个问题，提交 PR 来帮我们修复这个问题。
![cef](https://user-images.githubusercontent.com/13995319/57591275-27b69500-7563-11e9-9289-48c1af08bb84.gif)

**Comment by shuilan0066** [comment]
在第二屏中 进行这样操作呢 我是在第二屏中 出现的 主屏没问题

**Comment by nmgwddj** [comment]
@shuilan0066 在上面录制的 GIF 中就是在第二个屏幕中操作，您可以在你自己的场景中跟踪以下代码，看一看是什么位置出现了异常，根据自己的环境来尝试修复问题。

**Comment by shuilan0066** [comment]
@nmgwddj   这个图片是怎么加上的呢  我也录了个动图 可以看看

**Comment by shuilan0066** [comment]
好了 上传了，原来不能上传10M以上的 ，得压缩下
![2019_5_13_9_59_41 (1)](https://user-images.githubusercontent.com/16250519/57592101-75cd9780-7567-11e9-950c-37f96191d560.gif)

**Comment by shuilan0066** [comment]
进一步测试发现 ，与第二屏 分辨率有关
我这里测试时，有这种规律：
第二屏分辨率的宽度  大于 第一屏分辨率宽度时，就会出现这种现象
                                    小于                                 ，则不会出现这种现象

建议可以调整下第二屏分辨率再试试

**Comment by shuilan0066** [comment]
刚才的 按钮状态不对，应该是没有考虑 软件贴屏处理？

**Comment by nmgwddj** [comment]
@shuilan0066 感谢提供的宝贵信息，我会尝试复现并处理这个问题。
而您说的状态按钮的问题，是需要业务层去处理的，这些是业务层的实现，需要你在窗口大小变化时判断是否是全屏，比如 IsZoomed，从而显示不同按钮状态，或者完全禁用窗口边缘附着后的放大和吸附效果，这类方法资料比较多，可搜索做参考。

**Comment by nmgwddj** [comment]
@shuilan0066 https://github.com/netease-im/NIM_Duilib_Framework/commit/9ee965d558672d20ed33c81cf24623cc534e038e 提交了一个修复补丁，您可以尝试在 development 分支下编译程序看是否能解决您的问题。
