### ISSUE TITLE
cef release不能加载网页，debug下能加载网页

### ISSUE THREAD

**Issue by tornodo** [netease-im/NIM_Duilib_Framework#155]
图片是release下的截图，debug下没有任何问题
![image](https://user-images.githubusercontent.com/4067864/70997788-bc442f80-2110-11ea-9be7-aec38851754c.png)

**Comment by tornodo** [comment]
而且release下点击鼠标右键也没有任何反应。debug下点击右键有菜单。

**Comment by nmgwddj** [comment]
development 分支最新代码 cef 项目编译为 release 没能重现您所描述的问题。请详细的描述该问题的重现步骤以帮助我们解决可能存在的问题。

**Comment by tornodo** [comment]
@nmgwddj 
命令行参数处理引起的，cef会再启动一个进程，我找不到参数就给退出这个进程了。这下难办了，😫

**Comment by nmgwddj** [comment]
可以将 CEF 的 render 进程与主进程分开两个执行程序，参考：https://github.com/netease-im/NIM_PC_Demo/tree/master/tool_kits/cef/cef_render

**Comment by chengjianxi** [comment]
把 
```
CefManager::GetInstance()->Initialize
```
放到main函数的最前面，处理命令行参数方法的前面就可以了
