### ISSUE TITLE
编译ui_components报错是什么原因？使用的VS2019

### ISSUE THREAD

**Issue by Chow1989** [netease-im/NIM_Duilib_Framework#156]
编译ui_components报错是什么原因？使用的VS2019
base和duilib编译成功，但编译ui_components报错！
![QQ截图20191222195258](https://user-images.githubusercontent.com/39211209/71321483-e45ad680-24f4-11ea-9c99-56374a822fe2.png)

**Comment by nmgwddj** [comment]
development 分支已经适配了 VS2019 的场景，请尝试使用此分支代码编译测试：https://github.com/netease-im/NIM_Duilib_Framework/blob/development/ui_components/modal_wnd/async_modal_runner.h

**Comment by Chow1989** [comment]
Thanks,Its  OK!
