### ISSUE TITLE
关于多窗口管理的问题

### ISSUE THREAD

**Issue by AsaminOgawa** [netease-im/NIM_Duilib_Framework#157]
我使用过原版的DUILIB，在NIM版本中消息循环和原版的差异就是消息循环被放进线程中去了。这样一来造成了一个问题，就是我不知道我的窗口退出码是多少了 因为目前我看的例子中 都没法获取窗口退出码，我的项目其实很简单，就是登录窗口 跳转到到主页面 两个窗口的管理问题，可是完全没有例子，我不知道如何使用。麻烦大大给个例子或者建议可以吗？ 真的文档太少 baidu google啥也搜不到呀

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/duilib/Core/Window.h#L136
Window 类中的 `Close()` 方法含有一个可选参数，这里可以标记退出原因，覆写 OnClose 后 wParam 可以获取到该退出原因的数据，根据自己需要做不同操作。

**Comment by AsaminOgawa** [comment]
如果我想用你们的窗口管理类来实现该如何做呢？
有没有nim_comp::WindowsManager::的详细例子？
我看参考了一下PCUIKIT  发现这样写不行：nim_comp::WindowsManager::SingletonShow<LoginWndFrame>(LoginWndFrame::kClassName);
说无法从wstring 转LPCTSTR 。

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/development/examples/controls/controls_form.cpp#L185

**Comment by AsaminOgawa** [comment]
补充，我需要修改window->Create(NULL, WindowType::kClassName.c_str(), WS_OVERLAPPEDWINDOW & ~WS_MAXIMIZEBOX, 0); 这样才能正常编译，但是我不确定是我的代码问题，还是我已开始使用就有问题。

**Comment by AsaminOgawa** [comment]
非常感谢您的回答，我想我知道该怎么做了
