### ISSUE TITLE
可以提供一个TabBox的例子吗？

### ISSUE THREAD

**Issue by AsaminOgawa** [netease-im/NIM_Duilib_Framework#158]
又来麻烦您了，baidu到一个例子 可是无法运行。
我想利用TabBox来做一个菜单页切换。可是没有例子 不知道如何下手

**Comment by AsaminOgawa** [comment]
补充一下，主要是布局的例子。代码到是很简单

**Comment by nmgwddj** [comment]
NIM PC Demo 包含了各类控件的丰富示例，覆盖了所有控件的使用方法，clone 该项目可以查看我们如何使用这些控件来构建应用。https://github.com/netease-im/NIM_PC_Demo
