### ISSUE TITLE
有没有办法使c++的字符串数据直接保存到js里呢?

### ISSUE THREAD

**Issue by lsaejn** [netease-im/NIM_Duilib_Framework#159]
程序加载时，我有一些数据需要发送到html的代码里，所以我调用NimCefWebInstance.call(...)，在回调函数里保存数据，但是我发现这些数据不是实时返回的。请问有没有做到呢？

**Comment by nmgwddj** [comment]
在 JS 与 C++ 交互时，中间涉及到进程间的通信，均是异步的。在做数据通信的时候就要考虑到数据可能是异步有时效性的。
不仅可以通过 call 方法中的回调，你也可以使用 NimCefWebInstance.register 注册一个全局函数来接受这些数据。

**Comment by lsaejn** [comment]
谢谢。我尝试了一下用了window binding，好像符合我的需求.....网页加载就可以直接用变量保存的数据了。
