### ISSUE TITLE
DPI能自适应图片资源吗

### ISSUE THREAD

**Issue by cn-ygf** [netease-im/NIM_Duilib_Framework#16]
类似 logo.png  logo@125.png  logo@150.png

**Comment by nmgwddj** [comment]
一个变通的方法是可以通过 DPIManager 判断当前屏幕缩放比例，从而加载不同的皮肤资源：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Utils/DPIManager.md

**Comment by cn-ygf** [comment]
> 一个变通的方法是可以通过 DPIManager 判断当前屏幕缩放比例，从而加载不同的皮肤资源：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Utils/DPIManager.md

我准备把别人写的的自适应加进去

**Comment by nmgwddj** [comment]
@cn-ygf 欢迎提交 PR 来帮我们完善这类功能。
