### ISSUE TITLE
使用默认阴影方案时，不能够往窗口里拖拽文件

### ISSUE THREAD

**Issue by lsaejn** [netease-im/NIM_Duilib_Framework#165]
亲爱的开发组，你们好！
在cef工程例子里，设置kEnableOffsetRender = true后，网页无法收到drop事件。
我尝试为窗口增加WS_EX_ACCEPTFILES，网页依然没有办法捕获这个drop事件(程序里能收到WM_DROPFILES消息)。请问这种需求应该怎么处理呢?

**Comment by nmgwddj** [comment]
你可能需要将控件接收到的消息转发到 CEF，参考：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/ui_components/cef_control/control/cef_control_ui.cpp#L172
另外如不是特殊需求，建议使用真窗口模式儿不是离屏渲染模式。

**Comment by lsaejn** [comment]
收到！！由于项目时间紧张，我们最后还是选择了离屏渲染模式和处理windows消息。因为我们需要调整边框大小，还有，cef窗口前置时，鼠标在窗口外需要收到键盘消息。离屏渲染模式可以来之即用。
