### ISSUE TITLE
tab_box修改selectedid无效

### ISSUE THREAD

**Issue by lsaejn** [netease-im/NIM_Duilib_Framework#166]
使用 option控件修改selectedid时，无效果
`<Event type="select" receiver="select_tab" applyattribute="selectedid=&quot;1&quot;"/>`
我注意到#62,看起来和这个改动有关。
`if( strName == _T("selectedid") ) SelectItem(_ttoi(strValue.c_str()));`

**Comment by nmgwddj** [comment]
您可以本地 revert 掉该提交查看问题是否得到解决，我们再与 @smallevilbeast  一起讨论如何处理这个问题。
另外如果您已经有更好的修复方案，也欢迎帮我们来修复这个问题。

**Comment by Zo213** [comment]
我这边也遇到了这个情况，#62对这一行代码的改动让selectedid属性失效了
![TabBox_BUG](https://user-images.githubusercontent.com/20905739/76379448-0bee6c00-638b-11ea-92af-c104866e43cf.PNG)
改回修改前的代码就恢复正常了。

**Comment by smallevilbeast** [comment]
两行同时加上就可以了，设置m_iCurSel是为了让初始化有作用，或把他放在SelectItem方法中

**Comment by smallevilbeast** [comment]
@Zo213  @lsaejn

**Comment by lsaejn** [comment]
了解，我也时这么做的。
