### ISSUE TITLE
高DPI字体显示模糊问题

### ISSUE THREAD

**Issue by l619534951** [netease-im/NIM_Duilib_Framework#17]
## 问题现象
高DPI，采用缩放时，字体显示模糊。（4K 250%缩放）。
![image](https://user-images.githubusercontent.com/17621099/57796559-10ea8b00-777b-11e9-95d6-b51852e55488.png)

## 重现步骤
1.在高分屏上，设置缩放，运行项目中的例子。

PS：因为我只是喜欢做自己一些小软件的开发，不是专门做这块的，了解其实并不是很多，昨晚通过duilib找到这里，克隆之后运行起来，发现挺好看的，而且文档也好，就是高DPI字体显示有问题，可以给个解决方法吗？麻烦说得简单一点，太专业我可能不了解，谢谢大佬。

**Comment by nmgwddj** [comment]
@l619534951 https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/GLOBAL.md#Startup
参考 Startup 方法第 3 个参数，开启 DPI 适配，设置为 true 的情况下会根据情况做适配，设置为 false 操作系统会对应用做自动暴力适配（就是你看到的现象）。

**Comment by l619534951** [comment]
@nmgwddj 谢谢大佬，晚上回去就自己试试。
