### ISSUE TITLE
VS2017PRO+WIN10+X64 how to build？？

### ISSUE THREAD

**Issue by jcyhcs** [netease-im/NIM_Duilib_Framework#170]
请问如何用这样的配置编译？

**Comment by nmgwddj** [comment]
使用 development 分支已经支持 VS2017 32 位及 64 位的编译，如果编译过程中遇到什么问题，可以将错误内容提交给我们。

**Comment by jcyhcs** [comment]
![image](https://user-images.githubusercontent.com/34532224/76624448-4a914b80-6570-11ea-8b20-e49b10138cda.png)
请看

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76624674-b4115a00-6570-11ea-9cec-c0c0bc6d83a7.png)
错误如图

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76626336-f4260c00-6573-11ea-8414-d8fda6b93646.png)
编译ui_components出错

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76626476-2c2d4f00-6574-11ea-90ba-54968d336568.png)

**Comment by nmgwddj** [comment]
这个提示的意思是你没有安装 v120 的平台工具集（对应VS2013），你使用 VS2017 应该修改平台工具集为 v141，在第一次打开项目工程时会有提示你是否升级，也可以通过多选项目右键属性，修改平台工具集。

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76716481-4da45b80-676b-11ea-93f1-3a44517c93f8.png)
我修改了平台工具集，但是在编译ui_componets依然报错，如图

**Comment by jcyhcs** [comment]
我修改了平台工具集，但是在编译ui_components模块依然报错，如图
![无标题](https://user-images.githubusercontent.com/34532224/76716571-b25fb600-676b-11ea-9566-36ad39f6f588.png)

**Comment by jcyhcs** [comment]
我替换 了平台工具集，但是在编译ui_components模块依然出错，目前只有这个模块出错，其他模块可以编译通过
![无标题](https://user-images.githubusercontent.com/34532224/76716787-75e08a00-676c-11ea-9cfa-058a2e8e488b.png)

**Comment by jcyhcs** [comment]
我替换 了平台工具集，但是在编译ui_components模块依然出错，目前只有这个模块出错，其他模块可以编译通过
![无标题](https://user-images.githubusercontent.com/34532224/76716815-885ac380-676c-11ea-9a41-ff8af19ccf81.png)

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76716897-c526ba80-676c-11ea-9d5e-4e78272637c3.png)

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76716946-f1dad200-676c-11ea-995a-c3a81f20909d.jpg)

**Comment by jcyhcs** [comment]
![a](https://user-images.githubusercontent.com/34532224/76717168-df14cd00-676d-11ea-96c8-f49e9b4afde7.jpg)

**Comment by jcyhcs** [comment]
![a](https://user-images.githubusercontent.com/34532224/76717204-fb186e80-676d-11ea-9e5b-ad5cc2d048e1.jpg)

**Comment by jcyhcs** [comment]
![a](https://user-images.githubusercontent.com/34532224/76717362-0f5c6b80-676e-11ea-8a1c-3a8dc3eeec87.jpg)

**Comment by jcyhcs** [comment]
我已经切换平台工具集，目前只是这个ui_components模块编译错误

**Comment by jcyhcs** [comment]
![无标题](https://user-images.githubusercontent.com/34532224/76717457-62ceb980-676e-11ea-9e02-4f2239457b76.png)

**Comment by nmgwddj** [comment]
拉取 development 分支的最新代码，已经对无法编译的代码做了修正。https://github.com/netease-im/NIM_Duilib_Framework/commit/3833e427ff25a73e94982b2fcba144e3d85ff142
