### ISSUE TITLE
development版本运行examples中的virtualbox崩溃

### ISSUE THREAD

**Issue by jcyhcs** [netease-im/NIM_Duilib_Framework#174]
环境：vs2017pro win10 debug x64
![1](https://user-images.githubusercontent.com/34532224/76818150-caa10500-683f-11ea-8093-c4a2a7331e6a.png)
![2](https://user-images.githubusercontent.com/34532224/76818153-ce348c00-683f-11ea-8366-dd5a22dbcde8.png)

**Comment by nmgwddj** [comment]
已经在提交：https://github.com/netease-im/NIM_Duilib_Framework/commit/fff03ed4dedc301058c693756594da7f0d3ffa39 中修复，请尝试拉取最新代码测试。
