### ISSUE TITLE
development版本编译examples中的multi_browser项目失败

### ISSUE THREAD

**Issue by jcyhcs** [netease-im/NIM_Duilib_Framework#175]
![无标题](https://user-images.githubusercontent.com/34532224/76941478-15517880-6937-11ea-8bef-dbe33f5d6856.png)
vs2017 x64 debug环境

**Comment by nmgwddj** [comment]
@jcyhcs https://github.com/netease-im/NIM_Duilib_Framework/commit/ad2635f0e704e134f35fb91529a850efe4e24621 提交已经修复该问题，请尝试拉取最新提交。

**Comment by cdslily** [comment]
debug可以编译通过，release依然编译不通过。

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2065	“LC_ALL”: 未声明的标识符	multi_browser	D:\workspace\nim_duilib\examples\multi_browser\main.cpp	22
