### ISSUE TITLE
使用cef_native_control时 弹出Exception

### ISSUE THREAD

**Issue by harry12800** [netease-im/NIM_Duilib_Framework#176]
你好！
异常如下：
```
File:
cef_native_control.cpp Line:33
 Expression: (((DWORD)GetWindowLongW(m_pWindow->GetHWNDO,
(-20)&0x00080000)==0&&l无法在分层窗口内使用本控件
```
确实是TabBox里面使用的。
我的XML
```
<Window>
  <VBox bkcolor="bk_wnd_darkcolor">
    
	<CefNativeControl name="cef_native_control" margin="4,4,4,4" bkcolor="bk_wnd_lightcolor" bordersize="1" bordercolor="darkcolor"/>
  </VBox>
</Window>
```
请问，如果不能再TabBox里面使用怎么实现这个场景? 使用cef .

在NIM_PC_Demo工程，nim_demo中看到“Cef测试”插件工具Tab页，右侧是CefNativeForm，和MainForm什么关系？
和CefTestPlugin什么关系？
CefTestPlugin : public nim_comp::MainPluginBase<nim_comp::IMainPlugin::PluginType::PluginType_Main>
感谢解惑！！
CefNativeForm 和 MainForm都继承自 nim_comp::WindowEx
是怎么把CefNativeForm 绘制成MainForm的一部分的 ？

**Comment by harry12800** [comment]
CefNativeForm 和 MainForm都继承自 nim_comp::WindowEx
是怎么把CefNativeForm 绘制成MainForm的一部分的 ？

**Comment by nmgwddj** [comment]
这与您是否在 TabBox 里面使用这个控件没有关系，在提示中已经明确标明：无法在分层窗口内使用本控件。CefNativeControl 是真窗口模式，无法在带有 WS_EX_LAYERED 属性的窗口中使用。请参考 Cef 示例代码：https://github.com/netease-im/NIM_Duilib_Framework/blob/development/examples/cef/cef_form.h#L5

为方便其他人搜索，NIM_PC_Demo 的问题烦请在 Demo 项目中发起 Issue，您的问题也可能会有其他人遇到。
