### ISSUE TITLE
xml支持跨窗口发送消息吗？

### ISSUE THREAD

**Issue by lsaejn** [netease-im/NIM_Duilib_Framework#178]
在官方例子control中，弹出的菜单(settings_menu.xml)里，可不可以直接定义event，以达到修改主窗口的控件属性的效果？
例如，在settings_menu.xml里，我加入点击事件的event:

><MenuElement class="menu_element" name="second" width="180">
      <Button width="auto" height="auto" bkimage="menu_proxy.png" valign="center" mouse="false">
        <Event type="buttondown" receiver="a_control_in_mainwindow" applyattribute="visible=&quot;false&quot;"/>
      </Button>
      <Label class="menu_text" text="Proxy settings" margin="30,0,0,0"/>
</MenuElement>

但看起来没有效果，不知道大家的解决方案是？

**Comment by nmgwddj** [comment]
我们一般的做法是响应 menu item 的事件，可以通过 WindowManager 的 GetWindow 方法来查找主窗口调用指定的共有成员函数实现需求。

**Comment by lsaejn** [comment]
那么看起来只有代码里处理事件了。谢谢百忙之中解答我的疑惑！！！
