### ISSUE TITLE
离屏渲染模式输入法位置不正确问题

### ISSUE THREAD

**Issue by Brucexiaobi** [netease-im/NIM_Duilib_Framework#18]
## 问题现象
使用离屏渲染模式，WEB页面的编辑框输入时候输入法的位置不正确，无法显示在WEB页面内
## 重现步骤

1.simples的例子cef修改`const bool kEnableOffsetRender = true;`
2.WEB页面的编辑框输入中文可以看到输入法位置不能显示在整个CEF区域

真窗口模式下的输入法位置
![cef-真窗口](https://user-images.githubusercontent.com/12406128/57839610-9dd42980-77f9-11e9-8403-b6e7e49c3879.png)

离屏渲染模式下的输入法位置

![cef-离屏模式](https://user-images.githubusercontent.com/12406128/57839619-a0368380-77f9-11e9-83e8-95ea012a9702.png)

**Comment by nmgwddj** [comment]
@Brucexiaobi 这个问题的确存在，我们还没有找到更好的方法来解决这个问题。在您的场景下如非必要，我们还是建议使用真窗口模式而非离屏渲染模式。

**Comment by Brucexiaobi** [comment]
谢谢

**Comment by silent-feng** [comment]
我们自己解决这个问题，有思路可以提示一下吗
