### ISSUE TITLE
有没有一个类似DuiDesigner.exe的设计工具

### ISSUE THREAD

**Issue by lixinhan2019** [netease-im/NIM_Duilib_Framework#183]
请问大家都是直接写xml文件吗？有没有类似于DuiDesigner.exe的设计器自动生成xml文件的？

**Comment by nmgwddj** [comment]
建议还是手工写 XML，类似 DuiDesigner 的视觉设计工具偏重视觉和产品设计，同类 UI 框架中最好的实现也避免不了产生冗余代码。你可以使用 Visual Studio IDE 作为编辑基础工具，会自动进行缩进对齐、检查语法。也可以使用 Visual Studio Code、Notepad++ 来做 XML 代码编辑。
