### ISSUE TITLE
图片文字渲染锯齿感严重

### ISSUE THREAD

**Issue by guxing** [netease-im/NIM_Duilib_Framework#186]
图片（control）只要重新设置width和height，带有圆角的图片边缘有严重锯齿感

设置DPI也没用，文字、GDI绘制也是，请问有没有解决方案，我看基本上没人反馈这个问题，大家都是怎么做界面适配的，现在感觉这种情况根本无法使用了

**Comment by smallevilbeast** [comment]
图片可以指定corner，控制圆角不被拉伸, 了解下九宫图， 如：
normalimage="file='../public/button/btn_global_green_80x30_normal.png' corner='5,5,5,5'"

**Comment by guxing** [comment]
> 图片可以指定corner，控制圆角不被拉伸, 了解下九宫图， 如：
> normalimage="file='../public/button/btn_global_green_80x30_normal.png' corner='5,5,5,5'"

谢谢你的回答，九宫格是没问题的，我可以指定圆角部分不拉伸，但是产品界面上还有大量图片素材都不是九宫格的，这些图片有些是有圆角的，一旦重新设置非原尺寸的宽高，锯齿非常严重，有其他适配方案或者底层处理方式呢？

**Comment by smallevilbeast** [comment]
> > 图片可以指定corner，控制圆角不被拉伸, 了解下九宫图， 如：
> > normalimage="file='../public/button/btn_global_green_80x30_normal.png' corner='5,5,5,5'"
> 
> 谢谢你的回答，九宫格是没问题的，我可以指定圆角部分不拉伸，但是产品界面上还有大量图片素材都不是九宫格的，这些图片有些是有圆角的，一旦重新设置非原尺寸的宽高，锯齿非常严重，有其他适配方案或者底层处理方式呢？

超过原尺寸肯定会模糊的，可以把原素材做大尺寸

**Comment by guxing** [comment]
> > > 图片可以指定corner，控制圆角不被拉伸, 了解下九宫图， 如：
> > > normalimage="file='../public/button/btn_global_green_80x30_normal.png' corner='5,5,5,5'"
> > 
> > 
> > 谢谢你的回答，九宫格是没问题的，我可以指定圆角部分不拉伸，但是产品界面上还有大量图片素材都不是九宫格的，这些图片有些是有圆角的，一旦重新设置非原尺寸的宽高，锯齿非常严重，有其他适配方案或者底层处理方式呢？
> 
> 超过原尺寸肯定会模糊的，可以把原素材做大尺寸

是这样，没有模糊，我们就是用的1080p来切的素材，在低分辨率下图片肯定会被缩放的（通过设置图片的width和height，当然设置的都比原素材分辨率要小），但是有圆角的图片锯齿感很强烈，用不用DPI都没有用，只要圆角图片缩小尺寸，马上锯齿就出来

**Comment by guxing** [comment]
图片控件只要重新设置宽高、或者外边距平铺父控件，或者DPI适配，只要改变原图片大小，带有圆角的图片都会有锯齿

**Comment by guxing** [comment]
我看RenderContext_GdiPlus:DrawImage方法 是通过gdi+来绘制图片的，gdi应该是支持平滑绘制的，我看SetStretchBltMode(m_hDC,HALFTONE)确实是线性插值去做平滑处理的，但是这个函数里面还有GDI的内容，是否可以调整GDI+线性插值算法优化呢

**Comment by guxing** [comment]
已经解决

**Comment by lsaejn** [comment]
> 已经解决

怎么解决的倒是说一下啊
