### ISSUE TITLE
示例程序在x64编译项下报错

### ISSUE THREAD

**Issue by jison699** [netease-im/NIM_Duilib_Framework#187]
## 问题现象
1. 选择 x64编译项，运行cef示例程序报错：Unhandled exception at 0x00007FFB242DA859 (KernelBase.dll) in cef64_d.exe: 0xC06D007E: Module not found (parameters: 0x0000006CEEEFEBF0).

![image](https://user-images.githubusercontent.com/15274702/78775287-8a5d1e80-79c8-11ea-8fbb-380ebd0c92c2.png)
2. 选择x64编译项，编译multi_browser示例程序报错
![image](https://user-images.githubusercontent.com/15274702/78775490-e0ca5d00-79c8-11ea-91ad-b9a4cb1e1818.png)

**Comment by nmgwddj** [comment]
这个问题原因是 cef 64 位的示例程序编译后使用了 32 位的 cef 依赖文件，增加了一个条件编译来处理不同平台下的 cef 依赖目录。请参考：https://github.com/netease-im/NIM_Duilib_Framework/commit/3ade303da4d39eae6dab697e9825f4d6a6b5d36a
