### ISSUE TITLE
使用NIM_Duilib_Framework无法包含windows.h这个头文件

### ISSUE THREAD

**Issue by findream** [netease-im/NIM_Duilib_Framework#189]
你好，我在使用NIM_Duilib_Framework创建一个demo的时候，想通过按钮去调用GetOpenFileName去浏览文件，所以我想在预编译头中填入#include <Windows.h>，但是当我编译的时候发现无法编译，经过排查发现可能和WinSock这个头文件冲突，希望给个解决方案

**Comment by nmgwddj** [comment]
可以调整一下 winsock 和 windows 头文件的包含顺序。给出具体错误提示，这样我们更方便帮助你分析问题。

**Comment by findream** [comment]
谢谢您的回复，问题已解决，原因是winsock和winsock2发生冲突




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 中午12:08
收件人:&nbsp;"netease-im/NIM_Duilib_Framework"<NIM_Duilib_Framework@noreply.github.com&gt;;
抄送:&nbsp;"HiJack"<1434905079@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [netease-im/NIM_Duilib_Framework] 使用NIM_Duilib_Framework无法包含windows.h这个头文件 (#189)





 
可以调整一下 winsock 和 windows 头文件的包含顺序。给出具体错误提示，这样我们更方便帮助你分析问题。
