### ISSUE TITLE
VS2017编译不过

### ISSUE THREAD

**Issue by x64bugreport** [netease-im/NIM_Duilib_Framework#2]
可否提供下高版本编译方法，或源码修改方案？

**Comment by nmgwddj** [comment]
升级到 VS2017（>MSVC++ 14.1  _MSC_VER == 1910） 一些模板和标准库的使用方法会有些不同，单独改动量稍大，在后期计划中会尝试修复这个问题。
现在建议最高升级到 VS2015（MSVC++ 14.0  _MSC_VER == 1900）来进行开发，如果你项目中有必须使用 VS2017 以上静态库，可以尝试自己修改代码，欢迎提交 PR 来帮我们完善。

**Comment by IULOVE** [comment]
我是这样编译的，base工程把警告视为错误关闭, 其他把 属性/c/c++/语言 中的符合模式关闭.
还有个错误是ui_components工程的，把AsyncModalRunner(Delegate *delegate); virtual ~AsyncModalRunner(); 放到public 。。

**Comment by nmgwddj** [comment]
@x64bugreport 最新 master 分支已经支持使用 VS2017 直接编译，无需修改代码和参数。
