### ISSUE TITLE
是否支持64位

### ISSUE THREAD

**Issue by thanthesun** [netease-im/NIM_Duilib_Framework#20]
- vs2017版最新编译
我使用64位编译会报一大堆错误
而且不论32位或64位都看到有很多强制转换类型 还有很多其它警告.在64位可能会出错。

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/commit/019e34cac1acc710410cfd04a87f7480b0cd3484 已经修复在 MSVC 15.9 以上版本无法编译成功问题。

一些警告内容要逐步替换，不会影响绝对稳定性。您也可以做适当修改，欢迎提交 PR 来帮我们保证程序更加稳健。
