### ISSUE TITLE
virtualbox用例中 固定列数 选择列数为1时  无法正常下拉显示全部数据

### ISSUE THREAD

**Issue by liubin123456** [netease-im/NIM_Duilib_Framework#205]

**Comment by liubin123456** [comment]
@smallevilbeast @quanzhuo @surebeli @nmgwddj

**Comment by dilibili** [comment]
同样遇到这个问题
选列一
滚动条  和 下拉 都无法显示完整数据

**Comment by smallevilbeast** [comment]
一列的话，先用core中的VirtualListBox

**Comment by liubin123456** [comment]
将VirtualTileBox.cpp 的109行 改为return m_szItem.cy * rows  + childMarginTotal; 可以解决无法全部显示BUG

**Comment by liubin123456** [comment]
@dilibili
