### ISSUE TITLE
鼠标进入 鼠标离开消息

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#206]
如果这个控件的子控件 mouse属性都是false时，
		pVideoBox_->AttachMouseEnter([this](ui::EventArgs* param){

			scale_menu_box_->SetVisible(true);
			return true;
		});

		pVideoBox_->AttachMouseLeave([this](ui::EventArgs* param){

			scale_menu_box_->SetVisible(true);
			return true;
		});

要实现的，鼠标进入就显示某子控件  鼠标离开就隐藏某子控件  功能可以实现
但如果子控件mouse为true的 时候， 子控件截取了消息， 导致如上功能无法实现

我现在使用的 绘制时，通过判断鼠标位置 来动态隐藏与显示
还有更好的方式么

**Comment by smallevilbeast** [comment]
AttachBubbledEvent(ui::kEventMouseEnter
AttachBubbledEvent(ui::kEventMouseLeave

使用bubbledEvent

**Comment by shuilan0066** [comment]
恩恩 测试成功了  
这个AttachBubbledEvent   是什么意思   这样虽然有子控件，但是也能收到鼠标进入消息

是不是，这个的意思是  控件收到了什么消息 不管有没有被子控件截取
