### ISSUE TITLE
Control::DrawImage中imageCache为empty引发异常

### ISSUE THREAD

**Issue by eternalmr** [netease-im/NIM_Duilib_Framework#208]
### 应用背景：
server上根据client的不同状态（空闲、忙碌、故障等）设置client相应的背景图片。

### 问题描述
Control::DrawImage函数中1255行异常：rcNewSource.right = duiImage.imageCache->nX，提示std::shared_ptr<ui::ImageInfo>::operator->**<ui::ImageInfo,0>**(...) 返回 nullptr。此时imageCache显示为empty。
我觉得这个问题很奇怪，因为在DrawImage开始的时候已经对imageCache进行了初始化，并进行了判断之后，才运行到1255行的。
GetImage(duiImage);
if (!duiImage.imageCache) {
	ASSERT(FALSE);
	duiImage.imageAttribute.Init();
	return false;
}
imageCache是一个std::shared_ptr<ImageInfo>的变量，可能在过程中意外的释放了imageCache。由于在server运行的过程中会随机发生这个异常，所以不太确定如何解决这个问题。

### 异常截图：
![image](https://user-images.githubusercontent.com/42640955/81784287-3a292d00-952f-11ea-9034-1483374d1b13.png)
![image](https://user-images.githubusercontent.com/42640955/81784410-647aea80-952f-11ea-8d85-b7accdd36339.png)
![image](https://user-images.githubusercontent.com/42640955/81785662-21217b80-9531-11ea-8f2c-78faee709168.png)

**Comment by nmgwddj** [comment]
这个问题很有可能是 GDI 句柄泄露导致，在出现问题时查看一下当前进程所占用的句柄使用数量，是否有未释放句柄导致系统空间的资源不足。

**Comment by eternalmr** [comment]
> 这个问题很有可能是 GDI 句柄泄露导致，在出现问题时查看一下当前进程所占用的句柄使用数量，是否有未释放句柄导致系统空间的资源不足。

谢谢您的回复，虽然我当时没有精确定位到问题，但是由于当时使用了多线程，所有导致了一些不可预知的问题的发生。当把所有界面更新函数都放入一个线程后，上述问题就没有发生过了
