### ISSUE TITLE
能否提供一个带io message 的例子

### ISSUE THREAD

**Issue by masor** [netease-im/NIM_Duilib_Framework#21]
如题

**Comment by nmgwddj** [comment]
@masor 能否描述一下您更详细的需求？比如什么场景或者什么案例？我们也好提供更丰富的 demo 帮助你来实现业务代码。

**Comment by masor** [comment]
@nmgwddj 场景大致这样：1、多客户端连接服务端；2、服务端维护客户端连接；3、服务端实现实时查看客户端连接状态及管理客户端。UI线程实现查看及管理等功能，IO线程实现通信。

**Comment by nmgwddj** [comment]
@masor UI 框架中使用 Google base 的功能有限，对于 Google base 基础库中很多内容我也没有相关涉猎，盲目给出示例代码没有实践怕给您造成误导。这个更建议您看一些 Chrome 的实现代码来帮助你学习相关内容。
