### ISSUE TITLE
嵌入CEF时 点击原生界面按钮 CEF焦点会转移 这个怎么破

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#218]
比如： CEF有滚动条
            点击原生窗口按钮时，CEF焦点失效  此时鼠标按中健 滚动条不滑动

**Comment by lsaejn** [comment]
cef_control_->SetFocus();

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，使用方法问题我们开通了 Github discussions 用以交流使用方式：https://github.com/netease-im/NIM_Duilib_Framework/discussions
