### ISSUE TITLE
支持窗口分割

### ISSUE THREAD

**Issue by wangxiaokun** [netease-im/NIM_Duilib_Framework#219]
您好，我看原版的Duilib是支持窗口分栏的，比如通过sepwidth属性和sepimm设置，咱们这个是给去掉了，还是没有做呢？如果是去掉的，请问为什么去掉这个特性，谢谢。

**Comment by nmgwddj** [comment]
该功能在 NIM Duilib 中的确已经删除，您的问题将作为需求，我们会根据情况评估是否增加新能力。

**Comment by wangxiaokun** [comment]
谢谢
