### ISSUE TITLE
cef退出导致崩溃

### ISSUE THREAD

**Issue by Gocpy** [netease-im/NIM_Duilib_Framework#22]
## 问题现象
Samples里面的cef demo与qq拼音输入法冲突。退出导致崩溃
## 重现步骤

1.切换当前输入法为qq拼音输入法。退出导致崩溃，
2.切换为其他输入法则退出正常。

**Comment by nmgwddj** [comment]
@Gocpy 我们遇到过一些在搜狗输入法环境卡主、崩溃的情况，QQ拼音的很少有蹦到。能否提供更详细的崩溃栈信息，看一下具体崩溃在什么位置，是否可以找到对应的 pdb 查找到崩溃的原因？现在除 CEF 是编译后的文件外，其他都是包含源代码的，您可以尝试调试一下看看具体崩溃位置我们来一起查找解决方案。

您也可以到 QQ 拼音的交流社区如 QQ拼音贴吧、QQ拼音微博及公众号反馈问题。https://tieba.baidu.com/f?kw=qq%E8%BE%93%E5%85%A5%E6%B3%95&ie=utf-8

**Comment by Gocpy** [comment]
这个地方调试不了，提示帧不在模块中。堆栈信息也看不到。

**Comment by nmgwddj** [comment]
@Gocpy 您可以尝试更新一下 QQ 拼音输入法的版本，我当前使用 QQ 拼音 6.1.5306 版本，得到的是正常的退出路径。如果依然存在问题，可以在 QQ 拼音的社区中反馈一下相关问题。

![2019-05-22_09-46-14](https://user-images.githubusercontent.com/13995319/58141623-976d0400-7c76-11e9-9f98-cca427d42a09.png)

**Comment by Gocpy** [comment]
重装了最新的qq拼音输入法后正常了。
