### ISSUE TITLE
如何设置弹出窗口的opener

### ISSUE THREAD

**Issue by djzbj** [netease-im/NIM_Duilib_Framework#220]
对于window.open打开链接，使用onlinkclick后，打开新cef窗口，如何在新的cef控件里面设置opener为当前cef控件，方便js回传参数？

**Comment by nmgwddj** [comment]
您指的回传参数这个路径具体是怎样的？能否更清晰的描述一下这个过程，再综合判断一下是不是有更好的方案来满足这个需求。

**Comment by xtsdjz** [comment]
本来页面是是网站的一部分，页面有有combox，combox右侧有添加新选项按钮+，点击+，弹出窗口添加新选项，关闭弹出窗口后，自动设置combox为新选项的值，这个设置过程是在弹出窗口提交时返回了js代码，js使用opener调用父窗口js函数设置的这个新的选项。

**Comment by xtsdjz** [comment]
另外这个cef处理的好像有点问题，页面加载有时很慢，比如domo哪个，加载的本地页面有时半天不出来

**Comment by xtsdjz** [comment]
另外这个cef处理的好像有点问题，页面加载有时很慢，比如 多标签浏览器 哪个demo哪个，加载的本地页面有时半天不出来

**Comment by djzbj** [comment]
通过以下修改解决了：
1.修改OnBeforePopup 返回false，使用默认弹窗，但是自动了libcef版本太老，弹窗程序崩溃
2.同时升级libcef到 76.1.13 可以默认弹窗了

**Comment by djzbj** [comment]
通过以下修改解决了：
1.修改OnBeforePopup 返回false，使用默认弹窗，但是自带的libcef版本太老，弹窗导致程序崩溃
2.同时升级libcef到 76.1.13 可以默认弹窗了

**Comment by djzbj** [comment]
牺牲了对xp的支持
