### ISSUE TITLE
richedit 在弹出的输入对话框中，文字没有颜色，不可见

### ISSUE THREAD

**Issue by xtsdjz** [netease-im/NIM_Duilib_Framework#221]
<?xml version="1.0" encoding="UTF-8"?>
<Window size="300,90" caption="0,0,0,35" sizebox="1,1,1,1" shadowattached="false" >

  <VBox bkcolor="bk_wnd_lightcolor">
    <HBox width="stretch" height="35" bkcolor="bk_main_wnd_title">
      <Label class="font_title" name="title" valign="center" margin="8" text="请输入" />
      <Control />
      <Button class="btn_wnd_close" name="closebtn" margin="4,6,8,0"/>
    </HBox>
    
    <Control class="splitline_hor_level1"/>
    
    <RichEdit class="simple prompt input" name="text_input" width="stretch" height="50" padding="8,8,8,8" font="system_18" prompttext="请输入" />
    <Button class="btn_global_blue_80x30" name="btn_ok" width="50" height="30" text="确定" halign="center"/>
  </VBox>

</Window>

**Comment by djzbj** [comment]
主要现象是设置字体颜色和光标颜色不生效，无论如何设置字体颜色和光标颜色都是白色，如何修正这边bug

**Comment by nmgwddj** [comment]
参考：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/bin/resources/themes/default/controls/controls.xml#L69
尝试设置 RichEdit 背景色为固定颜色或使用非 Layered 特性窗口。

**Comment by djzbj** [comment]
> 参考：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/bin/resources/themes/default/controls/controls.xml#L69
> 尝试设置 RichEdit 背景色为固定颜色或使用非 Layered 特性窗口。

谢谢，非layered窗口可以了。
