### ISSUE TITLE
如何控制tab键的切换顺序？

### ISSUE THREAD

**Issue by xtsdjz** [netease-im/NIM_Duilib_Framework#227]
demo中的登录窗口输入用户名，需要按tab两次才能切换到密码，如果修改为一次？

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/commit/bef5c9ac8e57b9660b4e6d09758e1836fd6ee4e2
参考此提交。

**Comment by xtsdjz** [comment]
该文说的tabbox切换，我的意思按键盘tab键，如何控制在richedit和button直接切换顺序。这个如果可以在xml进行配制就方便多了

**Comment by nmgwddj** [comment]
控件是否响应 TAB 事件在上面提供的提交中有一些说明，您可以强制 RichEdit 将焦点移动到其他控件上。另外 Issue 作为问题跟踪和新功能开发跟踪，使用方法问题我们开通了 Github discussions 用以交流使用方式：https://github.com/netease-im/NIM_Duilib_Framework/discussions
