### ISSUE TITLE
是否能提供一个 FrameworkThread 的demo？

### ISSUE THREAD

**Issue by xtsdjz** [netease-im/NIM_Duilib_Framework#228]
是否能提供一个 FrameworkThread 的demo？如何执行 定时任务和动态添加任务，谢谢

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/examples/controls/controls_form.cpp#L116
PostRepeatedTask 可以满足你的需求。

**Comment by xtsdjz** [comment]
谢谢
