### ISSUE TITLE
有没有办法 将客户端的视频数据比如yuv数据 传送到CEF中显示呢

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#23]
有没有办法 将客户端的视频数据比如yuv数据 传送到CEF中显示呢

客户端采集摄像头，获得摄像头数据，这些数据想在CEF中显示，因为逻辑都在浏览器中处理

有这种方法么

**Comment by nmgwddj** [comment]
可接入相关的 Web SDK 在 CEF 内部实现类似功能，从 Native 传递数据涉及到从渲染进程到浏览器进程传递数据，数据的多次拷贝存在性能问题。所以使用 Web 直接接受渲染数据是最好的选择。

**Comment by qsocjdjwnzn** [comment]
你好 这个最后用什么办法解决呢
