### ISSUE TITLE
建议增加模态对话框功能

### ISSUE THREAD

**Issue by yzxfz** [netease-im/NIM_Duilib_Framework#231]
原duilib有ShowModal功能可以实现模态对话框，现在NIM_Duilib里没有这个功能，这样就无法实现模态对话框的效果了

**Comment by yzxfz** [comment]
ShowModalFake这个也无法实现真正的模态对话框，主窗口后续代码仍然会执行无法进行阻塞

**Comment by lsaejn** [comment]
可以写个windows消息循环。。。

**Comment by yzxfz** [comment]
> 可以写个windows消息循环。。。

请问有代码可以参考吗？我参考duilib里的ShowModal用消息循环做，但会有问题

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
