### ISSUE TITLE
怎么调整带阴影窗口的rounddercorder

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#234]
比如 直接 shadowattached="true" roundcorner="38,38"时， 窗口的圆角没发生变化

而且shadowattached="true" 后， Box里设置的透明色都呈现了黑色

![image](https://user-images.githubusercontent.com/16250519/88530458-fd4fdb00-d033-11ea-83d1-2f759b4d0775.png)

如何使得窗口既有阴影效果 又可调整窗口圆角呢

使用了以下样式操作
![image](https://user-images.githubusercontent.com/16250519/88530776-76e7c900-d034-11ea-93ae-415f72ef6bb1.png)

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
