### ISSUE TITLE
请问: 有跨平台计划么？

### ISSUE THREAD

**Issue by ddao** [netease-im/NIM_Duilib_Framework#236]
该项目是否有跨平台计划, 支持Linux, Mac OSX等非Windows平台？

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
