### ISSUE TITLE
共享桌面时 如何让桌面忽略掉本客户端交互的对话框呢

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#239]
我看腾讯会议 实现了这个功能
抓取的桌面  但是不包含腾讯会议客户端上的对话框等界面

他们应该也是duilib做的界面 ，
但是不明白 为什么他们抓取桌面时  
虽然对话框仍然显示着  
但却可以忽略掉这些窗口，从而得到纯粹的桌面

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
