### ISSUE TITLE
发现一个BUG

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#24]
## 问题现象
CEF 离屏模式下， 网址输入框 是半透明的 ，将shadowattached="false" 改为true 时 才正确
## 重现步骤

1. CEF 离屏模式
2. CEF示例 网址输入框 输入文字时，色彩根据背景色改变 ，好像加载新网页时，下面的网页部分也完全透明，加载成功后，才正常显示

**Comment by nmgwddj** [comment]
默认使用真窗口模式，cef 示例 .h 头文件 class 声明位置有说明。
