### ISSUE TITLE
能否把libcef2623的 nim_cef.dll工程放出来

### ISSUE THREAD

**Issue by Elegent** [netease-im/NIM_Duilib_Framework#242]

**Comment by Elegent** [comment]
我需要重新编译 libcef2623 的 nim_cef.lib 及  nim_cef.dll、搜索完全网都没找着、弄了2天裁剪也没有效果编译失败。

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
