### ISSUE TITLE
NIM_Duilib_Framework/examples/ 中的一个例子不可下载

### ISSUE THREAD

**Issue by JKwarn** [netease-im/NIM_Duilib_Framework#243]
## 问题现象

标题所述位置中的，NetEase Interact Live Demo，例子不可下载

点击后弹出页面显示

略
对象“package/1542889389/NIM_InteractLive_PC_Demo_v2.9.0.zip”不存在，请指定正确的对象
略

**Comment by nmgwddj** [comment]
可访问云信官网下载最新的工程代码：https://yunxin.163.com/im-demo
