### ISSUE TITLE
简介中的 Google base 基础类库（线程、内存、闭包等）中的线程该如何利用呢？

### ISSUE THREAD

**Issue by JKwarn** [netease-im/NIM_Duilib_Framework#246]
examples中也没有示例呀。

**Comment by nmgwddj** [comment]
所有示例中主线程均使用 base 中的线程模型，controls 示例代码中有演示如何投递一个任务包到线程队列，请参考：
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/examples/controls/controls_form.cpp#L87
