### ISSUE TITLE
如何使用原生的标题栏和菜单栏

### ISSUE THREAD

**Issue by ClearSeve** [netease-im/NIM_Duilib_Framework#247]
我想用WTL和duilib混合开发, 但是这个版本的加了一个多线程.. 就不会弄了
原版的duilib我是创建一个WTL窗口, 之后继承CWindowWnd和INotifyUI当做子窗口

**Comment by nmgwddj** [comment]
不推荐在 Duilib 中嵌入原生标题栏和菜单栏，两种混合使用会带来较大的维护成本，不仅仅是 UI 上的变更，包括原生窗口的消息处理都需要单独维护。
另外原生标题栏和菜单栏是一种通用原生窗口的设计语言，使用 Duilib 更多是能打破这种束缚，从交互设计角度就彻底与原生提供能力分离。

**Comment by ClearSeve** [comment]
明白了，原来这样，谢谢您能够回答我的问题。
