### ISSUE TITLE
zip资源文件有密码时创建控件失败

### ISSUE THREAD

**Issue by djzbj** [netease-im/NIM_Duilib_Framework#248]
使用zip资源文件时，如果设置密码
GlobalManager::CreateBoxWithCache 下面的
 box = builder->Create(strXmlPath.c_str(), callback); 
 返回了null导致报错

zip文件没有密码正常

**Comment by smallevilbeast** [comment]
使用develop分支试试

**Comment by djzbj** [comment]
我试试
