### ISSUE TITLE
如何动态添加按钮？

### ISSUE THREAD

**Issue by haifenghuang** [netease-im/NIM_Duilib_Framework#249]
我这里有个xml文件，内容如下：

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Window size="850,800" caption="0,0,0,34" sizebox="4,4,4,4" textid="STRID_CEF_BROWSER_OFF_SCREEN_MODE">
<Box  width="850" height="650">
	<HBox width="550" height="32" margin="200,10,50,10">
		<!-- 这里动态添加几个按钮 -->
	</HBox>
</Box>

</Window>
```
请问我用代码如何实现？

**Comment by nmgwddj** [comment]
参考 richlist 动态创建 item 实现：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/examples/richlist/richlist_form.cpp#L38

**Comment by haifenghuang** [comment]
非常感谢，你给的例子是VListBox，但是我希望的是HBox，动态增加的button的位置（左边距）是不固定的，
我现在的需求是添加的按钮的布局如下：

---------------------------------------------------
   |  button1 |  button2 |  button3 |  button4 |
----------------------------------------------------

请问对于这样的布局，`xml`文件中大致应该怎么写呢？

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
