### ISSUE TITLE
浏览器BUG

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#25]
## 问题现象
跳转网址不起作用
## 重现步骤

1.输入biying.com 随便搜索什么，跳出很多网址
2. 点击这些网址，并没有跳转到对应网站，还是停留在当前网页上

**Comment by nmgwddj** [comment]
参考 CEF 文档 https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Controls/CefControl.md#AttachLinkClick 和 multi_browser 示例添加 AttachLinkClick 处理方法。
