### ISSUE TITLE
怎么模拟按钮点击？

### ISSUE THREAD

**Issue by haifenghuang** [netease-im/NIM_Duilib_Framework#257]
项目需求：请求后端返回电影类型，后端会返回一个电影类型列表(例如:["动作", "爱情", "科幻", "古装"])。

我需要根据后端返回的电影类型来动态创建一些按钮，同时我希望能够模拟第一个按钮(“动作”按钮)的点击事件，在这个点击事件中我需要做大致如下的操作：
       1. 设置点击的按钮的颜色（以区别与未点击按钮的颜色）
       2. 根据点击的按钮所对应的类别，来请求后端返回相应的电影列表。

请问一下这个用程序怎么做到？

**Comment by nmgwddj** [comment]
Issue 作为问题跟踪和新功能开发跟踪，我们开通了 Github discussions 用以交流使用方式，请访问 Discussions 来提交你的询问以获取帮助：https://github.com/netease-im/NIM_Duilib_Framework/discussions
