### ISSUE TITLE
Event事件 同名控件问题

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#26]
<VBox name="official">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Official" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>    
         
<VBox name ="test">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Test" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>     

比如，我想实现关联操作，选中第一个的某个option， 第二个盒子中的也同样选中， 反之亦然， 但是两个option名字是相同的，  
这种情况下，全局的my_option   肯定是两个VBOX的某一个 ，比如是第一个的话，则点击第一个时， 第二个盒子并没有被关联

能不能除了全局、 .\  可以扩展成 某个父节点下的定位  比如    test\my_option 这样的，如果能扩展成这样，就没这个问题了

**Comment by shuilan0066** [comment]
`<VBox name="official">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Official" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>    
         
<VBox name ="test">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Test" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>     `

**Comment by shuilan0066** [comment]
<VBox name="official">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Official" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>    
         
<VBox name ="test">
            <HBox name="noIntHBox">
               <Option   name="my_option" group="layout_Test" />
                <Event type="buttondown" receiver="my_option .\my_option" applyattribute="selected=&quot;true&quot;" />
             </HBox>
<VBox>

**Comment by shuilan0066** [comment]
![image](https://user-images.githubusercontent.com/16250519/58398214-e22bb900-8086-11e9-8466-58fc140b8c63.png)

**Comment by nmgwddj** [comment]
@shuilan0066 代码已经开源，您可以随意拓展。

**Comment by shuilan0066** [comment]
@nmgwddj  好的已添加 实现

![image](https://user-images.githubusercontent.com/16250519/58446487-78b5b400-8133-11e9-86df-91b260baac7a.png)
