### ISSUE TITLE
cef的开发者工具在下js断点时候会和js一起卡住

### ISSUE THREAD

**Issue by gitcsw** [netease-im/NIM_Duilib_Framework#260]
使用：cef_control_->AttachDevTools(cef_control_dev_); 
开发者工具和浏览界面在同一线程，有没有多线程参考？

**Comment by nmgwddj** [comment]
现在这种情况下对你实际业务有什么特殊的影响吗，能否描述问题的背景？

**Comment by gitcsw** [comment]
暂时没有特殊影响，因为我是学习一下Duilib的，在测试时候发现的问题，具体问题如下：
按照example里的步骤，
1、首先在winMain开头初始化cef(路径有所更改)：
nim_comp::CefManager::GetInstance()->AddCefDllToPath();
CefSettings settings;// 初始化 CEF
nim_comp::CefManager::GetInstance()->Initialize(nbase::win32::GetCurrentModuleDirectory() + L"\\cef\\", settings, kEnableOffsetRender);
2、创建一个窗口后，在initWindow()中：
cef_control_->AttachDevTools(cef_control_dev_);
cef_control_->LoadURL(nbase::win32::GetCurrentModuleDirectory() + L"html\\index.html");
现在我在开发者工具Sources标签中，在JS代码处下断点，当JS运行到断点后，开发者工具窗口内部元素全部假死。
所以应该是cef的开发者工具与前端显示在同一线程关系，望提供一下相关代码修改思路，感谢。

**Comment by gitcsw** [comment]
已发现问题，在cef_manager.cpp大约248行把cef在debug运行改成了单线程。
