### ISSUE TITLE
CEF 显示时，如果桌面上有搜狗输入法 右下角的提示框，则这个搜狗提示框总闪烁

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#263]
CEF 显示时，如果桌面上有搜狗输入法 右下角的提示框，则这个搜狗提示框总闪烁

不知是什么原因引起的 ，如何解决

**Comment by nmgwddj** [comment]
Issue 针对已知问题的跟踪，建议您移步到 Discussions 来讨论排查具体问题原因后再根据情况提交 Issue 来跟踪问题，问题的重现步骤、几率以及建议的修改方案。
针对你的问题，建议排查窗口是否频繁的拥有和失去焦点导致输入法频繁的切换状态。其他输入法是否有类似问题？频繁闪烁时输入法的栈信息是如何体现的等。
