### ISSUE TITLE
云信duilib自定义控件嵌入win32窗口绘制视频失败

### ISSUE THREAD

**Issue by ChnPhantom** [netease-im/NIM_Duilib_Framework#264]
有一个主窗口，在此主窗口之上我做了以下操作，目的是想实现duilib+SDL2播放视频的功能
首先：我基于云信duilib自定义了一个VideoWndUI控件，如下所示：
![image](https://user-images.githubusercontent.com/5669600/103262419-daa96000-49df-11eb-9fdb-35a8391ab2d1.png)
然后：实现了一个VideoWnd窗口类，如下所示：
![image](https://user-images.githubusercontent.com/5669600/103262467-fdd40f80-49df-11eb-974a-8f33e1a2ce39.png)
![image](https://user-images.githubusercontent.com/5669600/103262480-04628700-49e0-11eb-9cb4-278e7b64c2a3.png)
问题：
创建除CHILD类型以外的窗口类型，都是可以显示图像的。

**Comment by nmgwddj** [comment]
我没有实战过使用 SDL2 在 duilib 的 CHILD 类型窗口做绘制操作，你的问题我建议的排查方向是可以关注下 CHILD 属性的窗口在绘制时是否被 duilib 原有的绘制能力覆盖。

**Comment by ChnPhantom** [comment]
原生的duilib的CHILD类型窗口做绘制是可以的，但是使用nim duilib，就像你说的被覆盖了一样，没有显示任务图像。

**Comment by nmgwddj** [comment]
@ChnPhantom 由于我环境有限，这个问题可能要你跟一下绘制相关的出口和 SDL 的绘制事件，是否有重叠或其他情况。如果有进一步消息还请及时反馈。

**Comment by ChnPhantom** [comment]
好的，因为项目情况，后续排查后，如果有进一步的消息，我即时在这里回复

**Comment by ChnPhantom** [comment]
我发现是主窗口启用了阴影效果，因为我创建的STATIC控件是附属于主窗口的WS_CHILD类型。

**Comment by ChnPhantom** [comment]
我阅读了ShadowWndBase，使用这种方法解决了我的问题

**Comment by wangzm1218** [comment]
你好，取消了设置WS_EX_LAYERED属性，父窗口的边框黑色怎么取消。

**Comment by ChnPhantom** [comment]
你可以从这个类继承实现你的窗口
![image](https://user-images.githubusercontent.com/5669600/116174634-61c5d500-a741-11eb-8493-f8327d34f396.png)
