### ISSUE TITLE
发现个奇怪问题，GetImage中 std::wstring 非空字符串给其赋值后，其值为空

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#268]
void Control::GetImage(Image& duiImage) const
{
	if (duiImage.imageCache) {
		return;
	}
	std::wstring sImageName = duiImage.imageAttribute.sImageName;

如下所示，这是什么原因造成的呢 

debug时，
sImageName 值为空
duiImage.imageAttribute.sImageName  值为 xnwRes/db/nor/5.png

不明白，为什么赋值后， sImageName 怎么是空 而不是和duiImage.imageAttribute.sImageName 一样的值呢

![image](https://user-images.githubusercontent.com/16250519/103635693-da7f0680-4f83-11eb-95bd-fd02684348db.png)

**Comment by nmgwddj** [comment]
这取决于你断点位置，截图不是很完整，没办法判断该值为何为空。
若该问题当前为未确认为缺陷，建议在 Discussions 中讨论。如果已经确认为缺陷，请按缺陷格式提交 Issue。

**Comment by shuilan0066** [comment]
发现可能原因了， 应该是没有再UI线程中 操作控件引起的
