### ISSUE TITLE
有没有接入UIAutomation的计划？

### ISSUE THREAD

**Issue by peilinok** [netease-im/NIM_Duilib_Framework#269]
QA对于windows端自动化测试一直抱怨很深，调研了一下UIAutomation的可行性，想问下，官方或者其他人有没有计划或者正在做这件事情？以免重复造轮子。

**Comment by nmgwddj** [comment]
还处于 Story 阶段。

**Comment by peilinok** [comment]
我这里初步调研应该是完全可以加上的，至少大部分控件是可以支持的，近期我可能会尝试加一下

**Comment by nmgwddj** [comment]
> 我这里初步调研应该是完全可以加上的，至少大部分控件是可以支持的，近期我可能会尝试加一下

期待您的佳作。

**Comment by peilinok** [comment]
![image](https://user-images.githubusercontent.com/7828663/106230230-fe073b00-6229-11eb-93a4-3d66bc188d48.png)
已经完成 70%-80%

**Comment by peilinok** [comment]
https://github.com/peilinok/NIM_Duilib_Framework/tree/peilinok/feature

**Comment by nmgwddj** [comment]
> https://github.com/peilinok/NIM_Duilib_Framework/tree/peilinok/feature
> rebase develop后无法编译通过。。。。。。
我先尝试拉取您 fork 的代码修正编译方面的问题。

**Comment by nmgwddj** [comment]
https://github.com/peilinok/NIM_Duilib_Framework/pull/1
在你的仓库提交了 PR，你可以继续在这个分支上开发。

**Comment by peilinok** [comment]
> [peilinok#1](https://github.com/peilinok/NIM_Duilib_Framework/pull/1)
> 在你的仓库提交了 PR，你可以继续在这个分支上开发。

辛苦了，那UIA模块是否可以提PR入netease分支中？低版本系统需要用另外一套自动化手段，所以在startup中加了开关来控制是否启用该功能，暂时开发者可自行选择是否开启。

**Comment by nmgwddj** [comment]
@peilinok 你可以暂时 PR 到 `feature/ui_automation` 分支。
由于目前工程默认配置是 Visual Sutdio 2013 v120_xp 的配置，代码合并后默认的工程配置是无法编译新添加的 UIA 先关功能的，我建议可以先做一些适配，确保可以在该配置下正常编译，比如做一些宏隔离。

**Comment by peilinok** [comment]
OK


| |
黄沛霖
|
|
***@***.***
|

签名由 网易邮箱大师 定制

在2021年03月18日 11:38，Dylan Deng 写道：

@peilinok 你可以暂时 PR 到 feature/ui_automation 分支。
由于目前工程默认配置是 Visual Sutdio 2013 v120_xp 的配置，代码合并后默认的工程配置是无法编译新添加的 UIA 先关功能的，我建议可以先做一些适配，确保可以在该配置下正常编译，比如做一些宏隔离。

**Comment by peilinok** [comment]
![image](https://user-images.githubusercontent.com/7828663/111992130-086df300-8b50-11eb-8e92-b12994469e04.png)


> @peilinok 你可以暂时 PR 到 `feature/ui_automation` 分支。
> 由于目前工程默认配置是 Visual Sutdio 2013 v120_xp 的配置，代码合并后默认的工程配置是无法编译新添加的 UIA 先关功能的，我建议可以先做一些适配，确保可以在该配置下正常编译，比如做一些宏隔离。

你好我做了宏用来控制编译时打开全部的UIA代码，最近有些忙，对通过MSC_VER做控制不熟悉，暂时使用此办法，但最终仍然有上图编译错误，是否是我这边的环境问题？

https://github.com/peilinok/NIM_Duilib_Framework/commits/peilinok/feature
