### ISSUE TITLE
DPI 文本缩放更改时崩溃

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#27]
## 问题现象
启用DPI后 ，改变文本缩放比例时 出现崩溃
## 重现步骤

1. 启用dpi，  改变显示器文本缩放比例

我查了下崩溃dump，在这里
![image](https://user-images.githubusercontent.com/16250519/58603221-8baabe80-82c2-11e9-815c-bc9724064fce.png)

改的话，只需要加下判断就可以么，还是还有什么相关项，我是加了下判断，能继续执行了，但不知有无隐患
![image](https://user-images.githubusercontent.com/16250519/58603286-c3196b00-82c2-11e9-92d2-1c5f9c774c22.png)

**Comment by nmgwddj** [comment]
这个问题的确存在，场景为不带有 LAYERED 属性的窗口没有附加阴影效果时，当 DPI 变更触发该函数时由于没有正确附加阴影所以出现崩溃，该问题已经由 https://github.com/netease-im/NIM_Duilib_Framework/commit/11dbe9344eff982dc69072218c940348873d13f1 修复。
