### ISSUE TITLE
在制作DLL插件使用FrameworkThread无法启动主程序

### ISSUE THREAD

**Issue by fengshen4399** [netease-im/NIM_Duilib_Framework#273]
## 问题现象
制作X64的插件(DLL) 在DllMain函数下使用以下函数创建线程无法启动主程序
MiscThread(kThreadGlobalMisc, "Global Misc Thread").RunOnCurrentThreadWithLoop(nbase::MessageLoop::kDefaultMessageLoop);
以及		
misc_thread_.reset(new MiscThread(kThreadGlobalMisc, "Global Misc Thread"));
misc_thread_->Start();

## 预期结果
希望能和线程池一样

## 重现步骤
在DLL中建立一个线程并启动.主程序直接阻塞

**Comment by nmgwddj** [comment]
无法启动主程序的具体表现是如何的，另外您说希望预期和线程池一样这个具体想如何表现这种场景？
