### ISSUE TITLE
edit 控件不能复制？

### ISSUE THREAD

**Issue by cvwet** [netease-im/NIM_Duilib_Framework#277]
怎么响应ctrl-c复制等命令

**Comment by cvwet** [comment]
> 怎么响应ctrl-c复制等命令

可以复制粘贴，只是没有右键菜单

**Comment by nmgwddj** [comment]
使用方式相关的问题可以在 Discussions 中讨论。
右键菜单根据鼠标点击坐标动态在指定位置创建菜单实现 Copy 等能力。
