### ISSUE TITLE
建议给字体加上 id 属性

### ISSUE THREAD

**Issue by 01haike** [netease-im/NIM_Duilib_Framework#28]
当字体多的时候可能不好确定id，建议给字体加上 id 属性。

**Comment by nmgwddj** [comment]
@wizcpp 很好的建议。

**Comment by lovesnow** [comment]
可以在Font节点定义一个alias属性，增加别名管理

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/pull/42 已增加此功能。
由 @nmgwddj 更新文档。
