### ISSUE TITLE
VS2019编译错误

### ISSUE THREAD

**Issue by bptx0114** [netease-im/NIM_Duilib_Framework#280]
![QQ截图20210307152019](https://user-images.githubusercontent.com/17290890/110232512-0c4b2400-7f59-11eb-8cea-e46d64e77592.png)
请问这是哪里错了？

**Comment by Kaakira** [comment]
项目属性里 c/c++ 语言符合模式，改成否
https://docs.microsoft.com/zh-cn/cpp/build/reference/permissive-standards-conformance?view=msvc-160
