### ISSUE TITLE
win10 vs2019 编译ui_components出错

### ISSUE THREAD

**Issue by munitioner** [netease-im/NIM_Duilib_Framework#284]
在win10  vs2019环境下编译ui_components报错
![image](https://user-images.githubusercontent.com/14157458/111427159-a3219880-8730-11eb-8f03-15a2702e4ced.png)

**Comment by nmgwddj** [comment]
VS2019 已经取消了对 XP 支持，你选择的 Windows SDK 版本还是 7.0，尝试修改 Windows SDK 到你安装到本地的版本。

**Comment by munitioner** [comment]
![微信图片_20210317213853](https://user-images.githubusercontent.com/14157458/111476741-67ef8b80-8769-11eb-89f0-e62c2a70f972.png)
就是用的兼容xp的sdk

**Comment by nmgwddj** [comment]
该问题已经在 develop 分支修正了，你可以修改一下你本地的复合模式选项：
![2021-03-18_09-15-16](https://user-images.githubusercontent.com/13995319/111558938-9ea9be00-87ca-11eb-82fd-32beeebc164b.png)

**Comment by munitioner** [comment]
好的，谢谢！
