### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by BestP2P** [netease-im/NIM_Duilib_Framework#292]
is there any new release version? thank you

**Comment by nmgwddj** [comment]
目前 master 为稳定分支，一些新的功能我们在 develop 中进行开发，但他们可能不稳定，如果你需要体验可以 checkout develop 来尝试。
Master is a stable branch. We are developing some new features in  branch `develop`, but they may be unstable. If you want to try some new features, you can checkout branch `develop`.
