### ISSUE TITLE
如何实现一个卷帘的效果

### ISSUE THREAD

**Issue by xiaoyu21git** [netease-im/NIM_Duilib_Framework#294]
因为使用duilib 的时间并不多，但是由于最近项目需要更换UI所以我选择这个库，原来项目是用MFC 做的其中有一个功能是点击一个按钮然后下面出现按钮对应的窗口，再次点击的时候窗口隐藏。类似于tabbox控件只不过要显示的窗口出现在下面。MFC 是RollupCtrl这个类实现的功能，类似卷帘的效果。另外官方是不是出一个这个库使用的一个布局或者效果的集合。我发现现在关于这个版本的教程非常少，有的都是收费的。虽然我很菜但是我会把我使用这个库的一些心得发到博客上或者有没有专门的社区呢。。谢谢辛苦了

**Comment by nmgwddj** [comment]
对于库功能的使用建议在 Discussions 中讨论，Issues 中仅保留已确认缺陷或待开发新功能讨论。
针对你的问题，可以参考我们基于 NIM duilib 开发的 IM 即时通讯 Demo，它几乎涵盖了所有业务场景：https://github.com/netease-im/NIM_PC_Demo
