### ISSUE TITLE
我想要把第三方控件加入到界面上，应该如何做呢？实例代码有吗？

### ISSUE THREAD

**Issue by LZUXK** [netease-im/NIM_Duilib_Framework#295]
如题：我想加入第三方的ACtiveX控件，不知道是否支持？应该怎么实现呢？非常感谢

**Comment by nmgwddj** [comment]
原版 duilib 关于 ActiveX 控件的能力在 NIM duilib 中已经移除，不知道你要使用的 ActiveX 控件是具体什么能力？我看有没有其他的方案可以给到你。

**Comment by LZUXK** [comment]
我现在要准备使用teechart的图表控件来实现统计分析的功能，又或者说我现在的项目中有很多以前自己封装的MFC ActiveX控件想要直接使用。不知道我这样描述的是否清楚？
希望能有一个可实施的方案，谢谢

**Comment by nmgwddj** [comment]
目前的确无法实现你加载旧版 MFC ActiveX 控件的需求。
现有方案中，我个人建议基于 CEF 接入前端方案，现在前端的图标库及控件非常丰富，可以减少很多底层能力实现的维护，而不依赖本地的 ActiveX 控件。

**Comment by LZUXK** [comment]
好的，了解，谢谢。
