### ISSUE TITLE
关于TABLE的使用

### ISSUE THREAD

**Issue by xiaoyu21git** [netease-im/NIM_Duilib_Framework#299]
能不能提供一下TBABOX加载分页的dome吗？最好能说一下布局文件和初始化控件等详细的流程，就是table控件到切换选项然后如何加载对应的xml文件和切换到其他的xml文件后是怎么执行的，流程是什么样的，使用什么样的接口。我看了demo但是不是特别明白：session_box_tab_ = static_cast<TabBox*>(FindControl(L"session_box_tab"));这是个tab。SessionBox* session_box = new SessionBox(session_id, session_type);
	session_box_tab_->Add(session_box);
GlobalManager::FillBoxWithCache(session_box, L"session/session_box.xml");加载xml文件
session_box->SetName(id);
	session_box->InitSessionBox();初始化控件
	taskbar_manager_.RegisterTab(*session_box->GetTaskbarItem());//这个不知道干嘛的。。。
我是想把每个分页写成单独的xml文件然后分开管理不知道能不能行。

**Comment by nmgwddj** [comment]
在网易云信 IM 即时通讯 Demo 中有一个功能简单的案例，在设置页面通过 TabBox 切换音频和视频的配置页面，你可以参考这里的实现逻辑：
https://github.com/netease-im/NIM_PC_Demo/blob/master/tool_kits/ui_component/av_kit/gui/video/video_setting.cpp
https://github.com/netease-im/NIM_PC_Demo/blob/master/bin/resources/themes/default/video/video_setting.xml

**Comment by xiaoyu21git** [comment]
我看了那部分的代码，但是好像跟我的情况还不太一样。我的情况是想通过动态加载的方式切换因为每个要切换的地方布局有点多，所以我就拆分了不同的xml文件。这部分可能更像是会话的那部分就是我上面贴的，我之前的理解是每个xml文件是一个独立的窗口，但是现在想想这个思路是不对的，他可能是一个ListContainerElement，不知道这么想对不对。

**Comment by nmgwddj** [comment]
关于功能使用的咨询，建议在 Discussions 中讨论。
您的问题可以参考动态创建控件并附加到指定控件容器中的能力，参考 rich_list 代码动态创建 item 的能力。

**Comment by xiaoyu21git** [comment]
好的
