### ISSUE TITLE
为什么不尝试合进  https://github.com/duilib/duilib

### ISSUE THREAD

**Issue by runner-mei** [netease-im/NIM_Duilib_Framework#3]
为什么不尝试合进  https://github.com/duilib/duilib

那个不是正式官方版本么？

**Comment by nmgwddj** [comment]
主要有以下几点。

 - 开发时并不是实时与初代版本协作开发，合并代码量极大，涉及 duilib 源码和 demo 的改动。
 - 除核心模块外，其他代码和结构设计理念上可能与初代版本有极大差异。
 - 因为以上两个原因在加上 MIT 协议的许可遂单独开出分支提供不同喜好和不同目标群体使用。
