### ISSUE TITLE
父容器尺寸不是根据子元素计算出来的

### ISSUE THREAD

**Issue by wizcpp** [netease-im/NIM_Duilib_Framework#30]
我按照文档“快速上手”新建一个工程，xml 如下：

`<?xml version="1.0" encoding="UTF-8"?>
<Window size="500,450" caption="0,0,0,35">
<VBox bkcolor="white">
  <VBox name="vbox1" bordersize="2" bordercolor="red">
    <Button text="test" height="16" bordersize="1" bordercolor="blue"></Button>
    <Button text="test" height="16" bordersize="1" bordercolor="blue"></Button>
  </VBox>
  <VBox name="vbox2">
  </VBox>
</VBox>
</Window>`

运行效果是 vbox1 与 vbox2 的高度是一样的。

想问一下这里必须要设置一下vbox1 的高度吗？有办法让 vbox 的高度等于其子元素的高度之和吗？
谢谢。

**Comment by wizcpp** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<Window size="500,450" caption="0,0,0,35">
<VBox bkcolor="white">
  <VBox name="vbox1" bordersize="2" bordercolor="red">
    <Button text="test" height="16" bordersize="1" bordercolor="blue"></Button>
    <Button text="test" height="16" bordersize="1" bordercolor="blue"></Button>
  </VBox>
  <VBox name="vbox2">
  </VBox>
</VBox>
</Window>`

**Comment by shuilan0066** [comment]
height="auto"试试

**Comment by nmgwddj** [comment]
@wizcpp 如 @shuilan0066 所述，您可以给控件高度设置 auto 属性，让控件根据子控件自动计算位置。如果 @shuilan0066 的回答有帮助您解决问题，请主动关闭 issue，谢谢。

```
<VBox bkcolor="bk_wnd_darkcolor">
      <VBox height="auto" bkcolor="lightcolor">
        <Button class="btn_global_blue_80x30" text="TestButton"/>
      </VBox>
      <VBox bkcolor="dark_gray">
      </VBox>
    </VBox>
```

**Comment by wizcpp** [comment]
> @wizcpp 如 @shuilan0066 所述，您可以给控件高度设置 auto 属性，让控件根据子控件自动计算位置。如果 @shuilan0066 的回答有帮助您解决问题，请主动关闭 issue，谢谢。
> 
> ```
> <VBox bkcolor="bk_wnd_darkcolor">
>   <VBox height="auto" bkcolor="lightcolor">
>     <Button class="btn_global_blue_80x30" text="TestButton"/>
>   </VBox>
>   <VBox bkcolor="dark_gray">
>   </VBox>
> </VBox>
> ```

试了下，可以解决。谢谢二位@shuilan0066  @nmgwddj 。
建议这个功能是父元素默认的属性。等要想设置大小的时候，再给父元素设置一下。
