### ISSUE TITLE
xml属性值

### ISSUE THREAD

**Issue by BestP2P** [netease-im/NIM_Duilib_Framework#300]
Font 这个xml里面的属性值应该在哪里查看呢，例如设置font的color？
<Font id="system_12" name="system" size="12" default="true"/>
不知道哪里可以查看所有属性？
控件的属性，也不知道在哪里查看？
doc文档下面也没有描述的很全面，跟标准的duilib属性差别有点大

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/SUMMARY.md
