### ISSUE TITLE
高DPI下图片即模糊又有锯齿

### ISSUE THREAD

**Issue by huycode** [netease-im/NIM_Duilib_Framework#302]
是不是高DPI下控件是放大了，但图片是原尺寸的放大了，有没有其他的高清显示方法了。
其实友商的图片在DPI下显示方法也可以参考参考，根据不同的缩放比例后缀加载图片，tp.png、tp@125.png、tp@150.png、tp@175.png。。。

**Comment by nmgwddj** [comment]
这个功能暂时没有支持，给您一个思路，可以在获取图片时使用 DPIManager 判断一下当前缩放比例来加载 @2x 等后缀的图片。

**Comment by peilinok** [comment]
> 是不是高DPI下控件是放大了，但图片是原尺寸的放大了，有没有其他的高清显示方法了。
> 其实友商的图片在DPI下显示方法也可以参考参考，根据不同的缩放比例后缀加载图片，tp.png、[tp@125.png](mailto:tp@125.png)、[tp@150.png](mailto:tp@150.png)、[tp@175.png](mailto:tp@175.png)。。。

新版不是有SVG啦
