### ISSUE TITLE
支持Tab键切换控件焦点吗？

### ISSUE THREAD

**Issue by 01haike** [netease-im/NIM_Duilib_Framework#31]
支持Tab键切换控件焦点吗？

**Comment by wizcpp** [comment]
https://github.com/qdtroy/DuiLib_Ultimate 这个库有提供默认的 Tab 切换功能。
在下面这个函数中：CPaintManagerUI::PreMessageHandler 做的处理。

**Comment by nmgwddj** [comment]
@wizcpp 现在代码中没有对 Tab 切换控件焦点做支持，我会考虑用何种方式增加类似功能，您也可以提交 PR 来帮我们完善该功能。

**Comment by nmgwddj** [comment]
Hi @01haike，https://github.com/netease-im/NIM_Duilib_Framework/commit/bef5c9ac8e57b9660b4e6d09758e1836fd6ee4e2 已经添加了 tab 切换控件焦点的功能。这部分功能代码因为一些历史原因是注释掉的，这次提交只是将注释的部分代码打开并打通切换焦点的逻辑，在控件切换焦点时会将获取到焦点的控件设置为 hot 状态。
一些特殊的控件比如 RichEdit 需要在按下 Tab 键将焦点切换到其他控件时，请设置 `wanttab` 属性为 false，否则 RichEdit 会默认处理自己的 Tab 按键功能。
目前尚不支持对获取到焦点的控件按回车、空格、上下方向键等响应，需要后期不断完善。
