### ISSUE TITLE
develop版本的SVN#345的duilib代码能编译通过，#346的版本都不行,最新版本的也不行，中间几个版本也试了不行，不知道原因，希望能帮忙处理一下。谢谢

### ISSUE THREAD

**Issue by LZUXK** [netease-im/NIM_Duilib_Framework#316]
如题，试了VS2019和VS2013都不行

已启动生成…
1>------ 已启动生成: 项目: duilib, 配置: Debug Win32 ------
1>cl : 命令行 warning D9035: “Gm”选项已否决，并将在将来的版本中移除
1>Window.cpp
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\WorkPlace\222\duilib\Core\Window.cpp(275,2): error C2065: “oMonitor”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(275,27): error C2065: “oMonitor”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(276,73): error C2065: “oMonitor”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(277,11): error C2065: “oMonitor”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1083,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1964,40): warning C4838: 从“int”转换到“BYTE”需要收缩转换
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1967,2): error C2059: 语法错误:“else”
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1967,7): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1967,7): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1972,13): error C2065: “m_hWnd”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1972,22): error C2065: “ps”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1972,24): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1972,25): error C2440: “初始化”: 无法从“initializer list”转换为“int”
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1972,12): message : 初始值设定项包含过多元素
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1975,6): error C2653: “Window”: 不是类或命名空间名称
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1978,6): error C2065: “m_pRoot”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1979,3): error C2065: “m_nAlpha”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1980,14): error C2065: “m_pRoot”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1980,3): error C3861: “Invalidate”: 找不到标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1984,6): error C2653: “Window”: 不是类或命名空间名称
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1985,1): error C2270: “IsRenderTransparent”: 非成员函数上不允许修饰符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1986,9): error C2065: “m_renderContext”: 未声明的标识符
1>D:\WorkPlace\222\duilib\Core\Window.cpp(1989,6): error C2653: “Window”: 不是类或命名空间名称

**Comment by ruincrez** [comment]
编码的问题，Windows.cpp不知道为什么使用了UTF-8编码，改成GB2312就可以正常编译了
