### ISSUE TITLE
ring.h 引用的头文件 Vfw.h 中宏 ToHex 与 protobuf 冲突，编译失败

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#32]
## 问题现象
项目中使用 protobuf，在 stdafx.h 中引用头文件 shared.h，导致编译错误。
protobuf 里的头文件 strutil.h 中定义了一个函数 ToHex 与 Vfw.h 宏 ToHex 冲突。
## 重现步骤

1.
2.

**Comment by nmgwddj** [comment]
请使用命名空间（namespace）加以保护。
