### ISSUE TITLE
颜色值设置问题

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#33]
## 问题现象
`<HBox width="stretch" height="35" bkcolor="#ff0E8EE7">`

bkcolor 不能这样设置吗

这样设置就直接报错了

**Comment by lovesnow** [comment]
有的颜色是单页面使用的， 全放在Global也不合适丫- -

**Comment by nmgwddj** [comment]
一套合理的视觉设计颜色不会多种多样的，每一个颜色都是有针对性、精心挑选的。类似 element-ui、antd 等前端 UI 组件库，都是有一套主题管理方案的：https://element.eleme.cn/#/zh-CN/component/custom-theme

每一种色彩对应的都是一个场景，比如进度条前景色、进度条背景色等，这样方便换肤等特效方法的实现。如果您出现了一个颜色只有一个位置使用，那是不是应该考虑一下这是否违背了 UI 的设计原则呢？

**Comment by lovesnow** [comment]
这个回答真赞 👍
