### ISSUE TITLE
有一个登录对话框，一个主界面，正确的做法是怎么安排？

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#34]
比如我有一个登录对话框，一个主界面。先显示登录对话框，登录后，再显示主界面。如果我用ShowModal 显示登录对话框，然后再显示主界面，这样做主界面不会显示出来。

我看了所有的例子，都是在显示一个窗口的，没有显示两个的。所以想问一下正确做法是什么？

**Comment by nmgwddj** [comment]
@caop3ng 参考 ui_components 项目中的 WindowsManager 类，该类提供了窗口管理的一系列方法，与 duilib 完全分离，如果你有很多窗口需要管理，我相信这个一定能帮到你。
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/tool_kits/ui_components/windows_manager/windows_manager.h#L87
它的使用方法参考云心 IM Demo，里面有各种各样的示例：https://github.com/netease-im/NIM_PC_Demo/blob/17a5f9b2323c16c48900efbc21d8cc25590b66f1/nim_win_demo/gui/login/login_form.cpp#L184

你也可以从云信官网下载 IM Demo 最新源码包查看我们常用的手段都有哪些：https://yx-web-nosdn.netease.im/package/1558689357/NIM_PC_Demo_x86_x64_v6.5.0.7z?download=NIM_PC_Demo_x86_x64_v6.5.0.7z

**Comment by caop3ng** [comment]
> @caop3ng 参考 ui_components 项目中的 WindowsManager 类，该类提供了窗口管理的一系列方法，与 duilib 完全分离，如果你有很多窗口需要管理，我相信这个一定能帮到你。
> https://github.com/netease-im/NIM_Duilib_Framework/blob/master/tool_kits/ui_components/windows_manager/windows_manager.h#L87
> 它的使用方法参考云信 IM Demo，里面有各种各样的示例：https://github.com/netease-im/NIM_PC_Demo/blob/17a5f9b2323c16c48900efbc21d8cc25590b66f1/nim_win_demo/gui/login/login_form.cpp#L184
> 
> 你也可以从云信官网下载 IM Demo 最新源码包查看我们常用的手段都有哪些：https://yx-web-nosdn.netease.im/package/1558689357/NIM_PC_Demo_x86_x64_v6.5.0.7z?download=NIM_PC_Demo_x86_x64_v6.5.0.7z

谢谢。
