### ISSUE TITLE
VListBox 与 ListBox 有什么区别？

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#35]
为什么在 xml 中定义成 ListBox 后，代码里动态添加 Item 只会显示在第一行？

**Comment by lovesnow** [comment]
VirtualListBox 是懒加载，对于数据量大的列表，用VirtualListBox

**Comment by caop3ng** [comment]
> VirtualListBox 是懒加载，对于数据量大的列表，用VirtualListBox

xml 中定义一个 ListBox， InitWindow 中动态添加两个或更多 elem。所有的 elem 都会显示到一起。
换成 VListBox 就正常。

**Comment by nmgwddj** [comment]
@caop3ng 
请注意以下代码，默认 ListBox 是没有布局特性的，而 VListBox 和 HListBox 是有布局特性的。

```
else if( strControlClass == DUI_CTR_HLISTBOX )			pControl = new ListBox(new HLayout);
else if( strControlClass == DUI_CTR_VLISTBOX )          pControl = new ListBox(new VLayout);
```
