### ISSUE TITLE
WIN10 VS2019编译提示PostTaskAndReplyRelay::Run重定义

### ISSUE THREAD

**Issue by shadow-yuan** [netease-im/NIM_Duilib_Framework#353]
## 问题现象
我在使用VS2019编译examples时失败，提示PostTaskAndReplyRelay::Run重定义，以下是输出提示：

5>main.cpp
5>正在生成代码...
5>ui_components.lib(stdafx.obj) : error LNK2005: "public: void __thiscall nbase::MessageLoopProxy::PostTaskAndReplyRelay<void __cdecl(void),void __cdecl(void)>::Run(void)" (?Run@?$PostTaskAndReplyRelay@$$A6AXXZ$$A6AXXZ@MessageLoopProxy@nbase@@QAEXXZ) 已经在 stdafx.obj 中定义
5>..\..\bin\controls_d.exe : fatal error LNK1169: 找到一个或多个多重定义的符号
5>已完成生成项目“controls.vcxproj”的操作 - 失败。

**Comment by longloo** [comment]
PostTaskAndReplyRelay把这个函数放到cpp里，在头文件里申明下就可以了

**Comment by nmgwddj** [comment]
使用哪个分支的代码？

**Comment by walletiger** [comment]
遇到 相同 的问题， 你们怎么解决的？

**Comment by nmgwddj** [comment]
> 遇到 相同 的问题， 你们怎么解决的？

请使用 develop 分支代码。

**Comment by reghtml** [comment]
![图片](https://user-images.githubusercontent.com/15364651/156539640-bbf937f4-3c17-49ec-8030-03cdad10c2e7.png)
同样的问题 ，使用的develop 最新代码，从examples复制出来的项目，没这个问题，  自己新建一个项目，相同的代码，确实是有这个问题，目前没找出原因来

**Comment by nmgwddj** [comment]
> ![图片](https://user-images.githubusercontent.com/15364651/156539640-bbf937f4-3c17-49ec-8030-03cdad10c2e7.png) 同样的问题 ，使用的develop 最新代码，从examples复制出来的项目，没这个问题， 自己新建一个项目，相同的代码，确实是有这个问题，目前没找出原因来

注意平台工具集、C++ 编译选项配置是否一致。

**Comment by FallenWhiter** [comment]
请问这个问题有解决吗，解决的话具体要怎么做

**Comment by nmgwddj** [comment]
> 请问这个问题有解决吗，解决的话具体要怎么做

使用 develop 分支代码，执行如下两条命令生成并编译示例程序：

```bash
cmake -Bbuild -G"Visual Studio 16 2019" -AWin32
cmake --build build --config Debug
```
