### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ChowShine** [netease-im/NIM_Duilib_Framework#358]
windows10 ，vs2017，编译shared时报错：
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.16.27023\include\memory(1801):
 error C2664: “AsyncModalRunner::AsyncModalRunner(const AsyncModalRunner &)”: 无法将参数 1 从“_Ty”转换为“AsyncModalRunner::Delegate *”

**Comment by nmgwddj** [comment]
请确认您使用的 Visual Studio 2017 版本为最新版本而非 RTM 版本。

**Comment by nmgwddj** [comment]
https://docs.microsoft.com/en-us/visualstudio/install/update-visual-studio?view=vs-2019
