### ISSUE TITLE
vs2019编译报错

### ISSUE THREAD

**Issue by zjq609177738** [netease-im/NIM_Duilib_Framework#359]
ui_components编译报错 看了下 引用的项目提示如下 
无法解析Microsoft.VisualStudio.ProjectSystem.References.UnresolvedBuildDependencyProject Reference"引用
百度了 也没找到解决方法

**Comment by nmgwddj** [comment]
在提交这个反馈前请确保当前 Issue 中没有相同的问题
请使用最新版本的代码确保你反馈的问题尚未修复

**Comment by zjq609177738** [comment]
> 在提交这个反馈前请确保当前 Issue 中没有相同的问题 请使用最新版本的代码确保你反馈的问题尚未修复（最新代码在 develop 分支维护）

https://github.com/netease-im/NIM_Duilib_Framework这个不就是网易的最新的吗 我没找到netease-im下还有别的分支啊

**Comment by nmgwddj** [comment]
请您参考 git 分支相关概念：https://git-scm.com/book/zh/v2/Git-%E5%88%86%E6%94%AF-%E5%88%86%E6%94%AF%E7%AE%80%E4%BB%8B
