### ISSUE TITLE
去掉 xml 中 Class 标签中的 value, 直接定义属性

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#36]
去掉 class 标签中的 value，直接定义属性，这样省了很多 “&quot;”，看起来也会清晰很多。

**Comment by lovesnow** [comment]
这个建议很好 👍

**Comment by lovesnow** [comment]
我已经提交了PR, 看看作者是否接收 :)

**Comment by caop3ng** [comment]
> 去掉 class 标签中的 value，直接定义属性，这样省了很多 “"”，看起来也会清晰很多。

这里的 """ 是 <&quot;>

**Comment by caop3ng** [comment]
&quot;&quot;&quot;

**Comment by caop3ng** [comment]
> &quot;

**Comment by caop3ng** [comment]
> 去掉 class 标签中的 value，直接定义属性，这样省了很多 “"”，看起来也会清晰很多。

“”“ 是 &quot

**Comment by shuilan0066** [comment]
要设置的话 最好兼容处理

**Comment by nmgwddj** [comment]
Commit:https://github.com/netease-im/NIM_Duilib_Framework/commit/e817180f3c57dc6ab41bcdac44416f4b0d177154
