### ISSUE TITLE
Vs2019 中出现的问题

### ISSUE THREAD

**Issue by lphwxl** [netease-im/NIM_Duilib_Framework#363]
C2039	"_Ref_count_obj": 不是 "std" 的成员

![image](https://user-images.githubusercontent.com/23658463/142754884-aafbf669-1e0d-48a0-b6b3-57b4471f975f.png)

**Comment by nmgwddj** [comment]
- 在提交这个反馈前请确保当前 Issue 中没有相同的问题
- 请使用最新版本的代码确保你反馈的问题在开发分支（develop）尚未修复

**Comment by reghtml** [comment]
你好，这个问题解决了吗，我也是用的VS2019 同样的报错，无法编译通过
![image](https://user-images.githubusercontent.com/15364651/146131503-03f432f4-520e-441f-bda9-31db9b3eb48a.png)

**Comment by nmgwddj** [comment]
> 你好，这个问题解决了吗，我也是用的VS2019 同样的报错，无法编译通过 ![image](https://user-images.githubusercontent.com/15364651/146131503-03f432f4-520e-441f-bda9-31db9b3eb48a.png)

该问题已经在 develop 分支中修复过很久了：https://github.com/netease-im/NIM_Duilib_Framework/commit/55ba0abf544379cf80fcaf0969f84c4971214c26

在提出问题前，请使用最新版本的代码确保你反馈的问题在开发分支（develop）尚未修复

**Comment by reghtml** [comment]
好的谢谢 ，试过了 ，确实可行

**Comment by huangwm999** [comment]
为什么master分支不修复呢，develop分支很多工程编译不了

**Comment by zuxzuk-Canco8-wevniq** [comment]
为什么我现在拉develop最新的还是这个问题
