### ISSUE TITLE
duilib编译失败

### ISSUE THREAD

**Issue by clearsky** [netease-im/NIM_Duilib_Framework#367]
用master分支编译出现#363#，然后下载这个NIM_Duilib_Framework-29fd84eb9ddb8bbfb085f0e1bb5fb42218c18d95,在release_142下编译出现下面的错误
![1](https://user-images.githubusercontent.com/38609798/143725819-66cbd9bf-81d9-45df-8e47-bb4155267c85.png)
![2](https://user-images.githubusercontent.com/38609798/143725821-e92362da-7699-4278-bd87-848ecc5dbf8a.png)

**Comment by nmgwddj** [comment]
在提交这个反馈前请确保当前 Issue 中没有相同的问题。
请使用最新版本的代码确保你反馈的问题尚未在最新代码（develop分支）中修复。

**Comment by clearsky** [comment]
今天又试了下  cpp文件编码的问题(ˉ▽ˉ；)...
