### ISSUE TITLE
VS2019编译shared工程失败

### ISSUE THREAD

**Issue by shengNorth** [netease-im/NIM_Duilib_Framework#371]
![image](https://user-images.githubusercontent.com/49051168/147335743-16af3643-cad5-4059-a17c-02b73f34c933.png)

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/issues/363

- 在提交这个反馈前请确保当前 Issue 中没有相同的问题
- 请使用最新版本的代码确保你反馈的问题在开发分支（develop）尚未修复

**Comment by shengNorth** [comment]
不好意思，大佬，评论错了地方；刚才去NIM_PC Demo看了您的回复，需要用v141工具集，我重新尝试下。
