### ISSUE TITLE
DIB位图绘制不能显示

### ISSUE THREAD

**Issue by lengkristy** [netease-im/NIM_Duilib_Framework#377]
我参照易信pc端的代码 自定义了一个控件，使用普通位图BITMAP进行绘制是没问题的，
![1640845912(1)](https://user-images.githubusercontent.com/37865070/147727410-6798a2bf-966a-4465-b6a2-ab46ef469a68.png)
代码：
![1640845948(1)](https://user-images.githubusercontent.com/37865070/147727439-34a99565-0209-4919-a6b5-066b88e1c873.png)

但是我获取到hdc之后，绘制DBI位图就不显示，代码片段如下:
![1640846048(1)](https://user-images.githubusercontent.com/37865070/147727519-aa563625-5c5c-4c1a-a88b-76bc0e5fcd8c.png)
![1640846087(1)](https://user-images.githubusercontent.com/37865070/147727555-5fdc81bb-b1e4-485f-8d31-986ff33d4b3b.png)
主要是用：
SetDIBitsToDevice、FillRect函数进行绘制，我在MFC、Win32窗口中测试都是没问题，主要是显示pdf图片

**Comment by nmgwddj** [comment]
参考 NIM Demo bitmap control：https://github.com/netease-kit/NIM_PC_Demo/blob/a3a504a33c957922edcdfdfbccbbbc36bc729cc4/tool_kits/ui_component/av_kit/gui/video/helper/ui_bitmap_control.cpp

**Comment by lengkristy** [comment]
> 参考 NIM Demo bitmap control：https://github.com/netease-kit/NIM_PC_Demo/blob/a3a504a33c957922edcdfdfbccbbbc36bc729cc4/tool_kits/ui_component/av_kit/gui/video/helper/ui_bitmap_control.cpp

好的，万分感谢
