### ISSUE TITLE
duilib\Core文件夹下Window.cpp编码类型错误

### ISSUE THREAD

**Issue by zesun96** [netease-im/NIM_Duilib_Framework#378]
## 问题现象

当前文件编码格式为unicode类型，在vs2019中编码错误，导致编译失败，应该和其他文件格式统一改为【简体中文（GB2312）- 代码页936】

**Comment by nmgwddj** [comment]
> ## 问题现象
> 当前文件编码格式为unicode类型，在vs2019中编码错误，导致编译失败，应该和其他文件格式统一改为【简体中文（GB2312）- 代码页936】
> 
> ## 预期结果
> ## 重现步骤

已经将所有文件编码修改为 UTF-8，并在所有工程和 CMakeLists 文件中增加了 /utf-8 的编译选项。由于该选项只有在 VS2017 以上才支持，所以升级了工程至 VS2017 v141_xp。见提交：
https://github.com/netease-im/NIM_Duilib_Framework/commit/cf3c9a7bc0d905c3cab0d1072082bc04bb6a56a8
