### ISSUE TITLE
这里的 CEF  如何加入crx扩展呢

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#379]
想要修改 响应头 去除某些网站的 x-frame 限制，但是没找到直接的方法
找了个crx插件 再谷歌浏览器可以用
但是不知道CEF 中，如何导入这个CRX插件

**Comment by nmgwddj** [comment]
建议到 CEF 论坛中寻求帮助：https://www.magpcss.org/ceforum/index.php
