### ISSUE TITLE
vs2022编译ui_components出错	

### ISSUE THREAD

**Issue by LiangQingHao** [netease-im/NIM_Duilib_Framework#383]
## 问题现象
<img width="661" alt="image" src="https://user-images.githubusercontent.com/52127787/153716805-6ef0f05d-e0d4-4faa-ba7e-3e015cc2317a.png">

## 错误信息
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	"_Ref_count_obj": 不是 "std" 的成员	ui_components	D:\Data\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41

**Comment by nmgwddj** [comment]
在提出新的 issue 前，请确保 issue 中没有相同问题在打开或者已经关闭。
https://github.com/netease-im/NIM_Duilib_Framework/issues/363
