### ISSUE TITLE
nbase::StringAppendVT的错误断言

### ISSUE THREAD

**Issue by QuanZag** [netease-im/NIM_Duilib_Framework#385]
## 问题现象

系统：Windows 10
开发工具：MSVS 2017
使用nbase::StringPrintf，超出默认的缓存大小会出现错误断言

## 原因描述

https://en.cppreference.com/w/cpp/io/c/vfprintf
http://www.cplusplus.com/reference/cstdio/vsnprintf/
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/vsnprintf-vsnprintf-vsnprintf-l-vsnwprintf-vsnwprintf-l?view=msvc-150
关于vsnprintf的返回的说明都有提到，vsnprintf超过缓存大小的情况，返回要写入到缓存的字符长度，而出错会返回-1

## 修改建议
if (result != -1)
{
	assert(0);
	return; /* not expected, result should be -1 here */
}
改为
if (result == -1)
{
	assert(0);
	return; /* not expected, result should be -1 here */
}

**Comment by nmgwddj** [comment]
细心的发现。您可以 fork 工程将修改提交到您的个人仓库，然后发起 Pull Request 将您的修改提交到 develop 分支，来帮助我们修复该问题。

**Comment by QuanZag** [comment]
> 细心的发现。您可以 fork 工程将修改提交到您的个人仓库，然后发起 Pull Request 将您的修改提交到 develop 分支，来帮助我们修复该问题。

已 pull。
