### ISSUE TITLE
ui_components的lib无法打开导致cef案例调试编译不通过

### ISSUE THREAD

**Issue by ishangxue** [netease-im/NIM_Duilib_Framework#387]
IDE VS2022
已按快速使用的要求进行了调整
1\平台工具集 2019
2\windows sdk 10.0.19041.0
3\运行库 debug模式 mtd

编译 basic 正常通过
但是编译 cef不通过
错误信息：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1104	无法打开文件“E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\libs\x64\ui_components.lib”	cef	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\examples\cef\LINK	1	
错误(活动)	E0020	未定义标识符 "MessageLoop"	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\base\framework\message_loop_proxy.h	73	
错误(活动)	E0135	命名空间 "std" 没有成员 "_Ref_count_obj"	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
错误	C2039	"_Ref_count_obj": 不是 "std" 的成员	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
错误	C2039	"_Ref_count_obj": 不是 "std" 的成员	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
警告	C4267	“初始化”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	83	
警告	C4267	“初始化”: 从“size_t”转换到“const int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	83	
警告	C4267	“+=”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	89	
警告	C4267	“+=”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	91	
警告	C4267	“=”: 从“size_t”转换到“uint32_t”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	172	
警告	C4267	“+=”: 从“size_t”转换到“uint32_t”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	189	

尝试处理：
对ui_components重新生成 提示错误信息如下
严重性	代码	说明	项目	文件	行	禁止显示状态
警告	C4267	“+=”: 从“size_t”转换到“uint32_t”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	189	
错误(活动)	E0020	未定义标识符 "MessageLoop"	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\base\framework\message_loop_proxy.h	73	
错误(活动)	E0135	命名空间 "std" 没有成员 "_Ref_count_obj"	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
警告	C4312	“reinterpret_cast”: 从“int”转换到更大的“void *”	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\base\thread\thread_local.h	80	
警告	C4267	“初始化”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\control\cef_control_base_ui.cpp	176	
警告	C4244	“=”: 从“WPARAM”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\control\cef_control_ui.cpp	449	
警告	C4244	“=”: 从“LPARAM”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\control\cef_control_ui.cpp	450	
警告	C4244	“参数”: 从“WPARAM”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\control\cef_control_ui.cpp	478	
警告	C4311	“类型强制转换”: 从“std::function<void (void)> *”到“int”的指针截断	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\util\auto_unregister.h	43	
警告	C4302	“类型强制转换”: 从“std::function<void (void)> *”到“int”截断	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\cef_control\util\auto_unregister.h	43	
错误	C2039	"_Ref_count_obj": 不是 "std" 的成员	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
错误	C2039	"_Ref_count_obj": 不是 "std" 的成员	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\async_modal_runner.h	41	
警告	C4267	“初始化”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	83	
警告	C4267	“初始化”: 从“size_t”转换到“const int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	83	
警告	C4267	“+=”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	89	
警告	C4267	“+=”: 从“size_t”转换到“int”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	91	
警告	C4267	“=”: 从“size_t”转换到“uint32_t”，可能丢失数据	ui_components	E:\Microsoft Visual Studio\vsproj\NIM_Duilib_Framework-master\ui_components\modal_wnd\file_dialog_ex.cpp	172

**Comment by nmgwddj** [comment]
在提出新的 issue 前，请在 issue 列表尝试搜索是否与你问题有相关的问题在讨论：https://github.com/netease-im/NIM_Duilib_Framework/issues/363
