### ISSUE TITLE
是否支持透明gif动画或支持透明的帧动画？

### ISSUE THREAD

**Issue by zjttcsy** [netease-im/NIM_Duilib_Framework#39]
是否支持透明gif动画或支持透明的帧动画？

**Comment by nmgwddj** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/bin/resources/themes/default/controls/controls.xml#L48
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/bin/resources/themes/default/public/animation/ani_loading.gif

`controls`  项目，跑起来看看是否是你需要的功能？

**Comment by nmgwddj** [comment]
@zjttcsy 如果以上讨论有助于
