### ISSUE TITLE
2个小问题

### ISSUE THREAD

**Issue by IULOVE** [netease-im/NIM_Duilib_Framework#4]
1: 最大化窗口后 拖动窗口会还原到原窗口大小，但最大化按钮状态没还原.
2: 我没看源码只编译了例子，layout例子那个 richedit控件应该是输入文本鼠标会消失,

**Comment by nmgwddj** [comment]
第一个问题，在应用中，窗口的最大化最小化按钮功能已经属于业务层面，在展示的示例中并没有做特别详细的示例，是希望使用者能快速理解代码执行效果。无论点击还原按钮还是拖动窗口非客户区都会得到 OnSize 变化，使用者可通过重写基类 OnSize 方法判断当前是否全屏（IsZoomed）从而显示不同的按钮状态。如下示例代码：

```
LRESULT BasicForm::OnSize(UINT uMsg, WPARAM wParam, LPARAM lParam, BOOL& bHandled)
{
	if (m_pRoot)
	{
		FindControl(L"maxbtn")->SetVisible(!::IsZoomed(m_hWnd));
		FindControl(L"restorebtn")->SetVisible(::IsZoomed(m_hWnd));
	}

	return __super::OnSize(uMsg, wParam, lParam, bHandled);
}
```

第二个问题这个应该是 Windows 的默认行为，比如在 WIN+R 运行的输入框中输入文字，鼠标指针会自动隐藏，如果您觉得这种行为并不可靠，欢迎提交 PR 来完善该功能。
