### ISSUE TITLE
tool_kits里的base怎么编译成动态库

### ISSUE THREAD

**Issue by LynnCpp** [netease-im/NIM_Duilib_Framework#41]
一直想写个工具库，功能用NIM_PC_Demo的太重了好多用不上，自己整合编译dll一直error，奈何是做web开发的...想请教tool_kits里的base怎么编译成动态库，或tool_kits里其他的组件to dll....

**Comment by caop3ng** [comment]
做web开发的为什么需要用工具库？。。。

**Comment by LynnCpp** [comment]
> 做网络开发的为什么需要用工具库？...
可能我没表达清楚，我是做web开发的，项目需要做个客户端，就自己研究着c++弄了...比如我可能会用到加密、Curl、websocket等...

**Comment by LynnCpp** [comment]
> 做网络开发的为什么需要用工具库？...

可能我没表达清楚，我是做网络开发的，项目需要做个客户端，就自己研究着C ++弄了......比如我可能会用到加密，卷曲的WebSocket等...

**Comment by LynnCpp** [comment]
> 做web开发的为什么需要用工具库？。。。

可能我没表达清楚，我是做web开发的，项目需要做个客户端，就自己研究着C ++弄了......比如我可能会用到加密，Curl、WebSocket等...

**Comment by nmgwddj** [comment]
@LynnCpp 在项目中将 base  project 属性修改为动态链接库编译，添加所需静态库链接

```
#pragma comment(lib, "Ws2_32.lib")
#pragma comment(lib, "Netapi32.lib")
#pragma comment(lib, "Snmpapi.lib")
#pragma comment(lib, "Iphlpapi.lib")
```

根据 `base_export.h` 定义指定预处理器。关于动态库和静态库的引用方式，如果您是从前端转过来的，我更建议您查一些网上的资料，或参考 Windows 核心编程介绍 dll 的章节来完成你的工作。

**Comment by LynnCpp** [comment]
> @LynnCpp 在项目中将 base project 属性修改为动态链接库编译，添加所需静态库链接
> 
> ```
> #pragma comment(lib, "Ws2_32.lib")
> #pragma comment(lib, "Netapi32.lib")
> #pragma comment(lib, "Snmpapi.lib")
> #pragma comment(lib, "Iphlpapi.lib")
> ```
> 
> 根据 `base_export.h` 定义指定预处理器。关于动态库和静态库的引用方式，如果您是从前端转过来的，我更建议您查一些网上的资料，或参考 Windows 核心编程介绍 dll 的章节来完成你的工作。

非常感谢您，按您说的操作，前几个报错解决了，，又卡在。。error LNK2001: 无法解析的外部符号 "protected: void __thiscall nbase::MessageLoop::operator=(class nbase::MessageLoop const &)" (??4MessageLoop@nbase@@IAEXABV01@@Z)	D:\Users\Desktop\C++\NIM_PC_Demo\tool_kits\base\thread_manager.obj	base，研究了半天了，T-T...

**Comment by nmgwddj** [comment]
@LynnCpp 如果您从 Web 端转向 C++ 开发，还是有部分语言特性要深入了解的，建议与这方面经验丰富的同事多沟通一下。因为类似的问题可能会接踵而至，我们通过 issue 来沟通这些问题效率是很低的，您学习的成本也非常高。

**Comment by LynnCpp** [comment]
> @LynnCpp 如果您从 Web 端转向 C++ 开发，还是有部分语言特性要深入了解的，建议与这方面经验丰富的同事多沟通一下。因为类似的问题可能会接踵而至，我们通过 issue 来沟通这些问题效率是很低的，您学习的成本也非常高。

好的 感谢！
