### ISSUE TITLE
cef版本替换后编译报错

### ISSUE THREAD

**Issue by Icepartition** [netease-im/NIM_Duilib_Framework#415]
4>------ 已启动生成: 项目: cef, 配置: Debug x64 ------
4>stdafx.cpp
4>D:\pxx\base\thread\thread_local.h(80,1): warning C4312: “reinterpret_cast”: 从“int”转换到更大的“void *”
4>D:\pxx\ui_components\menu\ui_menu.h(125,41): warning C4267: “return”: 从“size_t”转换到“int”，可能丢失数据
4>cef_form.cpp
4>main.cpp
4>正在生成代码...
4>ui_components.lib(client_app_render.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(js_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(client_app.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(bytes_write_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(util_win.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(client_app_browser.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(browser_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_control_base.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_control.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(osr_dragdrop_win.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_control_base_ui.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_control_ui.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_native_control.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(cef_js_bridge.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int)" (??0LogMessage@logging@cef@@QEAA@PEBDHH@Z)
4>ui_components.lib(client_app_render.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(js_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(client_app.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(bytes_write_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(util_win.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(client_app_browser.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(browser_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_control_base.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_control.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(osr_dragdrop_win.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_control_base_ui.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_control_ui.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_native_control.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_js_bridge.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::~LogMessage(void)" (??1LogMessage@logging@cef@@QEAA@XZ)
4>ui_components.lib(cef_control_ui.obj) : error LNK2019: 无法解析的外部符号 "public: static bool __cdecl CefBrowserHost::CreateBrowser(class CefWindowInfo const &,class scoped_refptr<class CefClient>,class CefStringBase<struct CefStringTraitsUTF16> const &,class CefStructBase<struct CefBrowserSettingsTraits> const &,class scoped_refptr<class CefDictionaryValue>,class scoped_refptr<class CefRequestContext>)" (?CreateBrowser@CefBrowserHost@@SA_NAEBVCefWindowInfo@@V?$scoped_refptr@VCefClient@@@@AEBV?$CefStringBase@UCefStringTraitsUTF16@@@@AEBV?$CefStructBase@UCefBrowserSettingsTraits@@@@V?$scoped_refptr@VCefDictionaryValue@@@@V?$scoped_refptr@VCefRequestContext@@@@@Z)，函数 "protected: virtual void __cdecl nim_comp::CefControl::ReCreateBrowser(void)" (?ReCreateBrowser@CefControl@nim_comp@@MEAAXXZ) 中引用了该符号
4>ui_components.lib(cef_native_control.obj) : error LNK2001: 无法解析的外部符号 "public: static bool __cdecl CefBrowserHost::CreateBrowser(class CefWindowInfo const &,class scoped_refptr<class CefClient>,class CefStringBase<struct CefStringTraitsUTF16> const &,class CefStructBase<struct CefBrowserSettingsTraits> const &,class scoped_refptr<class CefDictionaryValue>,class scoped_refptr<class CefRequestContext>)" (?CreateBrowser@CefBrowserHost@@SA_NAEBVCefWindowInfo@@V?$scoped_refptr@VCefClient@@@@AEBV?$CefStringBase@UCefStringTraitsUTF16@@@@AEBV?$CefStructBase@UCefBrowserSettingsTraits@@@@V?$scoped_refptr@VCefDictionaryValue@@@@V?$scoped_refptr@VCefRequestContext@@@@@Z)
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "int __cdecl CefExecuteProcess(class CefMainArgs const &,class scoped_refptr<class CefApp>,void *)" (?CefExecuteProcess@@YAHAEBVCefMainArgs@@V?$scoped_refptr@VCefApp@@@@PEAX@Z)，函数 "public: bool __cdecl nim_comp::CefManager::Initialize(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class CefStructBase<struct CefSettingsTraits> &,bool)" (?Initialize@CefManager@nim_comp@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEAV?$CefStructBase@UCefSettingsTraits@@@@_N@Z) 中引用了该符号
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "bool __cdecl CefInitialize(class CefMainArgs const &,class CefStructBase<struct CefSettingsTraits> const &,class scoped_refptr<class CefApp>,void *)" (?CefInitialize@@YA_NAEBVCefMainArgs@@AEBV?$CefStructBase@UCefSettingsTraits@@@@V?$scoped_refptr@VCefApp@@@@PEAX@Z)，函数 "public: bool __cdecl nim_comp::CefManager::Initialize(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class CefStructBase<struct CefSettingsTraits> &,bool)" (?Initialize@CefManager@nim_comp@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEAV?$CefStructBase@UCefSettingsTraits@@@@_N@Z) 中引用了该符号
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl CefShutdown(void)" (?CefShutdown@@YAXXZ)，函数 "public: void __cdecl nim_comp::CefManager::UnInitialize(void)" (?UnInitialize@CefManager@nim_comp@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "void __cdecl CefDoMessageLoopWork(void)" (?CefDoMessageLoopWork@@YAXXZ)，函数 "public: virtual bool __cdecl nim_comp::CefMessageLoopDispatcher::Dispatch(struct tagMSG const &)" (?Dispatch@CefMessageLoopDispatcher@nim_comp@@UEAA_NAEBUtagMSG@@@Z) 中引用了该符号
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "bool __cdecl CefPostTask(enum cef_thread_id_t,class base::Callback<void __cdecl(void)> const &)" (?CefPostTask@@YA_NW4cef_thread_id_t@@AEBV?$Callback@$$A6AXXZ@base@@@Z)，函数 "public: bool __cdecl nim_comp::CefManager::Initialize(class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > const &,class CefStructBase<struct CefSettingsTraits> &,bool)" (?Initialize@CefManager@nim_comp@@QEAA_NAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@AEAV?$CefStructBase@UCefSettingsTraits@@@@_N@Z) 中引用了该符号
4>ui_components.lib(browser_handler.obj) : error LNK2001: 无法解析的外部符号 "bool __cdecl CefPostTask(enum cef_thread_id_t,class base::Callback<void __cdecl(void)> const &)" (?CefPostTask@@YA_NW4cef_thread_id_t@@AEBV?$Callback@$$A6AXXZ@base@@@Z)
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "protected: __cdecl base::cef_internal::CallbackBase::CallbackBase(class base::cef_internal::BindStateBase *)" (??0CallbackBase@cef_internal@base@@IEAA@PEAVBindStateBase@12@@Z)，函数 "public: __cdecl base::Callback<void __cdecl(void)>::Callback<void __cdecl(void)><class base::cef_internal::RunnableAdapter<void (__cdecl*)(struct HWND__ *)>,void __cdecl(struct HWND__ *),void __cdecl(struct HWND__ *)>(struct base::cef_internal::BindState<class base::cef_internal::RunnableAdapter<void (__cdecl*)(struct HWND__ *)>,void __cdecl(struct HWND__ *),void __cdecl(struct HWND__ *)> *)" (??$?0V?$RunnableAdapter@P6AXPEAUHWND__@@@Z@cef_internal@base@@$$A6AXPEAUHWND__@@@Z$$A6AX0@Z@?$Callback@$$A6AXXZ@base@@QEAA@PEAU?$BindState@V?$RunnableAdapter@P6AXPEAUHWND__@@@Z@cef_internal@base@@$$A6AXPEAUHWND__@@@Z$$A6AX0@Z@cef_internal@1@@Z) 中引用了该符号
4>ui_components.lib(browser_handler.obj) : error LNK2001: 无法解析的外部符号 "protected: __cdecl base::cef_internal::CallbackBase::CallbackBase(class base::cef_internal::BindStateBase *)" (??0CallbackBase@cef_internal@base@@IEAA@PEAVBindStateBase@12@@Z)
4>ui_components.lib(cef_manager.obj) : error LNK2019: 无法解析的外部符号 "protected: __cdecl base::cef_internal::CallbackBase::~CallbackBase(void)" (??1CallbackBase@cef_internal@base@@IEAA@XZ)，函数 "public: __cdecl base::Callback<void __cdecl(void)>::~Callback<void __cdecl(void)>(void)" (??1?$Callback@$$A6AXXZ@base@@QEAA@XZ) 中引用了该符号
4>ui_components.lib(browser_handler.obj) : error LNK2001: 无法解析的外部符号 "protected: __cdecl base::cef_internal::CallbackBase::~CallbackBase(void)" (??1CallbackBase@cef_internal@base@@IEAA@XZ)
4>ui_components.lib(cef_js_bridge.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefProcessMessage> __cdecl CefProcessMessage::Create(class CefStringBase<struct CefStringTraitsUTF16> const &)" (?Create@CefProcessMessage@@SA?AV?$scoped_refptr@VCefProcessMessage@@@@AEBV?$CefStringBase@UCefStringTraitsUTF16@@@@@Z)，函数 "public: bool __cdecl nim_comp::CefJSBridge::CallCppFunction(class CefStringBase<struct CefStringTraitsUTF16> const &,class CefStringBase<struct CefStringTraitsUTF16> const &,class scoped_refptr<class CefV8Value>)" (?CallCppFunction@CefJSBridge@nim_comp@@QEAA_NAEBV?$CefStringBase@UCefStringTraitsUTF16@@@@0V?$scoped_refptr@VCefV8Value@@@@@Z) 中引用了该符号
4>ui_components.lib(client_app_render.obj) : error LNK2001: 无法解析的外部符号 "public: static class scoped_refptr<class CefProcessMessage> __cdecl CefProcessMessage::Create(class CefStringBase<struct CefStringTraitsUTF16> const &)" (?Create@CefProcessMessage@@SA?AV?$scoped_refptr@VCefProcessMessage@@@@AEBV?$CefStringBase@UCefStringTraitsUTF16@@@@@Z)
4>ui_components.lib(cef_js_bridge.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefV8Context> __cdecl CefV8Context::GetCurrentContext(void)" (?GetCurrentContext@CefV8Context@@SA?AV?$scoped_refptr@VCefV8Context@@@@XZ)，函数 "public: bool __cdecl nim_comp::CefJSBridge::CallCppFunction(class CefStringBase<struct CefStringTraitsUTF16> const &,class CefStringBase<struct CefStringTraitsUTF16> const &,class scoped_refptr<class CefV8Value>)" (?CallCppFunction@CefJSBridge@nim_comp@@QEAA_NAEBV?$CefStringBase@UCefStringTraitsUTF16@@@@0V?$scoped_refptr@VCefV8Value@@@@@Z) 中引用了该符号
4>ui_components.lib(js_handler.obj) : error LNK2001: 无法解析的外部符号 "public: static class scoped_refptr<class CefV8Context> __cdecl CefV8Context::GetCurrentContext(void)" (?GetCurrentContext@CefV8Context@@SA?AV?$scoped_refptr@VCefV8Context@@@@XZ)
4>ui_components.lib(cef_js_bridge.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefV8Value> __cdecl CefV8Value::CreateBool(bool)" (?CreateBool@CefV8Value@@SA?AV?$scoped_refptr@VCefV8Value@@@@_N@Z)，函数 "public: bool __cdecl nim_comp::CefJSBridge::ExecuteJSCallbackFunc(int,bool,class CefStringBase<struct CefStringTraitsUTF16> const &)" (?ExecuteJSCallbackFunc@CefJSBridge@nim_comp@@QEAA_NH_NAEBV?$CefStringBase@UCefStringTraitsUTF16@@@@@Z) 中引用了该符号
4>ui_components.lib(cef_js_bridge.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefV8Value> __cdecl CefV8Value::CreateString(class CefStringBase<struct CefStringTraitsUTF16> const &)" (?CreateString@CefV8Value@@SA?AV?$scoped_refptr@VCefV8Value@@@@AEBV?$CefStringBase@UCefStringTraitsUTF16@@@@@Z)，函数 "public: bool __cdecl nim_comp::CefJSBridge::ExecuteJSCallbackFunc(int,bool,class CefStringBase<struct CefStringTraitsUTF16> const &)" (?ExecuteJSCallbackFunc@CefJSBridge@nim_comp@@QEAA_NH_NAEBV?$CefStringBase@UCefStringTraitsUTF16@@@@@Z) 中引用了该符号
4>ui_components.lib(browser_handler.obj) : error LNK2019: 无法解析的外部符号 "bool __cdecl CefCurrentlyOn(enum cef_thread_id_t)" (?CefCurrentlyOn@@YA_NW4cef_thread_id_t@@@Z)，函数 "public: virtual void __cdecl nim_comp::BrowserHandler::OnAfterCreated(class scoped_refptr<class CefBrowser>)" (?OnAfterCreated@BrowserHandler@nim_comp@@UEAAXV?$scoped_refptr@VCefBrowser@@@@@Z) 中引用了该符号
4>ui_components.lib(browser_handler.obj) : error LNK2019: 无法解析的外部符号 "bool __cdecl CefPostTask(enum cef_thread_id_t,class scoped_refptr<class CefTask>)" (?CefPostTask@@YA_NW4cef_thread_id_t@@V?$scoped_refptr@VCefTask@@@@@Z)，函数 "public: void __cdecl nim_comp::BrowserHandler::CloseAllBrowser(void)" (?CloseAllBrowser@BrowserHandler@nim_comp@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(osr_dragdrop_win.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??0LogMessage@logging@cef@@QEAA@PEBDHHPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，函数 "bool __cdecl client::`anonymous namespace'::DragDataToDataObject(class scoped_refptr<class CefDragData>,struct IDataObject * *)" (?DragDataToDataObject@?A0xd8a124c0@client@@YA_NV?$scoped_refptr@VCefDragData@@@@PEAPEAUIDataObject@@@Z) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2001: 无法解析的外部符号 "public: __cdecl cef::logging::LogMessage::LogMessage(char const *,int,int,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (??0LogMessage@logging@cef@@QEAA@PEBDHHPEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
4>ui_components.lib(osr_dragdrop_win.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefStreamWriter> __cdecl CefStreamWriter::CreateForHandler(class scoped_refptr<class CefWriteHandler>)" (?CreateForHandler@CefStreamWriter@@SA?AV?$scoped_refptr@VCefStreamWriter@@@@V?$scoped_refptr@VCefWriteHandler@@@@@Z)，函数 "bool __cdecl client::`anonymous namespace'::DragDataToDataObject(class scoped_refptr<class CefDragData>,struct IDataObject * *)" (?DragDataToDataObject@?A0xd8a124c0@client@@YA_NV?$scoped_refptr@VCefDragData@@@@PEAPEAUIDataObject@@@Z) 中引用了该符号
4>ui_components.lib(osr_dragdrop_win.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefDragData> __cdecl CefDragData::Create(void)" (?Create@CefDragData@@SA?AV?$scoped_refptr@VCefDragData@@@@XZ)，函数 "class scoped_refptr<class CefDragData> __cdecl client::`anonymous namespace'::DataObjectToDragData(struct IDataObject *)" (?DataObjectToDragData@?A0xd8a124c0@client@@YA?AV?$scoped_refptr@VCefDragData@@@@PEAUIDataObject@@@Z) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl base::cef_internal::LockImpl::Lock(void)" (?Lock@LockImpl@cef_internal@base@@QEAAXXZ)，函数 "public: void __cdecl base::cef_internal::Lock::Acquire(void)" (?Acquire@Lock@cef_internal@base@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl base::cef_internal::LockImpl::Unlock(void)" (?Unlock@LockImpl@cef_internal@base@@QEAAXXZ)，函数 "public: void __cdecl base::cef_internal::Lock::Release(void)" (?Release@Lock@cef_internal@base@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl base::cef_internal::Lock::Lock(void)" (??0Lock@cef_internal@base@@QEAA@XZ)，函数 "public: __cdecl client::BytesWriteHandler::BytesWriteHandler(unsigned __int64)" (??0BytesWriteHandler@client@@QEAA@_K@Z) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "public: __cdecl base::cef_internal::Lock::~Lock(void)" (??1Lock@cef_internal@base@@QEAA@XZ)，函数 "int `public: __cdecl client::BytesWriteHandler::BytesWriteHandler(unsigned __int64)'::`1'::dtor$2" (?dtor$2@?0???0BytesWriteHandler@client@@QEAA@_K@Z@4HA) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "public: void __cdecl base::cef_internal::Lock::AssertAcquired(void)const " (?AssertAcquired@Lock@cef_internal@base@@QEBAXXZ)，函数 "public: __cdecl base::cef_internal::AutoLock::~AutoLock(void)" (??1AutoLock@cef_internal@base@@QEAA@XZ) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "private: void __cdecl base::cef_internal::Lock::CheckHeldAndUnmark(void)" (?CheckHeldAndUnmark@Lock@cef_internal@base@@AEAAXXZ)，函数 "public: void __cdecl base::cef_internal::Lock::Release(void)" (?Release@Lock@cef_internal@base@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(bytes_write_handler.obj) : error LNK2019: 无法解析的外部符号 "private: void __cdecl base::cef_internal::Lock::CheckUnheldAndMark(void)" (?CheckUnheldAndMark@Lock@cef_internal@base@@AEAAXXZ)，函数 "public: void __cdecl base::cef_internal::Lock::Acquire(void)" (?Acquire@Lock@cef_internal@base@@QEAAXXZ) 中引用了该符号
4>ui_components.lib(client_app_browser.obj) : error LNK2019: 无法解析的外部符号 "public: static class scoped_refptr<class CefCookieManager> __cdecl CefCookieManager::GetGlobalManager(class scoped_refptr<class CefCompletionCallback>)" (?GetGlobalManager@CefCookieManager@@SA?AV?$scoped_refptr@VCefCookieManager@@@@V?$scoped_refptr@VCefCompletionCallback@@@@@Z)，函数 "private: virtual void __cdecl nim_comp::ClientApp::OnContextInitialized(void)" (?OnContextInitialized@ClientApp@nim_comp@@EEAAXXZ) 中引用了该符号
4>ui_components.lib(client_app_render.obj) : error LNK2019: 无法解析的外部符号 "bool __cdecl CefRegisterExtension(class CefStringBase<struct CefStringTraitsUTF16> const &,class CefStringBase<struct CefStringTraitsUTF16> const &,class scoped_refptr<class CefV8Handler>)" (?CefRegisterExtension@@YA_NAEBV?$CefStringBase@UCefStringTraitsUTF16@@@@0V?$scoped_refptr@VCefV8Handler@@@@@Z)，函数 "private: virtual void __cdecl nim_comp::ClientApp::OnWebKitInitialized(void)" (?OnWebKitInitialized@ClientApp@nim_comp@@EEAAXXZ) 中引用了该符号
4>..\..\bin\cef64_d.exe : fatal error LNK1120: 28 个无法解析的外部命令
4>已完成生成项目“cef.vcxproj”的操作 - 失败。
========== 生成: 成功 3 个，失败 1 个，最新 0 个，跳过 0 个 ==========

cef版本替换76.1.13版本后，替换 bin 目录下 cef 的二进制文件，替换 third_part 目录下的 wrapper 层，重新编译程序将失效的接口修改为新的接口，这些都做了，然后编译demo中的cef示例程序失败，ui_components，duilib，base编译都通过了，cef示例程序的代码没有做任何修改。

**Comment by Icepartition** [comment]
cef版本替换76.1.13版本后，替换 bin 目录下 cef 的二进制文件，替换 third_part 目录下的 wrapper 层，重新编译程序将失效的接口修改为新的接口，这些都做了，然后编译demo中的cef示例程序失败，ui_components，duilib，base编译都通过了，cef示例程序的代码没有做任何修改。

**Comment by nmgwddj** [comment]
ui_components 能编译过因为它是一个静态库，不需要链接过程。所以不会出现上面链接的错误。给您一些排查思路和可能出现问题的关键步骤提醒：
 - 提示哪些符号链接不到，尝试在 cef_wrapper 层搜索该函数的实现，看看实现的源文件是否添加到了 cef_wrapper 工程。
 - 一些符号可能被一些平台宏、配置宏隔离掉了，注意观察指定函数是否在某些宏的隔离下。
 - 新版本的 libcef_dll_wrapper 文件目录变更比较大，在更新的时候不仅仅是替换文件，你还要在 VS 工程中将已经不存在的文件从工程中删除，重新扫描一下所有 libcef_dll_wrapper 目录下的文件添加到工程中（除了一些 tests 和 ui 的文件没必要添加以外）这样可以确保所有函数实现都被正确的编译到静态库最终让可执行文件链接到对应符号。

**Comment by Icepartition** [comment]
找到原因了。ui_components工程里面的附加依赖项nim_libcef.lib/nim_libcef_d.lib没有替换
