### ISSUE TITLE
在xml里面加载ScrollBar报错

### ISSUE THREAD

**Issue by QHHNB** [netease-im/NIM_Duilib_Framework#424]
直接在xml里面使用ScrollBar
![image](https://user-images.githubusercontent.com/106065825/172652656-4d4e5fa8-6167-4148-b91a-9a79db6c9ecb.png)
什么初始化都没有，就直接加载这个xml
![image](https://user-images.githubusercontent.com/106065825/172652820-47e8144f-8445-49e5-bd13-c3e8d45c193f.png)
![image](https://user-images.githubusercontent.com/106065825/172652886-32f99908-1e2d-4214-aaa1-d935aad23e5b.png)
出现以下错误，没有找到类似xml里面加载ScrollBar的例子。搞了好久没搞不明白

**Comment by nmgwddj** [comment]
ScrollBar 不能通过 xml 显示实例化，NIM duilib 并没有像其他一些 UI 框架将 ScrollBar 抽象成单独的可通过脚本组合样式控件。
要使用 ScrollBar，需要容器是 Box 子类，并且设置 hscrollbar 和 vscrollbar 属性。
更多详细使用场景可参考 NIM Demo ，它使用 NIM duilib 框架创建：https://github.com/netease-kit/NIM_PC_Demo
