### ISSUE TITLE
某些电脑下 弹窗窗口不稳定，显示不出 或半透明 或各种问题

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#43]
## 问题现象
在MAC双系统下   或 老电脑下  弹窗窗口显示有问题  尤其是debug环境下，在某些电脑上经常出现

之前提过一个issue 不过当时不知道怎么复现的， 现在知道复现原因了
不过那个 issue关闭了，不知道怎么打开

## 重现步骤

1.
复现了
使用网易纯直播demo

https://yx-web-nosdn.netease.im/package/LiveStreaming_Windows_Demo_v2.7.0.zip?download=LiveStreaming_Windows_Demo_v2.7.0.zip

添加进采集系统声音后， 点击关于， 这个弹窗就会出现黑色、或不出现等问题

debug下，频繁出现 release下 大部分机子正常 ，但有些机子也会出现弹窗窗口 不能显示等问题

2.
很奇怪 这个采集系统声音API 会影响到UI，我把它改到其它线程执行，也没效果

![59147932-64778e00-8a34-11e9-8c7e-1aa991f6131d](https://user-images.githubusercontent.com/16250519/59168121-07c8c000-8b67-11e9-9102-3b9b6fbabd97.gif)

**Comment by nmgwddj** [comment]
按您反馈的问题，我尝试去复现了一下。
1、替换 livesteaming 的 duilib 为 github 最新的 development 分支版本
2、修复一些编译不通过的位置
3、按以上步骤复现问题
我尝试了多次无论在 Debug 还是 Release 下都无法重现这个情况，您能否在您的环境下排查一下看看是哪里导致的问题，提交一个修复 PR 来帮我们解决这个问题，感谢。

**Comment by shuilan0066** [comment]
我自己的项目用的是duilib最新分支  ，采集系统声音的时候 ，在有个机子上 debug  release下 弹窗窗口显示都有问题

然后用网易的demo测了下 也是有问题 ， 尤其是在debug下 在某些电脑上 频繁出现  但在另外一些电脑上正常复现不了

上面的图也显示了， 我把系统声音去掉后，立马好了
不明白 为什么UI显示 会受这个SDK影响  

测试的机子一个是MAC 双系统 WIN10    两台 一台正常  一台频繁出现
                还有一个是09年的thinkpad win10  debug下偶现  release下 也出现过 但不多
                其它测试机正常

**Comment by shuilan0066** [comment]
我把系统声音采集去掉后， 那个频繁出现弹窗显示问题的 MAC机子就正常了

**Comment by nmgwddj** [comment]
@shuilan0066 我们遇到过一些因为预编译头导致的编译问题。您可以尝试如下做法：
1、清理项目所有生成的临时文件（tmp、obj）或直接用 git clean -xfd 清理所有未跟踪文件
2、重新编译程序查看效果

如果以上操作没有任何效果，还请跟踪一下 UI 层代码，找出根本原因来修复这个问题，仅去掉系统声音采集，可能只是规避而非彻底解决。

**Comment by shuilan0066** [comment]
好的 我再试试  只是很奇怪 为什么底层采集会影响到UI显示

**Comment by nmgwddj** [comment]
由于长时间没有收到你的反馈，我暂时关闭这个 issue，如果您发现了进一步的问题原因，可以重新打开这个 issue。
