### ISSUE TITLE
RichEdit控件在退出时崩溃

### ISSUE THREAD

**Issue by qiaohang** [netease-im/NIM_Duilib_Framework#440]
## 问题现象

修改example里中controls工程中的ControlForm::OnResourceFileLoaded函数，将设置控件文本xml内容修改为字符串L"hello"。
编译运行程序后，关闭程序时发生崩溃
```C++
void ControlForm::OnResourceFileLoaded(const std::wstring& xml)
{
	if (xml.empty())
		return;

	auto control_edit = static_cast<ui::RichEdit*>(FindControl(L"edit"));
	if (control_edit)
	{
		control_edit->SetText(L"hello"); // 修改该处代码
		control_edit->SetFocus();
		control_edit->HomeUp();
	}

	// Show about form
	nim_comp::WindowsManager::SingletonShow<AboutForm>(AboutForm::kClassName);
}
```

## 预期结果

可正常退出

## 重现步骤

见问题现象
![Crash](https://user-images.githubusercontent.com/2689089/179566030-bfd10582-3888-459f-a5e1-1ed0eb05550e.PNG)

**Comment by nmgwddj** [comment]
临时修复方法参见：
```diff
class UILIB_API ScrollableBox : public Box
{
public:
	ScrollableBox(Layout* pLayout);
	ScrollableBox(const ScrollableBox& r);
	ScrollableBox& operator=(const ScrollableBox& r) = delete;
+	~ScrollableBox() {
+		m_pHorizontalScrollBar.reset();
+		m_pHorizontalScrollBar = nullptr;
+	}
.......
```

这个问题还要在深究一下，您可以按这个思路尝试修改。

**Comment by qiaohang** [comment]
简单分析了一下原因：ScrollableBox 类中 m_pVerticalScrollBar 和 m_pHorizontalScrollBar 在析构时都会调用到 ScrollableBox::HandleMessage中（这两个成员变量也是Control的原因，Control在析构时会再处理一次kEventLast事件），因为 m_pHorizontalScrollBar 先析构并释放内存，而ScrollableBox::HandleMessage先对m_pVerticalScrollBar 进行判断，如果 有水平滚动条的话，在 m_pVerticalScrollBar 析构时 ScrollableBox::HandleMessage依然先对 m_pVerticalScrollBar 进行判断，所以就不会走到崩溃的地方。而在无水平滚动条的情况下，就触发了bug

**Comment by nmgwddj** [comment]
> 简单分析了一下原因：ScrollableBox 类中 m_pVerticalScrollBar 和 m_pHorizontalScrollBar 在析构时都会调用到 ScrollableBox::HandleMessage中（这两个成员变量也是Control的原因，Control在析构时会再处理一次kEventLast事件），因为 m_pHorizontalScrollBar 先析构并释放内存，而ScrollableBox::HandleMessage先对m_pVerticalScrollBar 进行判断，如果 有水平滚动条的话，在 m_pVerticalScrollBar 析构时 ScrollableBox::HandleMessage依然先对 m_pVerticalScrollBar 进行判断，所以就不会走到崩溃的地方。而在无水平滚动条的情况下，就触发了bug
> 
> 以上分析仅供参考 :p

除了上面提到的临时方案以外，您是否有更好的修复建议？

**Comment by qiaohang** [comment]
> > 简单分析了一下原因：ScrollableBox 类中 m_pVerticalScrollBar 和 m_pHorizontalScrollBar 在析构时都会调用到 ScrollableBox::HandleMessage中（这两个成员变量也是Control的原因，Control在析构时会再处理一次kEventLast事件），因为 m_pHorizontalScrollBar 先析构并释放内存，而ScrollableBox::HandleMessage先对m_pVerticalScrollBar 进行判断，如果 有水平滚动条的话，在 m_pVerticalScrollBar 析构时 ScrollableBox::HandleMessage依然先对 m_pVerticalScrollBar 进行判断，所以就不会走到崩溃的地方。而在无水平滚动条的情况下，就触发了bug
> > 以上分析仅供参考 :p
> 
> 除了上面提到的临时方案以外，您是否有更好的修复建议？

我的临时处理方案是在 ScrollableBox::HandleMessage 函数中对事件类型做了判断:P
```C++
if( (!IsMouseEnabled() && event.Type > kEventMouseBegin && event.Type < kEventMouseEnd) || 
     event.Type == kEventLast ) {
	if( m_pParent != NULL ) m_pParent->HandleMessageTemplate(event);
	else Box::HandleMessage(event);
	return;
}
```
