### ISSUE TITLE
CEF真窗口模式下，触控屏，点击输入框时，无法弹出虚拟键盘。

### ISSUE THREAD

**Issue by HongXG** [netease-im/NIM_Duilib_Framework#441]
CEF真窗口模式下，触控屏，点击输入框时，无法弹出虚拟键盘。
请问贵单位是否支持，如何实现虚拟键盘的弹出。

**Comment by nmgwddj** [comment]
> CEF真窗口模式下，触控屏，点击输入框时，无法弹出虚拟键盘。 请问贵单位是否支持，如何实现虚拟键盘的弹出。

升级 CEF，实测 49 真窗口的确不支持。
