### ISSUE TITLE
建议增加一个类似 spy++ 的功能

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#45]
比如在窗口上，给鼠标所在的控件增加边框，并且有一个提示框显示当前控件的 xml 内容。
增加功能原因：
1.
在参考其他项目的时候，找 xml 有些麻烦，新手更不容易快速定位到。
2.
在自己写代码的时候，也容易看到控件显示的位置。

**Comment by nmgwddj** [comment]
无法快速找到自己想找到的控件，这的确是目前 duilib 的短板，目前的情况如果是自己的项目我建议在 xml 中做好注释，代码分块，让逻辑看起来更加清晰一些。
您说的类似 spy++ 的功能，高度依赖原生 Win32 控件的一些特性，做一个外部工具来实现这样的功能对核心代码改造也是非常大的，目前阶段我们可以不会考虑制作类似的功能。

**Comment by caop3ng** [comment]
@nmgwddj ，如果提供一个debug选项，然后代码检查比如"ctrl+鼠标“消息，这个时候可以根据鼠标 pos 判断在哪个控件上，然后改变控件 border 属性。并且获取到控件的 xml，以tooltip形式显示。
这样呢？

**Comment by lovesnow** [comment]
这个实现起来也不难  ， 向目标文件注入一个dll, 使用duilib库遍历内存

**Comment by caop3ng** [comment]
> 这个实现起来也不难 ， 向目标文件注入一个dll, 使用duilib库遍历内存

感觉这样有点复杂了。
可以设置监听一个快捷键，比如“ctrl+d”,然后 duilib 内部对快捷键处理，获取到鼠标pos处的控件。
然后给控件加属性，比如 border。并且，弹出一个窗口显示这个控件的 xml。
这样就可以了。

**Comment by nmgwddj** [comment]
@caop3ng 我们可能不会单独排期来添加这个功能，但如果您有兴趣，可以单独开启一个分支来做一些基础工作，我们一起完善。

**Comment by caop3ng** [comment]
> @caop3ng 我们可能不会单独排期来添加这个功能，但如果您有兴趣，可以单独开启一个分支来做一些基础工作，我们一起完善。

@nmgwddj 嗯嗯，好的。暂时我对 duilib 了解的还不够。
