### ISSUE TITLE
VS2022编译dev分支中自带的例子controls报错

### ISSUE THREAD

**Issue by AidanMichle** [netease-im/NIM_Duilib_Framework#452]
VS2022编译dev分支中自带的例子controls报错
如下图：
![QQ截图20220907115109](https://user-images.githubusercontent.com/39211209/188785354-38b20327-5010-430c-b8d5-1bd2ab8ac4ff.png)

**Comment by nmgwddj** [comment]
1. Checkout `develop` branch
2. Run `cmake -Bbuild -G"Visual Studio 17 2022" -AWin32`
3. Run `cmake --build build --target controls`
