### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by 204065248** [netease-im/NIM_Duilib_Framework#457]
## 问题现象
在github下载完后直接编译提示`该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失`，会有很多的报错。

## 解决方案
用notepad++将所有文件改为UTF-8-BOM，即可编译通过。请问有什么更好的解决方案吗，说实话改编码改得手都麻了

**Comment by nmgwddj** [comment]
https://learn.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170
