### ISSUE TITLE
单击 Combo 控件，程序崩溃

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#46]
## 重现步骤

1.
在例子 controls 工程 controls.xml 里添加一个 Combo 代码，如下：
`
      
        <VBox>
          <Option class="circle_option_2" group="option_group" text="option1" margin="0,3,0,10" selected="true"/>
          <Option class="circle_option_2" group="option_group" text="option2" margin="0,3,0,10"/>
          <Option class="circle_option_2" group="option_group" text="option3" margin="0,3,0,10"/>
        </VBox>
        
        <HBox>
          <Combo  height="30" bordersize="1" bordercolor="red">
            <ListContainerElement height="20" text="t1" />
            <ListContainerElement height="20" text="t1" />
          </Combo>
        </HBox>
        
        <VListBox class="list" name="list" padding="5,3,5,3">
`
2.
点击 Combo 就会崩溃。
3. 
在这里崩溃了
`CPoint ptOldOrg = pRender->OffsetWindowOrg(ptOffset);`

**Comment by caop3ng** [comment]
3. 在这里崩溃了
`CPoint ptOldOrg = pRender->OffsetWindowOrg(ptOffset);`

**Comment by caop3ng** [comment]
> aaa

**Comment by caop3ng** [comment]
找到原因了，在 global.xml 里添加一个`<TextColor name="combobox_border" value="#ffe4e7eb"/>` 就可以了。
如果没有这个，`DWORD GlobalManager::GetTextColor(const std::wstring& strName)
{
	// 必须在global.xml中提前定义到颜色值
	ASSERT(m_mapTextColor[strName] != 0);
	return m_mapTextColor[strName];
}`
这里 ASSERT 会弹窗，然后 ComboWnd 会被 KILLFOCUS，然后自己 delete 自己，然后莫名其名的还有 WM_PAINT 消息没有被处理，然后处理的时候，发现 this 已经无效了，就崩溃了。

我用的是 vs2019，不知道为什么 ASSERT 不提示对话框。

**Comment by caop3ng** [comment]
应该不是 vs2019 ASSERT 不显示对话框的问题。ASSERT 的对话框还没来得及显示，程序就崩溃了。

**Comment by nmgwddj** [comment]
@caop3ng 这个问题是需要改正的，尽量不在核心代码中出现常量的颜色值，感谢您的反馈。

**Comment by caop3ng** [comment]
@nmgwddj 默认的 global.xml 里没有 combobox_border 色值。
