### ISSUE TITLE
ExtSelectClipRgn创建圆角有锯齿

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#48]
使用borderround创建的圆角有锯齿，如何改为gdi+ clip @nmgwddj

**Comment by nmgwddj** [comment]
@lovesnow 这种情况我们一般建议先可以通过图片覆盖的方式来解决锯齿的问题，类似示例代码中的 login 窗口：https://github.com/netease-im/NIM_Duilib_Framework/blob/development/bin/resources/themes/default/layouts/login.xml#L51

**Comment by bhui** [comment]
请问下图片和control大小不一致时的锯齿怎么处理呢？
