### ISSUE TITLE
自定义控件绘制本地摄像头数据没有颜色

### ISSUE THREAD

**Issue by ManyFish** [netease-im/NIM_Duilib_Framework#481]
参考PC_demo的视频通话部分，使用opencv获取本地摄像头数据对自定义控件进行绘制后，发现绘制的画面没有颜色，本地是灰度图画面；opencv获取的视频帧是正确的，是格式还是绘制问题呢？请问该如何解决？感谢

**Comment by nmgwddj** [comment]
请不要在两边提交 issue 提问。
