### ISSUE TITLE
给 HBox 添加 cursortype="hand" 属性，没有效果

### ISSUE THREAD

**Issue by caop3ng** [netease-im/NIM_Duilib_Framework#49]
## 问题现象
因为想定义一个 <HBox><Control bkimage='icon.png'/><Label /></HBox> 这样的控件。
并且想给Label和 icon 都加上 hand cursor，但是不能给 HBox 加。需要分别给每个控件加。
但是icon 和 Label 之间的空隙是 margin 产生的，没办法添加 hand cursor。
虽然空隙也可以定义一个控件，加上 hand cursor，但是这种方式感觉不好。
## 重现步骤

1.
2.

**Comment by caop3ng** [comment]
刚刚又试了下，给 HBox 加 cursor 属性是可以的，但是内部的控件不能继承这个属性。

**Comment by nmgwddj** [comment]
@caop3ng 属性不像事件，是没有冒泡或者捕获传播等特性，您还是需要给指定控件单独指定其特有的属性。

**Comment by caop3ng** [comment]
@nmgwddj 比如 HBox 里包含多个控件，想给整个 HBox 加上 cursor 属性应该只需要给 HBox 加一下就可以了，而不需要每一个子控件分别加上 cursor 属性吧？

**Comment by nmgwddj** [comment]
@caop3ng 这种情况当鼠标悬浮在子控件中，事件首先会被子控件捕获，子控件是需要单独处理 mouse hover 事件的。

**Comment by caop3ng** [comment]
@nmgwddj  有没有可能在 build 控件的时候，可以把某一些属性从父亲那里继承下来呢？

**Comment by nmgwddj** [comment]
可以重写自己关注的控件增加消息过滤器 AddMessageFilter 来实现类似功能。
