### ISSUE TITLE
shadowattached=“false“ 导致 RichEdit 透明穿透 到底怎么修复啊！还是不会！

### ISSUE THREAD

**Issue by tlbbsf** [netease-im/NIM_Duilib_Framework#494]
shadowattached=“false“ 导致 RichEdit 透明穿透 到底怎么修复啊！还是不会！  有什么地方可以交流吗？

**Comment by nmgwddj** [comment]
参考 issue：https://github.com/netease-im/NIM_Duilib_Framework/issues/164
