### ISSUE TITLE
请问怎么支持RTL？也就是阿拉伯语的使用习惯

### ISSUE THREAD

**Issue by GodLikeDota** [netease-im/NIM_Duilib_Framework#507]
目前窗口扩展属性设置：WS_EX_LAYOUTRTL后，没有效果，请问这个UI框架支持RTL吗？谢谢！

**Comment by GodLikeDota** [comment]
补充一下，设置WS_EX_LAYOUTRTL后，控件应该是都对撑位移了的，只是UI上没有更新，这里UI需要做哪些特殊处理吗？

**Comment by nmgwddj** [comment]
我们的确没有对 RTL 做过特殊的适配工作，您可能要关注 Control 基类中对控件渲染时的坐标转译情况，这可能要新增配置才能实现这种能力。
