### ISSUE TITLE
通过动态链接库创建窗口

### ISSUE THREAD

**Issue by RJJX** [netease-im/NIM_Duilib_Framework#508]
通过可执行程序(exe)创建一个窗口后，再通过调用动态链接库(dll)中方法的方式创建第二个窗口，如果创建窗口时将层窗口属性设置为true，那么第二个窗口将无法显示。

**Comment by nmgwddj** [comment]
> 通过可执行程序(exe)创建一个窗口后，再通过调用动态链接库(dll)中方法的方式创建第二个窗口，如果创建窗口时将层窗口属性设置为true，那么第二个窗口将无法显示。

目前 NIM duilib 的设计主要还是以单主线程为主，一旦 duilib 窗口开始运行就意味着所有事件流均通过内部的消息循环来驱动。这样你的主窗口可能是不受控的，并且新的事件将无法正常被派发，这样的方式可能是不行的。

可以具体描述一下为什么要单独自己创建一个窗口，看看是否有其他方案。

**Comment by RJJX** [comment]
感谢解答！情况是这样的，有一个NIM_Duilib创建的窗口主进程，在这个窗口主线程中会加载多个动态链接库(dll)的模块，有的模块会有自己的窗口，当触发特定条件时，模块会根据自己的业务创建一个窗口。

**Comment by RJJX** [comment]
> > 通过执行程序(exe)创建一个窗口后，再通过调用动态链接库(dll)中方法的方式创建第二个窗口，如果创建窗口时将层窗口属性设置为true，那么第二个窗口将无法显示。
> 
> 目前NIM duilib的设计主要还是以单主线程为主，一旦duilib窗口开始运行就意味着所有事件流均通过内部的消息循环来驱动。这样你的主窗口可能是不受控的，并且新的事件将无法正常被派发，这样的方式可能是无法的。
> 
> 可以具体描述一下为什么要单独创建一个窗口，看看是否有其他方案。

谢谢解答！情况是这样的，有一个NIM_Duilib创建的窗口主进程，在这个窗口主线程中会加载多个动态链接库(dll)的模块，有的模块会有自己的窗口，当触发特定条件时，模块会根据自己的业务创建一个窗口。
