### ISSUE TITLE
WindowsManager::SingletonShow 设置的 win_id 无效

### ISSUE THREAD

**Issue by 01haike** [netease-im/NIM_Duilib_Framework#51]
## 问题现象
当调用 WindowsManager::SingletonShow 创建窗口，给第一个参数设置窗口 id。
然后在其他地方用这个 id 调用函数 WindowsManager::GetWindow，返回的窗口指针是空的。
## 重现步骤
1.
调试发现：
```
bool WindowEx::RegisterWnd()
{
	std::wstring wnd_class_name = GetWindowClassName();
	std::wstring wnd_id = GetWindowId();
	if (!WindowsManager::GetInstance()->RegisterWindow(wnd_class_name, wnd_id, this))
	{
		return false;
	}
	return true;
}
```
窗口创建的时候，调用的是 GetWindowId(), SingletonShow 设置的 id 没有被用上。

2.

**Comment by nmgwddj** [comment]
@01haike 烦请使用标准 markdown 语法来描述多行代码（https://www.runoob.com/markdown/md-code.html），这样代码更加清晰。问题现象中描述出现该问题的直接现象，应该表现为何种状态，现在又是何种状态。如有必要请在重现步骤中描述清楚重现该问题的方法或示例代码。

**Comment by 01haike** [comment]
@nmgwddj  抱歉，之前我用过 ``` 包含代码时没有效果。然后一直也没去解决怎么包含代码。现在会了，谢谢。

**Comment by nmgwddj** [comment]
你的窗口需要从 WindowEx 类派生实现 `GetWindowId` 方法。这样你的窗口就会被注册到窗口管理类中。

**Comment by 01haike** [comment]
> 你的窗口需要从 WindowEx 类派生实现 `GetWindowId` 方法。这样你的窗口就会被注册到窗口管理类中。

我有一个窗口，但是需要显示两次。

**Comment by nmgwddj** [comment]
> > 你的窗口需要从 WindowEx 类派生实现 `GetWindowId` 方法。这样你的窗口就会被注册到窗口管理类中。
> 
> 我有一个窗口，但是需要显示两次。

可以从 `WindowImplBase` 派生。

**Comment by 01haike** [comment]
> > > 你的窗口需要从 WindowEx 类派生实现 `GetWindowId` 方法。这样你的窗口就会被注册到窗口管理类中。
> > 
> > 
> > 我有一个窗口，但是需要显示两次。
> 
> 可以从 `WindowImplBase` 派生。自己实现隐藏显示逻辑。


```
	template<typename WindowType, typename... TInstanceParams>
	static WindowType* SingletonShow(const std::wstring& window_id, const TInstanceParams&... params)
	{
		WindowType *window = (WindowType*)(WindowsManager::GetInstance()->GetWindow(WindowType::kClassName, window_id));
		if (!window)
		{
			window = new WindowType(params...);
			window->Create(NULL, WindowType::kClassName, WS_OVERLAPPEDWINDOW & ~WS_MAXIMIZEBOX, 0);
			window->CenterWindow();
			window->ShowWindow();
		}
		else
		{
			window->ActiveWindow();
		}

		return window;
	}
```
那这个函数中的 window_id 参数就没有效果了啊，没有实际用途。

**Comment by nmgwddj** [comment]
@01haike 代码稍加改造就可以实现您的需求，在 SingletonShow 时增加一些参数决定窗口是否可以重复创建，这个修改应该不是很难吧？
WindowEx 是一个辅助工具类，目的是更好的管理自己的窗口，没有把它放到 Duilib 核心代码中也是给大家提供一种管理窗口的方案，这已经偏向于业务场景了，不同的业务一份代码一定是无法完全兼容的，所以才把这个模块抽离出来，您可以根据自己业务随意修改。
