### ISSUE TITLE
关于void Window::Close(UINT nRet)函数的改进

### ISSUE THREAD

**Issue by 26597925** [netease-im/NIM_Duilib_Framework#54]
m_pRoot->SetVisible(false);修改成为ShowWindow(false, false);原始只是隐藏根节点，在close中关闭到托盘的时候，第一，这样任务栏还有项，这样点击项并不能打开，体验不好。第二，显示的时候还要操作根节点，我觉得这样代码对于很多人而言还需要找，比较麻烦。

**Comment by nmgwddj** [comment]
在 `basic` 示例代码中，如果去掉 `PostQuitMessage` 相关代码，点击窗口关闭按钮后是看不到任务栏图标的，不知道你是做过什么特殊处理？
https://github.com/netease-im/NIM_Duilib_Framework/blob/development/samples/basic/basic_form.cpp#L37

**Comment by 26597925** [comment]
我知道的你意思我是关闭的时候，不关闭换成隐藏，点击托盘然后显示出来。如果不这样修改，点击的时候就需要一些操作root节点。

**Comment by 26597925** [comment]
即便然根节点显示出来，这样感觉效果也不是很好，因为任务栏还有显示项，并不能点击后显示，感觉不好。

**Comment by nmgwddj** [comment]
您可以提供一些示例代码，我们来一起找更合适的方案，或者根据您的想法提交一个 PR 帮助我们改进这个功能。

**Comment by 26597925** [comment]
好的

**Comment by nmgwddj** [comment]
@26597925 您好，这个问题的细节我已经在 PR https://github.com/netease-im/NIM_Duilib_Framework/pull/61 中给您回复了，所以暂时关闭这个问题，如果您有其他疑问可以重新打开这个 issue。
