### ISSUE TITLE
Control控件设置alpha值的问题

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#55]
## 问题现象
在XML中设置alpha值为102，并且设置了bkimage, 这时显示后是正常的，在程序运行时，在代码中使用SetBkImage重新设置了一张新的本地图片后，就变成空白了，并没有显示新的图片

```xml
<Control name="wx_avatar" width="45" height="45" borderround="45,45" halign="center" bkimage="head/default.png" alpha="102" mouse="false" /> 
```

使用代码设置背景图后就显示异常，如果alpha值为255，则没有问题
```c++
m_pControlAvatar->SetBkImage(sLocalAvatar);
```

**Comment by nmgwddj** [comment]
这个版本针对有 alpha 属性的控件有一些改动，感谢您的反馈，我会跟踪排查这个问题。

**Comment by nmgwddj** [comment]
@lovesnow 我根据你的提示没能成功复现这个问题，我的操作步骤是：

1、复制你上面 Control 控件的信息添加到 basic 项目的 xml 中。
2、复制了两个图片到资源 basic/head 目录下
![image](https://user-images.githubusercontent.com/13995319/60777718-7bf68380-a166-11e9-8711-0cd0c36074b7.png)
3、给 Label 控件添加了一个 ButtonDown 的响应时间来切换图片
```
dynamic_cast<ui::Label*>(FindControl(L"tooltip"))->AttachButtonDown([this](ui::EventArgs* msg){
	FindControl(L"wx_avatar")->SetBkImage(L"head/wan_heads.png");
	return true;
});
```

最终效果：
![head](https://user-images.githubusercontent.com/13995319/60777729-857feb80-a166-11e9-9187-684263c8d1bf.gif)

**Comment by lovesnow** [comment]
好的  我测试下
