### ISSUE TITLE
弄个官方QQ群吧，可以让一起沟通讨论的

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#57]
如题

**Comment by qinwanlin** [comment]
支持

**Comment by nmgwddj** [comment]
即时通讯不利于开源软件和社区的发展，所以可能不会考虑。主要原因有以下几点：

1. QQ 群信息闭塞不利于搜索，而 github issue 有良好的的搜索功能。
2. QQ 群信息容易出现重复、多次提问等情况，维护成本极大，而线上社区如果能良好利用搜索和提高问题质量，将不会出现这种情况。
3. QQ 群不能良好的保存沟通记录、问题探讨记录，新入群的人很难得到问题详情，而线上的社区则不存在这种问题。
4. 更多人希望快捷解决问题，愿意帮助其他人的人凤毛麟角，像您这样的技术人员非常难得。这不利于开源软件和社区的发展。
5. 国内像 gitter、slack 一样的本土化工具很难用，与其接入不如直接使用 github 作为沟通媒介（如果您们有更好的推荐可以告知）

综上所述，除特殊要求以外，可能不会建立诸如 QQ 群、微信群等通道。
