### ISSUE TITLE
CEF 不能播放mp4

### ISSUE THREAD

**Issue by wcctml** [netease-im/NIM_Duilib_Framework#6]
## 问题现象
测试国内的视频网站（爱奇艺、腾讯视频、优酷、bilibili）基本播放不了。YouTube可以。 
使用samples/cef 打开以下链接：
https://www.bilibili.com/blackboard/html5playerhelp.html  
检测，提示不支持mp4播放。看网易云信的[文档](https://dev.yunxin.163.com/docs/product/%E9%80%9A%E7%94%A8/Demo%E6%BA%90%E7%A0%81%E5%AF%BC%E8%AF%BB/PC%E9%80%9A%E7%94%A8/Demo%20CEF%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97?#%E8%AE%A9Cef%E6%94%AF%E6%8C%81Flash%E3%80%81mp3%E3%80%81mp4)：cef2623版本可以直接支持mp3、mp4播放

**请问需要做什么操作才能开启mp4支持？**  

![image](https://user-images.githubusercontent.com/13461698/56270908-d1a02e80-6129-11e9-8bc9-1d778d90c1cd.png)

**Comment by nmgwddj** [comment]
@wcctml 主要还是版权问题，请见：https://www.zhihu.com/question/19721512
你可以自己编译（网络上有很多详细教程可以参考）或者下载其他人已经编译好的 CEF2623 增加了 MP3 和 MP4 支持的二进制包，如用于公众产品请注意版权问题。

链接：https://pan.baidu.com/s/1Hvj3H-XMWk7jmGhTalLelg
密码：d3q6

下载以后替换掉 cef_wrapper 中的所有文件和 bin 目录下的 cef 相关文件就可以跑了。
