### ISSUE TITLE
能否使用vs2008编译呢？

### ISSUE THREAD

**Issue by mengxp** [netease-im/NIM_Duilib_Framework#64]
公司的产品需要运行在老旧的系统上，用vs2008编译可以支持一下win2000……
目前用的界面库是soui，可以2008编译，但是这个库有点不好用，想换一下

**Comment by nmgwddj** [comment]
不好意思，这方面可能支持不了，现在使用了大量 C++11 语法，base 库内也基本上都是基于 C++11 的，VS2008 附带编译器不支持 C++11 的特性。
