### ISSUE TITLE
VirtualTileBox实现思路

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#65]
@nmgwddj 最近有一个需求， 是一个TileBox的布局，但是数据量较大，需要实现懒加载

如果要实现VirtualTileBox, 需要从哪里入手，能否实现一个VirtualBox的接口， 只需传入Layout就可以 :）

**Comment by nmgwddj** [comment]
VirtualTileBox 可能比 ListBox 多出来的就是横向的宽度计算。不过我觉得你可以使用 VirtualListBox 变向的实现这个功能，比如添加到 VirtualListBox 中的容器都是一个水平布局容器，而其中的内容由自己决定是加载 n ~ n 的数据列表，以此来实现一个懒加载的效果，如果 n ~ n 的数据不满足一行，则有几个就展示几个。
实现 VirtualTileBox 我没有做过太多的思考，这方面的实现可能要多翻翻代码讨论更好的实现方式。

**Comment by lovesnow** [comment]
花了2两天看了下源码， 今天终于实现了

源码分析：
1. Layout::ArrangeChild 来决定滚动区域的大小，并排列子项
2.  初始化的时候就确定了子项的数量，在滚动期间并没新增，只是改变现有子项的位置，并填充新的数据

实现思路：
实现一个VirtualTileLayout，继承TileLayout

```c++
	int npos = rc.top + pList->GetScrollPos().cy;   //  起始位置改为滚动条的起始位置

	ui::CPoint ptTile(rc.left, npos);

	int cyHeight = 0;

	// 顶部index
	int nTopBottom = 0;
	int nTopIndex = pList->GetTopElementIndex(nTopBottom);  // 获取到滚动条顶部的数据索引

````

```c++
		// 填充新数据
		int nElementIndex = nTopIndex + iCount;
		if (nElementIndex < pList->GetElementCount())
			pList->FillElement(pControl, nElementIndex);

		if ((++iCount % m_nColumns) == 0) {
			ptTile.x = iPosX;
			ptTile.y += cyHeight + m_iChildMargin;
			cyHeight = 0;
			tmpDeviation = deviation;
		}
		else {
			ptTile.x += rcTile.GetWidth();
		}
```

**Comment by lovesnow** [comment]
![3列](https://user-images.githubusercontent.com/1271747/60697181-aef90700-9f1b-11e9-966a-103d28c161d3.png)

**Comment by lovesnow** [comment]
@nmgwddj 现在的VirtualListBox也是有bug的， 如果初始化的子项条目过少， 高度变大时就会假死， 我想应该在尺寸变化时，自动计算能够放置多少子项

**Comment by eurake** [comment]
good job

**Comment by nmgwddj** [comment]
@lovesnow 的确是很棒的实现，我觉得您可以把这个例子提交上来作为一个 example 提供大家学习。让大家了解一下如何给予现有 Duilib 进行拓展开发，与自己的业务融合。

**Comment by lovesnow** [comment]
好的 我先提交一个PR，这个PR新建了一个项目，实现都在这个项目中，大家看看没问题的话 可以加入到duilib库中

**Comment by lovesnow** [comment]
@nmgwddj  感谢你们团队开源这么好的项目， c++11的特性的使用，AttachEvent方式 ，ThreadManager都使用起来太优美了， 还有大量的商业级demo（网易云信，直播，流媒体，视频播放器等) 从这个项目 学到的不仅仅是UI方面的

**Comment by lovesnow** [comment]
![2](https://user-images.githubusercontent.com/1271747/60750992-36a94900-9fe2-11e9-8dd0-15aad38d53c3.gif)

**Comment by lovesnow** [comment]
#68 已提交PR, 还需要完善，比如选中项计算等

**Comment by nmgwddj** [comment]
已经合并了你提交的示例，一个非常好的拓展进阶使用 duilib 的示例 :smile:
