### ISSUE TITLE
文档疑似有误

### ISSUE THREAD

**Issue by HowsonLiu** [netease-im/NIM_Duilib_Framework#66]
在快速上手文档[这里](https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/GETTING-STARTED.md#%E5%BC%95%E5%85%A5%E7%BA%BF%E7%A8%8B%E5%BA%93)，在`MainThread`类的'misc_thread_'变量声明中：
> std::unique_ptr\<ui::HelperThread\>	misc_thread_;

`ui::HelperThread`类未定义，我改成`MiscThread`后编译通过（是过期的类吗？）
而且在本例中并没有用到杂项线程，我感觉可以删掉整条语句

**Comment by lovesnow** [comment]
可以去掉，如果你需要一个单独线程处理事情再加上，比如下载，然后使用nbase::ThreadManager::PostXxxxx  向线程投递任务

**Comment by HowsonLiu** [comment]
好的@lovesnow谢谢:)

**Comment by nmgwddj** [comment]
@HowsonLiu 这个的确是笔误，为了演示多线程的例子时忘记删除掉这段内容，我会更新掉的，感谢您的提示。
