### ISSUE TITLE
耶~~，跟着文档新建项目，终于出来第一个窗口了。

### ISSUE THREAD

**Issue by zouhuigang** [netease-im/NIM_Duilib_Framework#69]
有2个地方开始遇到问题：

1. 

就是开始的std::unique_ptr<ui::HelperThread>	misc_thread_;,后来看到说issue是要注释掉就行。

2. 

后面一个是命令行 error D8016: “/clr”和“/MTd”命令行选项不兼容。发现创建一个窗口类，搞错了意思，创建了一个CLR windows窗体去了。直接删掉，重新创建空白的类就行了。看来是我的语文没过关。

希望多出点demo,供新手学习学习。

**Comment by lovesnow** [comment]
samples下面不是有好几个demo项目吗

**Comment by zouhuigang** [comment]
哈哈哈，demo当然越多越好了，希望多出几个交互性强的demo。

**Comment by lovesnow** [comment]
![image](https://user-images.githubusercontent.com/1271747/60762547-b7754d00-a095-11e9-903e-de07b26f14c5.png)

**Comment by lovesnow** [comment]
![image](https://user-images.githubusercontent.com/1271747/60762555-d96ecf80-a095-11e9-8371-117a69d2138e.png)
@zouhuigang

**Comment by lovesnow** [comment]
https://yunxin.163.com/im-demo
