### ISSUE TITLE
Controller中的float属性没有作用

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#7]
## 问题现象
`<Label name="test_label" text="helloworld" float="true" normaltextcolor="black" width="80" height="30" />`

## 重现步骤

1. 不显示Label
2. 而且不能设置位置
3. 增加floatalign和pos属性

-  name="float" default="false" type="BOOL" comment="是否使用绝对定位,如(true)" 
-  name="pos" default="0,0,0,0" type="RECT" comment="位置，如果为float控件则指定位置和大小，否则只指定大小,如(0,0,100,100)"
- name="floatalign" default="" type="STRING" value="left,right,center,top,bottom,vcenter" comment="用于控制float控件先对于父控件的对齐方式（left\center\right、top\vcenter\bottom）

**Comment by nmgwddj** [comment]
float 属性不太建议使用，不知道你是什么场景必须用到这个属性？当然如果代码方面缺陷我们还是一样要修复的，欢迎提交 PR 来帮助我们改善这个问题。

**Comment by lovesnow** [comment]
一些特殊的需求， 需要将某些控件显示在上层特定的位置， 不占位

**Comment by lovesnow** [comment]
![12](https://user-images.githubusercontent.com/1271747/56298822-70964c00-6165-11e9-8284-4f7b6dfeac4f.png)
类似上面的例子
图片可以在左上角浮动显示，右下角浮动显示，剧中浮动显示 （不占位）

**Comment by lovesnow** [comment]
好像没啥大问题， 我关了这个issue吧， 明天再提交一个pos属性的pr

**Comment by lovesnow** [comment]
浮动使用方法

将要设置为浮动状态的控件放到当前父节点下的最后位置
设置float="true"开启浮动状态
使用halign和valign来控制在父容器中的浮动位置, 如在右下角显示 halign="right" valign="bottom"

**Comment by nmgwddj** [comment]
建议使用父容器 Box 来替代控件的 float 属性实现浮动效果：https://github.com/netease-im/NIM_Duilib_Framework/pull/8
