### ISSUE TITLE
Label控件如何显示Emoji

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#70]
在数据库里中的数据，我用数据库管理工具查看时，可以显示emoji表情，在咱们的Label控件中显示为方框

**数据库中显示的效果：**
![image](https://user-images.githubusercontent.com/1271747/60786995-03ee8480-a18b-11e9-87d3-3b332000f247.png)

**Label控件显示为方框：**
![image](https://user-images.githubusercontent.com/1271747/60787078-35ffe680-a18b-11e9-84a1-3d1de8f1d724.png)

**Comment by lovesnow** [comment]
是不是与字体有关系

**Comment by redrains** [comment]
是的，这个和字体有关系。使用win10系统中的一些特定字体，会显示出emoji。但是如果要完全兼容自己需要的emoji，是需要自己处理emoji的unicode编码，然后自己替换为图片的

**Comment by lovesnow** [comment]
@redrains 好的 感谢提示
