### ISSUE TITLE
ScrollableBox在绘制子项时没有裁剪padding区域的bug

### ISSUE THREAD

**Issue by lovesnow** [netease-im/NIM_Duilib_Framework#72]
**这里使用Combo演示这个缺陷**
#71  这个PR修复了Combo控件在xml设置dropbox属性不起作用的bug

**在xml设置dropbox的属性如下**
```xml
bkimage="file='tag/combo_bg.png' corner='10,18,6,8'" 
padding="10,18,6,8" 
scrollbarpadding="10,18,6,8"
```
分别设置了bkimage、padding和九宫图背景，效果如下
![image](https://user-images.githubusercontent.com/1271747/60831484-46947900-a1ec-11e9-8616-de902df3dc0f.png)
上图明显可以看出子项在底部超出

**滚动时效果(GIF)**
![image](https://luoliwan.oss-cn-qingdao.aliyuncs.com/image/4.gif)
顶部和底部超出padding的区域

**问题思考**
像是在绘制子项时裁剪区域没有包含padding的原因 
代码位置：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/tool_kits/duilib/Core/Box.cpp#L1018

**尝试修复**
```c++
UiRect rcNewPaint = GetPaddingPos();
AutoClip alphaClip(pRender, rcNewPaint, m_bClip);
```

**修复后的效果(GIF)**
![image](https://luoliwan.oss-cn-qingdao.aliyuncs.com/image/5.gif)

**来个PR**
#72  看看是否可以

**Comment by nmgwddj** [comment]
如果不是经常做应用，这些细节很难被发现，感谢您提交的 PR。

**Comment by nmgwddj** [comment]
Closed by PR https://github.com/netease-im/NIM_Duilib_Framework/pull/71
