### ISSUE TITLE
Duilib每次都要重新编译的问题

### ISSUE THREAD

**Issue by RibbonServyou** [netease-im/NIM_Duilib_Framework#76]
## 问题现象
Duilib每次都要重新编译的问题
## 问题原因
多了一些不存在的引用项
ClInclude Include="Control\ButtonImpl.h"
    ClInclude Include="Control\CheckBoxImpl.h"
    ClInclude Include="Control\OptionImpl.h"
    ClInclude Include="Control\LabelImpl.h"

**Comment by nmgwddj** [comment]
感谢您的反馈，我看明白了您的问题。

**Comment by nmgwddj** [comment]
Fixed by https://github.com/netease-im/NIM_Duilib_Framework/commit/6bc11104951ac66a351dc57a70f5d7cce36bc3b7

**Comment by xuhuajie-NetEase** [comment]
仍然存在重编译问题啊
![image](https://user-images.githubusercontent.com/53515032/62200982-0ecabc80-b3b9-11e9-8e14-e145e318723c.png)
![image](https://user-images.githubusercontent.com/53515032/62201025-26a24080-b3b9-11e9-9487-c2111ff020b0.png)
删除这几项

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 我没能理解你们讨论的“重新编译”问题是什么情况，从这个 issue 中我能理解到的就是解决方案配置中有一些不存在的文件“可能”会导致你们描述的“重新编译”问题。所以我把它删除掉了。
除此以外我没能看到任何有关于这个问题的详细内容，比如它是如何发生的？怎么能重现这个情况？正常情况下是如何的？现在又是如何表现的？比如：

> 问题：尝试打开一个文件时返回 NULL
> 复现：调用 fopen("file.txt", "r") 正常情况下打开文件应该反馈一个 FILE 指针，而现在返回了一个 NULL，我尝试过 1/2/3，问题可能点 1/2/3，相关截图 ...。

一张截图或者一句详细的描述都有助于我们重现这个问题。

**Comment by xuhuajie-NetEase** [comment]
第一次编译后
再次编译
每次都要生成。


为啥要重新生成呢？
切换到诊断，再次编译
报错，缺少文件


为啥呢？
notepad打开duilib.vcxproj和duilib.vcxproj.filters，发现可以找到这些引用项，删除之


全部整理并删除
    duilib.vcxproj.filters
    <ClInclude Include="Control\ButtonImpl.h">
      <Filter>Source Files\Control</Filter>
    </ClInclude>
    <ClInclude Include="Control\CheckBoxImpl.h">
      <Filter>Source Files\Control</Filter>
    </ClInclude>
    <ClInclude Include="Control\OptionImpl.h">
      <Filter>Source Files\Control</Filter>
    </ClInclude>
  <ClInclude Include="Control\LabelImpl.h">
      <Filter>Source Files\Control</Filter>
    </ClInclude>


   duilib.vcxproj
    <ClInclude Include="Control\ButtonImpl.h" />
    <ClInclude Include="Control\CheckBoxImpl.h" />
    <ClInclude Include="Control\OptionImpl.h" />
   <ClInclude Include="Control\LabelImpl.h" />


保存后再次编译
再来一次编译呢


对，就是不会再次生成了。




那再次生成会怎么样呢？
每次都会更新pdb，lib的话，pdb就一个还好。dll的话，容易造成pdb不匹配。
| |
18767122173
|
|
18767122173@163.com
|
签名由网易邮箱大师定制
在2019年7月31日 17:44，Dylan<notifications@github.com> 写道：

@xuhuajie-NetEase 我没能理解你们讨论的“重新编译”问题是什么情况，从这个 issue 中我能理解到的就是解决方案配置中有一些不存在的文件“可能”会导致你们描述的“重新编译”问题。所以我把它删除掉了。
除此以外我没能看到任何有关于这个问题的详细内容，比如它是如何发生的？怎么能重现这个情况？正常情况下是如何的？现在又是如何表现的？比如：

问题：尝试打开一个文件时返回 NULL
复现：调用 fopen("file.txt", "r") 正常情况下打开文件应该反馈一个 FILE 指针，而现在返回了一个 NULL，我尝试过 1/2/3，问题可能点 1/2/3，相关截图 ...。

一张截图或者一句详细的描述都有助于我们重现这个问题。

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase https://github.com/netease-im/NIM_Duilib_Framework/commit/6bc11104951ac66a351dc57a70f5d7cce36bc3b7 这里的提交与您描述的内容是一致的，请注意提交的分支和你拉取的分支是否一致。

**Comment by xuhuajie-NetEase** [comment]
我拉的master，更新的develop，sorry


| |
18767122173
|
|
18767122173@163.com
|
签名由网易邮箱大师定制
在2019年7月31日 18:07，Dylan<notifications@github.com> 写道：

@xuhuajie-NetEase6bc1110 这里的提交与您描述的内容是一致的，请注意提交的分支和你拉取的分支是否一致。
