### ISSUE TITLE
RichEdit可以设置圆角和边框么?

### ISSUE THREAD

**Issue by zouhuigang** [netease-im/NIM_Duilib_Framework#77]
看文档里面好像没写

**Comment by nmgwddj** [comment]
参考通用样式，利用素材给 RichEdit 设置圆角和边框：https://github.com/netease-im/NIM_Duilib_Framework/blob/development/bin/resources/themes/default/global.xml#L158

**Comment by zouhuigang** [comment]
好的，感谢。使用图片最尴尬的就是做图都很丑，哈哈哈~
