### ISSUE TITLE
Base库无法使用生成dll导出

### ISSUE THREAD

**Issue by RibbonServyou** [netease-im/NIM_Duilib_Framework#80]
## 问题现象
目前遇到了编译缓慢问题，想把静态库切换到动态库。
尝试后warning C4251: “nbase::SupportWeakCallback::m_weakFlag”: class“std::shared_ptr<_Ty>”需要有 dll 接口由 class“nbase::SupportWeakCallback”的客户端使用
等等错误
dll导出类依赖std的东西会警告，有一定的风险（主要是跨dll资源生成与释放会崩溃）。
如果是这样的话，那么BASE_EXPORT 就形同虚设了。
## 重现步骤

#if defined(BASE_IMPLEMENTATION)
#define BASE_EXPORT __declspec(dllexport)
#else
#define BASE_EXPORT __declspec(dllimport)
#endif  // defined(BASE_IMPLEMENTATION)

1.
2.

**Comment by nmgwddj** [comment]
如果这个问题最终的现象是“跨dll资源生成与释放会崩溃”，需要你关注调用方与原始动态库文件是否使用的是相同版本的编译器，因为有些导出是 C++ 接口可能存在这种问题，或者您有更好的建议可以一起讨论。

**Comment by nmgwddj** [comment]
由于长时间没有收到你的反馈，暂时关闭此 issue，如果问题依然存在，请提供你的环境和复现这个问题的详细步骤并重新打开这个 issue。
