### ISSUE TITLE
CEF  只有JS调用C++示例 能不能加个C++调用JS示例呢

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#81]
CEF  只有JS调用C++示例 能不能加个C++调用JS示例呢

已整理完成

**Comment by cqu227hk** [comment]
![image](https://user-images.githubusercontent.com/10734949/61531142-97139e00-aa58-11e9-82ed-61cd0f7e5708.png)
可以跟踪一下“发送给js”这个按钮的操作，这就是一个C++调用JS示例

**Comment by shuilan0066** [comment]
close
