### ISSUE TITLE
xml布局中使用ScrollableBox会崩溃，报找不到控件

### ISSUE THREAD

**Issue by bhui** [netease-im/NIM_Duilib_Framework#84]
## 问题现象
xml布局中使用ScrollableBox会崩溃，报找不到控件
## 重现步骤
必现

文档：https://github.com/netease-im/NIM_Duilib_Framework/blob/master/docs/Containers/ScrollableBox.md
文档写的难道不是给人用的吗

**Comment by nmgwddj** [comment]
感谢您反馈的问题，这个问题应该是实例化控件的时候没有找到指定关键字的控件而导致的，在现有代码中您可以重写 CreateControl 接口来对这个名称的控件单独处理，另外 VListBox 和 HListBox 都是继承 ScrollableBox，您可以直接使用。我也会关注处理这个问题，让其不需要单独处理就可以使用。
```
class UILIB_API ListBox : public ScrollableBox, public IListOwner
```

**Comment by nmgwddj** [comment]
@bhui 回去看了一下 ScrollableBox 的实现，它主要提供两种布局的 ListBox（VListBox、HListBox）接口，如果想要作为控件使用需要在构造期间明确使用具体哪种布局，这与 ListBox 行为一致。所以建议直接使用 VListBox 和 HListBox，如果有其他方面需求，欢迎您再反馈。

**Comment by bhui** [comment]
不好意思，我看了UI文档里面写了ScrollableBox。
主观上套入了android的控件观念。以为ScrollableBox类似ScrollView. 以为可以直接用的，没想到只是一个接口

**Comment by nmgwddj** [comment]
@bhui 我会在文档上备注，感谢您的反馈。
