### ISSUE TITLE
移除TreeView时报错

### ISSUE THREAD

**Issue by smallevilbeast** [netease-im/NIM_Duilib_Framework#85]
treeview的父级box移除treeview时， 会报错
Unhandled exception at 0x75142CD2 in controls_d.exe: Microsoft C++ exception: std::__non_rtti_object at memory location 0x0096CF04.

```c++
pBox->Remove(pTreeView);
```
运行时会直接闪断

![image](https://user-images.githubusercontent.com/1271747/61684961-b6a71100-ad4d-11e9-99d1-04a9d28e55e7.png)

**Comment by lovesnow** [comment]
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/tool_kits/duilib/Core/Window.cpp#L974
Window这里执行了delete
```c++
		for (auto it = m_aDelayedCleanup.begin(); it != m_aDelayedCleanup.end(); it++)	delete *it;
		m_aDelayedCleanup.clear();
```
https://github.com/netease-im/NIM_Duilib_Framework/blob/master/tool_kits/duilib/Core/Box.cpp#L213
Delete调用了box的析构函数
```
Box::~Box()
{
	m_bDelayedDestroy = false;
	RemoveAll();
}
```
RemoveAll
```c++
void Box::RemoveAll()
{
	if (m_bAutoDestroy) {
		for (auto it = m_items.begin(); it != m_items.end(); it++) {
			if( m_bDelayedDestroy && m_pWindow ) m_pWindow->AddDelayedCleanup((*it));             
			else delete (*it);
		}
	}

	m_items.clear();
	Arrange();   //  析构时，给RemoveAll传一个参数不让arrange 可以解决这个问题
}
```
Arrange();  析构时，给RemoveAll传一个参数不让arrange 可以解决这个问题， 奇怪的只有Remove TreeView的时候会出错

**Comment by nmgwddj** [comment]
## 问题原因

在控件插入时，将所有的子控件都插入为 TreeView 的子节点，由于 TreeNode 重写了 SetWindow 方法，在 SetWindow 时，将要添加的子节点父容器设置为 ParentNode 了。
而销毁时是根据 TreeView 的所有子节点（一维的数据，非树形结构）数组依次进行销毁的，类似 ListBox 的做法，但由于并非所有子节点的父容器都是 TreeView 或 TreeView 中隐藏的 RootNode，导致第一个 ParentNode 被销毁时，后面的子节点就获取不到父容器指针了。

## 解决方案

将所有 TreeNode 的父容器都设置为 TreeView 中隐藏的 RootNode，而不影响 GetParentNode 方法，在整个 TreeView 销毁时，RootNode 由于是一个智能指针，也会跟随销毁。

**Comment by lovesnow** [comment]
辛苦啦 3Q

**Comment by lovesnow** [comment]
@nmgwddj  测试了下， 问题依然存在 

在controls项目 可以测试下
```c++
	ui::Button* btn = dynamic_cast<ui::Button*>(FindControl(L"btn_blue"));
	btn->AttachClick([tree](ui::EventArgs* args)->bool{
		tree->GetParent()->Remove(tree);
		return false;
	});
```

**Comment by nmgwddj** [comment]
@lovesnow 好的，感谢反馈，我试了一下的确还存在，可能我修改的时候本地有缓存代码没有上传，现在被 reset 掉了。

**Comment by nmgwddj** [comment]
@lovesnow https://github.com/netease-im/NIM_Duilib_Framework/commit/c627eff95dec7e4936b0d4f391842ce5b900acc2
我 revert 了之前的提交，重新梳理了一下移除的流程，你可以拉取一下最新代码来测试一下。具体的原因我稍后会补上。

**Comment by lovesnow** [comment]
@nmgwddj  测试了下  controls的例子 正常， 但是我项目上使用这个还是会出错， 我再看看 是什么原因  晚点再反馈

**Comment by nmgwddj** [comment]
@lovesnow 可以提供下最小化示例我们一起排查一下。
