### ISSUE TITLE
是否支持触摸屏、触摸大屏（教育软件）？

### ISSUE THREAD

**Issue by Gocpy** [netease-im/NIM_Duilib_Framework#88]
请问这个版本的CEF支不支持触摸屏手势（点、按、拖拽、滑动）？

**Comment by nmgwddj** [comment]
这个取决于你使用真窗口还是离屏渲染模式，如果是真窗口模式的话，理论上只要 CEF 对类似消息做过处理都是没有问题的。你可以使用 smaples 中的 CEF 示例（默认真窗口模式）来做测试。
