### ISSUE TITLE
我看最近提交的代码支持了tab切换焦点控件，这个如何使用？

### ISSUE THREAD

**Issue by smallevilbeast** [netease-im/NIM_Duilib_Framework#90]
https://github.com/netease-im/NIM_Duilib_Framework/commit/bef5c9ac8e57b9660b4e6d09758e1836fd6ee4e2

测试了 Button控件现在可以切换，RichEdit 按tab键输入的是tab, 不是切换 

还有就是box移除treeview的问题依然存在

**Comment by nmgwddj** [comment]
参考这里的回复：https://github.com/netease-im/NIM_Duilib_Framework/issues/31#issuecomment-512148697

**Comment by lovesnow** [comment]
@nmgwddj  RichEdit 加wanttab为false后 可用， 我看代码Control控件默认都支持tab切换， 但很多情况 

Label (用户名): RichEdit
Label(密码): RichEdit 

这样的布局， 只让RichEdit切换， 是不是应该设置一个参数 可以关掉Label的tab

**Comment by nmgwddj** [comment]
@lovesnow 可以提供一下最小化示例程序。

**Comment by nmgwddj** [comment]
这个是可以的，我认为有两种途径，或者以下两种都可作为标注。

 - 第一种是让控件在禁用状态下不响应 TAB。
 - 第二种就是你说的可以加一个参数来决定让控件是否接收 TAB。

虽然修改量不，但实现以上功能都需要调整现有代码，具体哪种方案比较好或者是不是有更好的方案我们要讨论以下，您如果有更好的观点可以告诉我们来一起完善这个功能。

**Comment by nmgwddj** [comment]
在最新的代码中，如果希望控件不响应 Tab，可以将控件设置为禁用状态，这也类似一些其他 UI 框架中的实现，如果有其他问题可以重新打开这个 Issue 来讨论。
