### ISSUE TITLE
CEF回调OnBeforePopup中创建子Browser会失败, 子窗口消失了

### ISSUE THREAD

**Issue by gh0stOne** [netease-im/NIM_Duilib_Framework#91]
## 重现步骤

1. CefControlBase::OnBeforePopup实现中添加
client = new nim_cef::BrowserHandler(); 
windowInfo.SetAsChild(hRoot, rcPos);

**Comment by nmgwddj** [comment]
子窗口是不需要你手工创建的，参考 CEF 注释

```
  // Called on the IO thread before a new popup browser is created. The
  // |browser| and |frame| values represent the source of the popup request. The
  // |target_url| and |target_frame_name| values indicate where the popup
  // browser should navigate and may be empty if not specified with the request.
  // The |target_disposition| value indicates where the user intended to open
  // the popup (e.g. current tab, new tab, etc). The |user_gesture| value will
  // be true if the popup was opened via explicit user gesture (e.g. clicking a
  // link) or false if the popup opened automatically (e.g. via the
  // DomContentLoaded event). The |popupFeatures| structure contains additional
  // information about the requested popup window. To allow creation of the
  // popup browser optionally modify |windowInfo|, |client|, |settings| and
  // |no_javascript_access| and return false. To cancel creation of the popup
  // browser return true. The |client| and |settings| values will default to the
  // source browser's values. If the |no_javascript_access| value is set to
  // false the new browser will not be scriptable and may not be hosted in the
  // same renderer process as the source browser.
  ///
  /*--cef(optional_param=target_url,optional_param=target_frame_name)--*/
  virtual bool OnBeforePopup(CefRefPtr<CefBrowser> browser,
                             CefRefPtr<CefFrame> frame,
                             const CefString& target_url,
                             const CefString& target_frame_name,
                             WindowOpenDisposition target_disposition,
                             bool user_gesture,
                             const CefPopupFeatures& popupFeatures,
                             CefWindowInfo& windowInfo,
                             CefRefPtr<CefClient>& client,
                             CefBrowserSettings& settings,
                             bool* no_javascript_access) {
    return false;
  }
```

**Comment by gh0stOne** [comment]
> 子窗口是不需要你手工创建的，参考 CEF 注释
> 
> ```
>   // Called on the IO thread before a new popup browser is created. The
>   // |browser| and |frame| values represent the source of the popup request. The
>   // |target_url| and |target_frame_name| values indicate where the popup
>   // browser should navigate and may be empty if not specified with the request.
>   // The |target_disposition| value indicates where the user intended to open
>   // the popup (e.g. current tab, new tab, etc). The |user_gesture| value will
>   // be true if the popup was opened via explicit user gesture (e.g. clicking a
>   // link) or false if the popup opened automatically (e.g. via the
>   // DomContentLoaded event). The |popupFeatures| structure contains additional
>   // information about the requested popup window. To allow creation of the
>   // popup browser optionally modify |windowInfo|, |client|, |settings| and
>   // |no_javascript_access| and return false. To cancel creation of the popup
>   // browser return true. The |client| and |settings| values will default to the
>   // source browser's values. If the |no_javascript_access| value is set to
>   // false the new browser will not be scriptable and may not be hosted in the
>   // same renderer process as the source browser.
>   ///
>   /*--cef(optional_param=target_url,optional_param=target_frame_name)--*/
>   virtual bool OnBeforePopup(CefRefPtr<CefBrowser> browser,
>                              CefRefPtr<CefFrame> frame,
>                              const CefString& target_url,
>                              const CefString& target_frame_name,
>                              WindowOpenDisposition target_disposition,
>                              bool user_gesture,
>                              const CefPopupFeatures& popupFeatures,
>                              CefWindowInfo& windowInfo,
>                              CefRefPtr<CefClient>& client,
>                              CefBrowserSettings& settings,
>                              bool* no_javascript_access) {
>     return false;
>   }
> ```

已解决,thx
