### ISSUE TITLE
development 分支 VS2017 编译不过

### ISSUE THREAD

**Issue by quanzhuo** [netease-im/NIM_Duilib_Framework#92]
## 问题现象
pull 了一下 development 分支最新的更改之后，编译不过。报了大量IsKeyboardEnabled() 未定义的错误，后来发现该函数与commit bef5c9ac8e57b9660b4e6d09758e1836fd6ee4e2 有关。 revert掉该笔提交后，编译通过。

## 重现步骤

1. 尝试 git clean -fdx 之后重新编译 development 分支
2. 报大量 IsKeyboardEnabled() 未定义的错误。

**Comment by nmgwddj** [comment]
@quanzhuo 我将代码 reset  到 development 最后一次提交，修改所有项目平台工具集为 VS2017 / VS2017 Windows XP 后都没有遇到你描述的问题，你可以做以下操作试试能否解决你的问题。

```
git fetch
git reset --hard origin/development
```

**Comment by nmgwddj** [comment]
由于长时间没有收到你的反馈，暂时关闭此 issue，如果问题依然存在，请提供你的环境和复现这个问题的详细步骤并重新打开这个 issue。
