### ISSUE TITLE
EVENT 事件 无动画效果

### ISSUE THREAD

**Issue by shuilan0066** [netease-im/NIM_Duilib_Framework#94]
## 问题现象

![image](https://user-images.githubusercontent.com/16250519/62109244-76600980-b2de-11e9-9201-ea11ea38de2e.png)

![image](https://user-images.githubusercontent.com/16250519/62109283-84ae2580-b2de-11e9-8dd2-4228bac64ecf.png)

设置了动画效果，但是用事件时，VBox立即显示或消失 ，没有动画过度

但是使用代码 AttachMouseHover   AttachMouseLeave 中控制其隐藏于显示的时候，是有动画效果的

希望， 直接使用Event控制时，也能实现动画效果

**Comment by nmgwddj** [comment]
`visible` 改为 `fadevisible`

```
<Event type="mouseenter" receiver="show_box" applyattribute="fadevisible=&quot;true&quot;"/>
<Event type="mouseleave" receiver="show_box" applyattribute="fadevisible=&quot;false&quot;"/>
```
