### ISSUE TITLE
borderround 属性的圆角没有边框

### ISSUE THREAD

**Issue by xuhuajie-NetEase** [netease-im/NIM_Duilib_Framework#97]
## 问题现象
borderround 属性的圆角没有边框
## 重现步骤
controls.xml中

        VListBox class="list" name="list" padding="5,3,5,3" bordersize="1" bordercolor="red" borderround="15,15"

1.
2.
![image](https://user-images.githubusercontent.com/53515032/62208269-e9de4580-b3c8-11e9-98f7-2260eb6ea059.png)
有圆角出现但无边框

**Comment by xuhuajie-NetEase** [comment]
<VListBox class="list" name="list" padding="5,3,5,3" bordersize="1" bordercolor="red" borderround="15,15">

**Comment by xuhuajie-NetEase** [comment]
![image](https://user-images.githubusercontent.com/53515032/62261395-bb537f80-b447-11e9-8c92-e1521e6fb1a8.png)
void Control::PaintBorder(IRenderContext* pRender)
{
	if (m_strBorderColor.empty()) {
		return;
	}
	DWORD dwBorderColor = 0;
	if (!m_strBorderColor.empty()) {
		dwBorderColor = GlobalManager::GetTextColor(m_strBorderColor);
	}

	if(dwBorderColor != 0) {
		//判断是否需要画圆角矩阵
		if ((m_cxyBorderRound.cx > 0 || m_cxyBorderRound.cy > 0) && m_nBorderSize > 0)
		{
			UiRect rcDraw = m_rcItem;
			int nDeltaValue = m_nBorderSize / 2;
			rcDraw.top += nDeltaValue;
			rcDraw.bottom -= nDeltaValue;
			if (m_nBorderSize % 2 != 0) {
				rcDraw.bottom -= 1;
			}
			rcDraw.left += nDeltaValue;
			rcDraw.right -= nDeltaValue;
			if (m_nBorderSize % 2 != 0) {
				rcDraw.right -= 1;
			}
			pRender->DrawRoundRect(rcDraw, m_cxyBorderRound, m_nBorderSize, dwBorderColor);
		}

**Comment by xuhuajie-NetEase** [comment]
void RenderContext_GdiPlus::DrawRoundRect(const UiRect& rc, const SIZE& round, int nSize, DWORD dwPenColor)
{
	Gdiplus::Graphics graphics(m_hDC);
	graphics.SetSmoothingMode(Gdiplus::SmoothingModeAntiAlias);
	Gdiplus::Pen pen(Gdiplus::Color(dwPenColor), (Gdiplus::REAL)nSize);
	Gdiplus::SolidBrush brShadow(Gdiplus::Color(255, 255, 255));
	Gdiplus::GraphicsPath m_pPath;
	m_pPath.AddArc(rc.left, rc.top, round.cx * 2, round.cy * 2, 180, 90);
	m_pPath.AddLine(rc.left + round.cx, rc.top, rc.right - round.cx * 2, rc.top);
	m_pPath.AddArc(rc.left + rc.GetWidth() - round.cx * 2, rc.top, round.cx * 2, round.cy * 2, 270, 90);
	m_pPath.AddLine(rc.right, rc.top + round.cy * 2, rc.right, rc.top + rc.GetHeight() - round.cy * 2);
	m_pPath.AddArc(rc.left + rc.GetWidth() - round.cx * 2, rc.top + rc.GetHeight() - round.cy * 2, round.cx * 2, round.cy * 2, 0, 90);
	m_pPath.AddLine(rc.right - round.cx * 2, rc.bottom, rc.left + round.cx * 2, rc.bottom);
	m_pPath.AddArc(rc.left, rc.bottom - round.cy * 2, round.cx * 2, round.cy * 2, 90, 90);
	m_pPath.AddLine(rc.left, rc.bottom - round.cy * 2, rc.left, rc.top + round.cy * 2);
	m_pPath.CloseFigure();

	graphics.FillPath(&brShadow, &m_pPath);
	graphics.DrawPath(&pen, &m_pPath);
	

}

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 如果您有更好的解决方案，可以创建一个 PR，来帮我们完善这个功能。

**Comment by xuhuajie-NetEase** [comment]
DrawRoundRect功能代码如上，PaintBorder的判断逻辑需要补全（我写的比较简略，以下是Duilib的判断逻辑，Duilib使用的GDI，锯齿太明显了）
	if(m_rcBorderSize.left > 0 && (m_dwBorderColor != 0 || m_dwFocusBorderColor != 0)) {
		if( m_cxyBorderRound.cx > 0 || m_cxyBorderRound.cy > 0 )//画圆角边框
		{
			if (IsFocused() && m_dwFocusBorderColor != 0)
				CRenderEngine::DrawRoundRect(hDC, m_rcItem, m_rcBorderSize.left, m_cxyBorderRound.cx, m_cxyBorderRound.cy, GetAdjustColor(m_dwFocusBorderColor), m_nBorderStyle);
			else
				CRenderEngine::DrawRoundRect(hDC, m_rcItem, m_rcBorderSize.left, m_cxyBorderRound.cx, m_cxyBorderRound.cy, GetAdjustColor(m_dwBorderColor), m_nBorderStyle);
		}

**Comment by xuhuajie-NetEase** [comment]
我把过程写到这里了
https://www.cnblogs.com/xuhuajie/p/11281075.html

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 感谢您提供的解决方案，如果您不介意更希望您能将修改的 commit 创建为 pull request 到开发分支，在 issue 中讨论问题和实现原理，具体代码由 commit 来呈现。

这样代码可以只围绕一个位置来进行修改，大家也可以在项目中看到您做过的贡献、产生的提交和提交中的详情。github issue 能被搜索引擎更好的索引，其他人也能通过你提出的问题和解决问题的 commit 找到解决方案。另外 commit history 助于追溯代码修改，因为我们并不能保证贴在 issue 中的代码未来不会被修改。

**Comment by nmgwddj** [comment]
@xuhuajie-NetEase 当容器的背景色与窗体背景色有非常大的差异时，比如窗体背景色是浅色色，而容器背景色是深色。绘制圆角边框时缩小了一个像素会明显看到步进4个角有超出，4个边也有明显的超出，所以我还是暂时注释掉了缩小一个像素的实现。您可以根据自己的情况重写一下这个方法。

彻底解决这个问题可能要修改比较多的内容，替代的方案除了重写一下这个方法，也可以使用图片的方案。两个方案虽都不完美，但可以解决现有的问题。

**Comment by nmgwddj** [comment]
Finished by commit: https://github.com/netease-im/NIM_Duilib_Framework/commit/7c8332bf9f69d99b2d0cc4d05efac32c25a408cb
